--liquibase formatted sql

--changeset Ondrej:1

ALTER TABLE EAADMIN.CUSTOMER ADD COLUMN CUSTOMER_PREFIX VARCHAR(16);
ALTER TABLE EAADMIN.CUSTOMER ADD COLUMN CUSTOMER_SUFFIX VARCHAR(16);
ALTER TABLE EAADMIN.CUSTOMER ADD COLUMN HOSTNAME_PREFIX VARCHAR(64);

REORG TABLE EAADMIN.CUSTOMER;