//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 12:15:07 PM CST 
//


package com.ibm.asset.swkbt.genSchema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for KbIdentityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="KbIdentityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Manufacturers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Manufacturer" type="{}ManufacturerType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="PartNumbers" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="PartNumber" type="{}PartNumberType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SoftwareItems" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;sequence>
 *                     &lt;element name="DistributedProduct" type="{}DistributedProductType" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="DistributedVersion" type="{}DistributedVersionType" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="DistributedRelease" type="{}DistributedReleaseType" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="Variation" type="{}VariationType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                   &lt;sequence>
 *                     &lt;element name="MainframeProduct" type="{}MainframeProductType" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="MainframeVersion" type="{}MainframeVersionType" maxOccurs="unbounded" minOccurs="0"/>
 *                     &lt;element name="MainframeFeature" type="{}MainframeFeatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Relationships" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Relationship" type="{}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Signatures" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element name="FileSignature" type="{}FileSignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="RegistrySignature" type="{}RegistrySignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="InstallRegistrySignature" type="{}InstallRegistrySignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="ApplicationServerSignature" type="{}ApplicationServerSignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="J2eeApplicationSignature" type="{}J2EeApplicationSignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="FilterSignature" type="{}FilterSignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="XslmIdSignature" type="{}XslmIdSignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="OtherSignature" type="{}OtherSignatureType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="guid" type="{}GUIDType" />
 *       &lt;attribute name="owner" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="contact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataVersion" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="lastModification" type="{}dateTimeType" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "KbIdentityType", propOrder = {
    "manufacturers",
    "partNumbers",
    "softwareItems",
    "relationships",
    "signatures",
    "additional"
})
public class KbIdentityType {

    @XmlElement(name = "Manufacturers")
    protected KbIdentityType.Manufacturers manufacturers;
    @XmlElement(name = "PartNumbers")
    protected KbIdentityType.PartNumbers partNumbers;
    @XmlElement(name = "SoftwareItems")
    protected KbIdentityType.SoftwareItems softwareItems;
    @XmlElement(name = "Relationships")
    protected KbIdentityType.Relationships relationships;
    @XmlElement(name = "Signatures")
    protected KbIdentityType.Signatures signatures;
    protected AdditionalStructureType additional;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "owner")
    protected String owner;
    @XmlAttribute(name = "copyright")
    protected String copyright;
    @XmlAttribute(name = "contact")
    protected String contact;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "dataVersion")
    protected Long dataVersion;
    @XmlAttribute(name = "lastModification")
    protected XMLGregorianCalendar lastModification;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the manufacturers property.
     * 
     * @return
     *     possible object is
     *     {@link KbIdentityType.Manufacturers }
     *     
     */
    public KbIdentityType.Manufacturers getManufacturers() {
        return manufacturers;
    }

    /**
     * Sets the value of the manufacturers property.
     * 
     * @param value
     *     allowed object is
     *     {@link KbIdentityType.Manufacturers }
     *     
     */
    public void setManufacturers(KbIdentityType.Manufacturers value) {
        this.manufacturers = value;
    }

    /**
     * Gets the value of the partNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link KbIdentityType.PartNumbers }
     *     
     */
    public KbIdentityType.PartNumbers getPartNumbers() {
        return partNumbers;
    }

    /**
     * Sets the value of the partNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link KbIdentityType.PartNumbers }
     *     
     */
    public void setPartNumbers(KbIdentityType.PartNumbers value) {
        this.partNumbers = value;
    }

    /**
     * Gets the value of the softwareItems property.
     * 
     * @return
     *     possible object is
     *     {@link KbIdentityType.SoftwareItems }
     *     
     */
    public KbIdentityType.SoftwareItems getSoftwareItems() {
        return softwareItems;
    }

    /**
     * Sets the value of the softwareItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link KbIdentityType.SoftwareItems }
     *     
     */
    public void setSoftwareItems(KbIdentityType.SoftwareItems value) {
        this.softwareItems = value;
    }

    /**
     * Gets the value of the relationships property.
     * 
     * @return
     *     possible object is
     *     {@link KbIdentityType.Relationships }
     *     
     */
    public KbIdentityType.Relationships getRelationships() {
        return relationships;
    }

    /**
     * Sets the value of the relationships property.
     * 
     * @param value
     *     allowed object is
     *     {@link KbIdentityType.Relationships }
     *     
     */
    public void setRelationships(KbIdentityType.Relationships value) {
        this.relationships = value;
    }

    /**
     * Gets the value of the signatures property.
     * 
     * @return
     *     possible object is
     *     {@link KbIdentityType.Signatures }
     *     
     */
    public KbIdentityType.Signatures getSignatures() {
        return signatures;
    }

    /**
     * Sets the value of the signatures property.
     * 
     * @param value
     *     allowed object is
     *     {@link KbIdentityType.Signatures }
     *     
     */
    public void setSignatures(KbIdentityType.Signatures value) {
        this.signatures = value;
    }

    /**
     * Gets the value of the additional property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStructureType }
     *     
     */
    public AdditionalStructureType getAdditional() {
        return additional;
    }

    /**
     * Sets the value of the additional property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStructureType }
     *     
     */
    public void setAdditional(AdditionalStructureType value) {
        this.additional = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the dataVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataVersion() {
        return dataVersion;
    }

    /**
     * Sets the value of the dataVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataVersion(Long value) {
        this.dataVersion = value;
    }

    /**
     * Gets the value of the lastModification property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModification() {
        return lastModification;
    }

    /**
     * Sets the value of the lastModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModification(XMLGregorianCalendar value) {
        this.lastModification = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Manufacturer" type="{}ManufacturerType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "manufacturer"
    })
    public static class Manufacturers {

        @XmlElement(name = "Manufacturer")
        protected List<ManufacturerType> manufacturer;

        /**
         * Gets the value of the manufacturer property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the manufacturer property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getManufacturer().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ManufacturerType }
         * 
         * 
         */
        public List<ManufacturerType> getManufacturer() {
            if (manufacturer == null) {
                manufacturer = new ArrayList<ManufacturerType>();
            }
            return this.manufacturer;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="PartNumber" type="{}PartNumberType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "partNumber"
    })
    public static class PartNumbers {

        @XmlElement(name = "PartNumber")
        protected List<PartNumberType> partNumber;

        /**
         * Gets the value of the partNumber property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the partNumber property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPartNumber().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PartNumberType }
         * 
         * 
         */
        public List<PartNumberType> getPartNumber() {
            if (partNumber == null) {
                partNumber = new ArrayList<PartNumberType>();
            }
            return this.partNumber;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Relationship" type="{}RelationshipType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "relationship"
    })
    public static class Relationships {

        @XmlElement(name = "Relationship")
        protected List<RelationshipType> relationship;

        /**
         * Gets the value of the relationship property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the relationship property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRelationship().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link RelationshipType }
         * 
         * 
         */
        public List<RelationshipType> getRelationship() {
            if (relationship == null) {
                relationship = new ArrayList<RelationshipType>();
            }
            return this.relationship;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;element name="FileSignature" type="{}FileSignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="RegistrySignature" type="{}RegistrySignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="InstallRegistrySignature" type="{}InstallRegistrySignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="ApplicationServerSignature" type="{}ApplicationServerSignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="J2eeApplicationSignature" type="{}J2EeApplicationSignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="FilterSignature" type="{}FilterSignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="XslmIdSignature" type="{}XslmIdSignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="OtherSignature" type="{}OtherSignatureType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fileSignatureOrRegistrySignatureOrInstallRegistrySignature"
    })
    public static class Signatures {

        @XmlElements({
            @XmlElement(name = "FileSignature", type = FileSignatureType.class),
            @XmlElement(name = "RegistrySignature", type = RegistrySignatureType.class),
            @XmlElement(name = "InstallRegistrySignature", type = InstallRegistrySignatureType.class),
            @XmlElement(name = "ApplicationServerSignature", type = ApplicationServerSignatureType.class),
            @XmlElement(name = "J2eeApplicationSignature", type = J2EeApplicationSignatureType.class),
            @XmlElement(name = "FilterSignature", type = FilterSignatureType.class),
            @XmlElement(name = "XslmIdSignature", type = XslmIdSignatureType.class),
            @XmlElement(name = "OtherSignature", type = OtherSignatureType.class)
        })
        protected List<SignatureType> fileSignatureOrRegistrySignatureOrInstallRegistrySignature;

        /**
         * Gets the value of the fileSignatureOrRegistrySignatureOrInstallRegistrySignature property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fileSignatureOrRegistrySignatureOrInstallRegistrySignature property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFileSignatureOrRegistrySignatureOrInstallRegistrySignature().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileSignatureType }
         * {@link RegistrySignatureType }
         * {@link InstallRegistrySignatureType }
         * {@link ApplicationServerSignatureType }
         * {@link J2EeApplicationSignatureType }
         * {@link FilterSignatureType }
         * {@link XslmIdSignatureType }
         * {@link OtherSignatureType }
         * 
         * 
         */
        public List<SignatureType> getFileSignatureOrRegistrySignatureOrInstallRegistrySignature() {
            if (fileSignatureOrRegistrySignatureOrInstallRegistrySignature == null) {
                fileSignatureOrRegistrySignatureOrInstallRegistrySignature = new ArrayList<SignatureType>();
            }
            return this.fileSignatureOrRegistrySignatureOrInstallRegistrySignature;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice maxOccurs="unbounded" minOccurs="0">
     *         &lt;sequence>
     *           &lt;element name="DistributedProduct" type="{}DistributedProductType" maxOccurs="unbounded" minOccurs="0"/>
     *           &lt;element name="DistributedVersion" type="{}DistributedVersionType" maxOccurs="unbounded" minOccurs="0"/>
     *           &lt;element name="DistributedRelease" type="{}DistributedReleaseType" maxOccurs="unbounded" minOccurs="0"/>
     *           &lt;element name="Variation" type="{}VariationType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;/sequence>
     *         &lt;sequence>
     *           &lt;element name="MainframeProduct" type="{}MainframeProductType" maxOccurs="unbounded" minOccurs="0"/>
     *           &lt;element name="MainframeVersion" type="{}MainframeVersionType" maxOccurs="unbounded" minOccurs="0"/>
     *           &lt;element name="MainframeFeature" type="{}MainframeFeatureType" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;/sequence>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "distributedProductAndDistributedVersionAndDistributedRelease"
    })
    public static class SoftwareItems {

        @XmlElements({
            @XmlElement(name = "DistributedProduct", type = DistributedProductType.class),
            @XmlElement(name = "DistributedVersion", type = DistributedVersionType.class),
            @XmlElement(name = "DistributedRelease", type = DistributedReleaseType.class),
            @XmlElement(name = "Variation", type = VariationType.class),
            @XmlElement(name = "MainframeProduct", type = MainframeProductType.class),
            @XmlElement(name = "MainframeVersion", type = MainframeVersionType.class),
            @XmlElement(name = "MainframeFeature", type = MainframeFeatureType.class)
        })
        protected List<Object> distributedProductAndDistributedVersionAndDistributedRelease;

        /**
         * Gets the value of the distributedProductAndDistributedVersionAndDistributedRelease property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the distributedProductAndDistributedVersionAndDistributedRelease property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDistributedProductAndDistributedVersionAndDistributedRelease().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DistributedProductType }
         * {@link DistributedVersionType }
         * {@link DistributedReleaseType }
         * {@link VariationType }
         * {@link MainframeProductType }
         * {@link MainframeVersionType }
         * {@link MainframeFeatureType }
         * 
         * 
         */
        public List<Object> getDistributedProductAndDistributedVersionAndDistributedRelease() {
            if (distributedProductAndDistributedVersionAndDistributedRelease == null) {
                distributedProductAndDistributedVersionAndDistributedRelease = new ArrayList<Object>();
            }
            return this.distributedProductAndDistributedVersionAndDistributedRelease;
        }

    }

}
