//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 12:15:07 PM CST 
//


package com.ibm.asset.swkbt.genSchema;

import java.util.HashMap;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for MainframeVersionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MainframeVersionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="guid" use="required" type="{}GUIDType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="manufacturer" type="{}GUIDType" />
 *       &lt;attribute name="identifier" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="product" use="required" type="{}GUIDType" />
 *       &lt;attribute name="ibmCustomerAgreement" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="IPLA" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VUE" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="SS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="softwarePricingType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subCapacityLicensing" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MainframeVersionType")
public class MainframeVersionType {

    @XmlAttribute(name = "guid", required = true)
    protected String guid;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "productId")
    protected String productId;
    @XmlAttribute(name = "manufacturer")
    protected String manufacturer;
    @XmlAttribute(name = "identifier")
    protected String identifier;
    @XmlAttribute(name = "version", required = true)
    protected int version;
    @XmlAttribute(name = "product", required = true)
    protected String product;
    @XmlAttribute(name = "ibmCustomerAgreement")
    protected Boolean ibmCustomerAgreement;
    @XmlAttribute(name = "IPLA")
    protected String ipla;
    @XmlAttribute(name = "VUE")
    protected String vue;
    @XmlAttribute(name = "SS")
    protected String ss;
    @XmlAttribute(name = "softwarePricingType")
    protected String softwarePricingType;
    @XmlAttribute(name = "subCapacityLicensing")
    protected String subCapacityLicensing;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public int getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(int value) {
        this.version = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the ibmCustomerAgreement property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isIbmCustomerAgreement() {
        if (ibmCustomerAgreement == null) {
            return false;
        } else {
            return ibmCustomerAgreement;
        }
    }

    /**
     * Sets the value of the ibmCustomerAgreement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIbmCustomerAgreement(Boolean value) {
        this.ibmCustomerAgreement = value;
    }

    /**
     * Gets the value of the ipla property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIPLA() {
        return ipla;
    }

    /**
     * Sets the value of the ipla property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIPLA(String value) {
        this.ipla = value;
    }

    /**
     * Gets the value of the vue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVUE() {
        return vue;
    }

    /**
     * Sets the value of the vue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVUE(String value) {
        this.vue = value;
    }

    /**
     * Gets the value of the ss property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSS() {
        return ss;
    }

    /**
     * Sets the value of the ss property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSS(String value) {
        this.ss = value;
    }

    /**
     * Gets the value of the softwarePricingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoftwarePricingType() {
        return softwarePricingType;
    }

    /**
     * Sets the value of the softwarePricingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoftwarePricingType(String value) {
        this.softwarePricingType = value;
    }

    /**
     * Gets the value of the subCapacityLicensing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubCapacityLicensing() {
        return subCapacityLicensing;
    }

    /**
     * Sets the value of the subCapacityLicensing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubCapacityLicensing(String value) {
        this.subCapacityLicensing = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }

}
