//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 12:15:07 PM CST 
//


package com.ibm.asset.swkbt.genSchema;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibm.asset.swkbt.genSchema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibm.asset.swkbt.genSchema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SwkbType }
     * 
     */
    public SwkbType createSwkbType() {
        return new SwkbType();
    }

    /**
     * Create an instance of {@link KbIdentityType }
     * 
     */
    public KbIdentityType createKbIdentityType() {
        return new KbIdentityType();
    }

    /**
     * Create an instance of {@link SoftwareKnowledgeBase }
     * 
     */
    public SoftwareKnowledgeBase createSoftwareKnowledgeBase() {
        return new SoftwareKnowledgeBase();
    }

    /**
     * Create an instance of {@link SwkbType.Platforms }
     * 
     */
    public SwkbType.Platforms createSwkbTypePlatforms() {
        return new SwkbType.Platforms();
    }

    /**
     * Create an instance of {@link SwkbType.DefinitionSources }
     * 
     */
    public SwkbType.DefinitionSources createSwkbTypeDefinitionSources() {
        return new SwkbType.DefinitionSources();
    }

    /**
     * Create an instance of {@link SwkbType.IdentityLinks }
     * 
     */
    public SwkbType.IdentityLinks createSwkbTypeIdentityLinks() {
        return new SwkbType.IdentityLinks();
    }

    /**
     * Create an instance of {@link AdditionalStructureType }
     * 
     */
    public AdditionalStructureType createAdditionalStructureType() {
        return new AdditionalStructureType();
    }

    /**
     * Create an instance of {@link OtherSignatureType }
     * 
     */
    public OtherSignatureType createOtherSignatureType() {
        return new OtherSignatureType();
    }

    /**
     * Create an instance of {@link IdentityLinkType }
     * 
     */
    public IdentityLinkType createIdentityLinkType() {
        return new IdentityLinkType();
    }

    /**
     * Create an instance of {@link InstallRegistrySignatureType }
     * 
     */
    public InstallRegistrySignatureType createInstallRegistrySignatureType() {
        return new InstallRegistrySignatureType();
    }

    /**
     * Create an instance of {@link RegistryType }
     * 
     */
    public RegistryType createRegistryType() {
        return new RegistryType();
    }

    /**
     * Create an instance of {@link DistributedReleaseType }
     * 
     */
    public DistributedReleaseType createDistributedReleaseType() {
        return new DistributedReleaseType();
    }

    /**
     * Create an instance of {@link XslmIdSignatureType }
     * 
     */
    public XslmIdSignatureType createXslmIdSignatureType() {
        return new XslmIdSignatureType();
    }

    /**
     * Create an instance of {@link ManufacturerType }
     * 
     */
    public ManufacturerType createManufacturerType() {
        return new ManufacturerType();
    }

    /**
     * Create an instance of {@link ApplicationServerSignatureType }
     * 
     */
    public ApplicationServerSignatureType createApplicationServerSignatureType() {
        return new ApplicationServerSignatureType();
    }

    /**
     * Create an instance of {@link FileType }
     * 
     */
    public FileType createFileType() {
        return new FileType();
    }

    /**
     * Create an instance of {@link MainframeProductType }
     * 
     */
    public MainframeProductType createMainframeProductType() {
        return new MainframeProductType();
    }

    /**
     * Create an instance of {@link AliasType }
     * 
     */
    public AliasType createAliasType() {
        return new AliasType();
    }

    /**
     * Create an instance of {@link DistributedProductType }
     * 
     */
    public DistributedProductType createDistributedProductType() {
        return new DistributedProductType();
    }

    /**
     * Create an instance of {@link MainframeFeatureType }
     * 
     */
    public MainframeFeatureType createMainframeFeatureType() {
        return new MainframeFeatureType();
    }

    /**
     * Create an instance of {@link VariationType }
     * 
     */
    public VariationType createVariationType() {
        return new VariationType();
    }

    /**
     * Create an instance of {@link KbDefinitionType }
     * 
     */
    public KbDefinitionType createKbDefinitionType() {
        return new KbDefinitionType();
    }

    /**
     * Create an instance of {@link DefintionSourceType }
     * 
     */
    public DefintionSourceType createDefintionSourceType() {
        return new DefintionSourceType();
    }

    /**
     * Create an instance of {@link J2EeApplicationSignatureType }
     * 
     */
    public J2EeApplicationSignatureType createJ2EeApplicationSignatureType() {
        return new J2EeApplicationSignatureType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link RegistrySignatureType }
     * 
     */
    public RegistrySignatureType createRegistrySignatureType() {
        return new RegistrySignatureType();
    }

    /**
     * Create an instance of {@link PartNumberType }
     * 
     */
    public PartNumberType createPartNumberType() {
        return new PartNumberType();
    }

    /**
     * Create an instance of {@link RelationshipType }
     * 
     */
    public RelationshipType createRelationshipType() {
        return new RelationshipType();
    }

    /**
     * Create an instance of {@link DistributedVersionType }
     * 
     */
    public DistributedVersionType createDistributedVersionType() {
        return new DistributedVersionType();
    }

    /**
     * Create an instance of {@link FileSignatureType }
     * 
     */
    public FileSignatureType createFileSignatureType() {
        return new FileSignatureType();
    }

    /**
     * Create an instance of {@link SoftwareItemType }
     * 
     */
    public SoftwareItemType createSoftwareItemType() {
        return new SoftwareItemType();
    }

    /**
     * Create an instance of {@link MainframeVersionType }
     * 
     */
    public MainframeVersionType createMainframeVersionType() {
        return new MainframeVersionType();
    }

    /**
     * Create an instance of {@link PlatformType }
     * 
     */
    public PlatformType createPlatformType() {
        return new PlatformType();
    }

    /**
     * Create an instance of {@link FilterSignatureType }
     * 
     */
    public FilterSignatureType createFilterSignatureType() {
        return new FilterSignatureType();
    }

    /**
     * Create an instance of {@link CVersionIdType }
     * 
     */
    public CVersionIdType createCVersionIdType() {
        return new CVersionIdType();
    }

    /**
     * Create an instance of {@link KbIdentityType.Manufacturers }
     * 
     */
    public KbIdentityType.Manufacturers createKbIdentityTypeManufacturers() {
        return new KbIdentityType.Manufacturers();
    }

    /**
     * Create an instance of {@link KbIdentityType.PartNumbers }
     * 
     */
    public KbIdentityType.PartNumbers createKbIdentityTypePartNumbers() {
        return new KbIdentityType.PartNumbers();
    }

    /**
     * Create an instance of {@link KbIdentityType.SoftwareItems }
     * 
     */
    public KbIdentityType.SoftwareItems createKbIdentityTypeSoftwareItems() {
        return new KbIdentityType.SoftwareItems();
    }

    /**
     * Create an instance of {@link KbIdentityType.Relationships }
     * 
     */
    public KbIdentityType.Relationships createKbIdentityTypeRelationships() {
        return new KbIdentityType.Relationships();
    }

    /**
     * Create an instance of {@link KbIdentityType.Signatures }
     * 
     */
    public KbIdentityType.Signatures createKbIdentityTypeSignatures() {
        return new KbIdentityType.Signatures();
    }

}
