//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 12:15:07 PM CST 
//


package com.ibm.asset.swkbt.genSchema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for platformsEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="platformsEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AIX"/>
 *     &lt;enumeration value="LINUX"/>
 *     &lt;enumeration value="SUN"/>
 *     &lt;enumeration value="HPUX"/>
 *     &lt;enumeration value="UNIX"/>
 *     &lt;enumeration value="WINDOWS"/>
 *     &lt;enumeration value="I5OS"/>
 *     &lt;enumeration value="ANY"/>
 *     &lt;enumeration value="z/OS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "platformsEnum")
@XmlEnum
public enum PlatformsEnum {

    AIX("AIX"),
    LINUX("LINUX"),
    SUN("SUN"),
    HPUX("HPUX"),
    UNIX("UNIX"),
    WINDOWS("WINDOWS"),
    @XmlEnumValue("I5OS")
    I_5_OS("I5OS"),
    ANY("ANY"),
    @XmlEnumValue("z/OS")
    Z_OS("z/OS");
    private final String value;

    PlatformsEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlatformsEnum fromValue(String v) {
        for (PlatformsEnum c: PlatformsEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
