//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 12:15:07 PM CST 
//


package com.ibm.asset.swkbt.genSchema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SoftwareItemType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{}KbDefinitionType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="endOfSupport" type="{}dateTimeType" />
 *       &lt;attribute name="productId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="website" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="activationDate" type="{}dateTimeType" />
 *       &lt;attribute name="productIds" type="{}spaceDelimStringListType" />
 *       &lt;attribute name="productRole" type="{}productRoleEnumeration" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareItemType")
@XmlSeeAlso({
    DistributedReleaseType.class,
    DistributedProductType.class,
    DistributedVersionType.class
})
public class SoftwareItemType
    extends KbDefinitionType
{

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "endOfSupport")
    protected XMLGregorianCalendar endOfSupport;
    @XmlAttribute(name = "productId")
    protected String productId;
    @XmlAttribute(name = "website")
    protected String website;
    @XmlAttribute(name = "activationDate")
    protected XMLGregorianCalendar activationDate;
    @XmlAttribute(name = "productIds")
    protected String productIds;
    @XmlAttribute(name = "productRole")
    protected ProductRoleEnumeration productRole;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the endOfSupport property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndOfSupport() {
        return endOfSupport;
    }

    /**
     * Sets the value of the endOfSupport property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndOfSupport(XMLGregorianCalendar value) {
        this.endOfSupport = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the website property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebsite() {
        return website;
    }

    /**
     * Sets the value of the website property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebsite(String value) {
        this.website = value;
    }

    /**
     * Gets the value of the activationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActivationDate() {
        return activationDate;
    }

    /**
     * Sets the value of the activationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActivationDate(XMLGregorianCalendar value) {
        this.activationDate = value;
    }

    /**
     * Gets the value of the productIds property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductIds() {
        return productIds;
    }

    /**
     * Sets the value of the productIds property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductIds(String value) {
        this.productIds = value;
    }

    /**
     * Gets the value of the productRole property.
     * 
     * @return
     *     possible object is
     *     {@link ProductRoleEnumeration }
     *     
     */
    public ProductRoleEnumeration getProductRole() {
        return productRole;
    }

    /**
     * Sets the value of the productRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductRoleEnumeration }
     *     
     */
    public void setProductRole(ProductRoleEnumeration value) {
        this.productRole = value;
    }

}
