//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.20 at 12:15:07 PM CST 
//


package com.ibm.asset.swkbt.genSchema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * <p>Java class for SwkbType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SwkbType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Platforms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Platform" type="{}PlatformType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DefinitionSources" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Source" type="{}DefintionSourceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="KbIdentity" type="{}KbIdentityType" maxOccurs="unbounded"/>
 *         &lt;element name="IdentityLinks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Link" type="{}IdentityLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="creationDate" use="required" type="{}dateTimeType" />
 *       &lt;attribute name="guid" type="{}GUIDType" />
 *       &lt;attribute name="sourceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaVersion" type="{}schemaVersionType" />
 *       &lt;attribute name="contact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dataVersion" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="lastModification" type="{}dateTimeType" />
 *       &lt;attribute name="databaseInstanceId" type="{}GUIDType" />
 *       &lt;attribute name="databaseInstanceName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filterUsed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filterStartDate" type="{}dateTimeType" />
 *       &lt;attribute name="filterEndDate" type="{}dateTimeType" />
 *       &lt;attribute name="swkbtBuildNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;anyAttribute processContents='lax'/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwkbType", propOrder = {
    "platforms",
    "definitionSources",
    "kbIdentity",
    "identityLinks",
    "additional"
})
@XmlSeeAlso({
    SoftwareKnowledgeBase.class
})
public class SwkbType {

    @XmlElement(name = "Platforms", required = true)
    protected SwkbType.Platforms platforms;
    @XmlElement(name = "DefinitionSources")
    protected SwkbType.DefinitionSources definitionSources;
    @XmlElement(name = "KbIdentity", required = true)
    protected List<KbIdentityType> kbIdentity;
    @XmlElement(name = "IdentityLinks")
    protected SwkbType.IdentityLinks identityLinks;
    protected AdditionalStructureType additional;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "creationDate", required = true)
    protected XMLGregorianCalendar creationDate;
    @XmlAttribute(name = "guid")
    protected String guid;
    @XmlAttribute(name = "sourceType")
    protected String sourceType;
    @XmlAttribute(name = "schemaVersion")
    protected String schemaVersion;
    @XmlAttribute(name = "contact")
    protected String contact;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "copyright")
    protected String copyright;
    @XmlAttribute(name = "dataVersion")
    protected Long dataVersion;
    @XmlAttribute(name = "lastModification")
    protected XMLGregorianCalendar lastModification;
    @XmlAttribute(name = "databaseInstanceId")
    protected String databaseInstanceId;
    @XmlAttribute(name = "databaseInstanceName")
    protected String databaseInstanceName;
    @XmlAttribute(name = "filterUsed")
    protected String filterUsed;
    @XmlAttribute(name = "filterStartDate")
    protected XMLGregorianCalendar filterStartDate;
    @XmlAttribute(name = "filterEndDate")
    protected XMLGregorianCalendar filterEndDate;
    @XmlAttribute(name = "swkbtBuildNumber")
    protected String swkbtBuildNumber;
    @XmlAnyAttribute
    private Map<QName, String> otherAttributes = new HashMap<QName, String>();

    /**
     * Gets the value of the platforms property.
     * 
     * @return
     *     possible object is
     *     {@link SwkbType.Platforms }
     *     
     */
    public SwkbType.Platforms getPlatforms() {
        return platforms;
    }

    /**
     * Sets the value of the platforms property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwkbType.Platforms }
     *     
     */
    public void setPlatforms(SwkbType.Platforms value) {
        this.platforms = value;
    }

    /**
     * Gets the value of the definitionSources property.
     * 
     * @return
     *     possible object is
     *     {@link SwkbType.DefinitionSources }
     *     
     */
    public SwkbType.DefinitionSources getDefinitionSources() {
        return definitionSources;
    }

    /**
     * Sets the value of the definitionSources property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwkbType.DefinitionSources }
     *     
     */
    public void setDefinitionSources(SwkbType.DefinitionSources value) {
        this.definitionSources = value;
    }

    /**
     * Gets the value of the kbIdentity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kbIdentity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKbIdentity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KbIdentityType }
     * 
     * 
     */
    public List<KbIdentityType> getKbIdentity() {
        if (kbIdentity == null) {
            kbIdentity = new ArrayList<KbIdentityType>();
        }
        return this.kbIdentity;
    }

    /**
     * Gets the value of the identityLinks property.
     * 
     * @return
     *     possible object is
     *     {@link SwkbType.IdentityLinks }
     *     
     */
    public SwkbType.IdentityLinks getIdentityLinks() {
        return identityLinks;
    }

    /**
     * Sets the value of the identityLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwkbType.IdentityLinks }
     *     
     */
    public void setIdentityLinks(SwkbType.IdentityLinks value) {
        this.identityLinks = value;
    }

    /**
     * Gets the value of the additional property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalStructureType }
     *     
     */
    public AdditionalStructureType getAdditional() {
        return additional;
    }

    /**
     * Sets the value of the additional property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalStructureType }
     *     
     */
    public void setAdditional(AdditionalStructureType value) {
        this.additional = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the guid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGuid() {
        return guid;
    }

    /**
     * Sets the value of the guid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGuid(String value) {
        this.guid = value;
    }

    /**
     * Gets the value of the sourceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceType() {
        return sourceType;
    }

    /**
     * Sets the value of the sourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceType(String value) {
        this.sourceType = value;
    }

    /**
     * Gets the value of the schemaVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSchemaVersion() {
        return schemaVersion;
    }

    /**
     * Sets the value of the schemaVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSchemaVersion(String value) {
        this.schemaVersion = value;
    }

    /**
     * Gets the value of the contact property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContact() {
        return contact;
    }

    /**
     * Sets the value of the contact property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContact(String value) {
        this.contact = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the copyright property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyright() {
        return copyright;
    }

    /**
     * Sets the value of the copyright property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyright(String value) {
        this.copyright = value;
    }

    /**
     * Gets the value of the dataVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getDataVersion() {
        return dataVersion;
    }

    /**
     * Sets the value of the dataVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDataVersion(Long value) {
        this.dataVersion = value;
    }

    /**
     * Gets the value of the lastModification property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModification() {
        return lastModification;
    }

    /**
     * Sets the value of the lastModification property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModification(XMLGregorianCalendar value) {
        this.lastModification = value;
    }

    /**
     * Gets the value of the databaseInstanceId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseInstanceId() {
        return databaseInstanceId;
    }

    /**
     * Sets the value of the databaseInstanceId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseInstanceId(String value) {
        this.databaseInstanceId = value;
    }

    /**
     * Gets the value of the databaseInstanceName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatabaseInstanceName() {
        return databaseInstanceName;
    }

    /**
     * Sets the value of the databaseInstanceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatabaseInstanceName(String value) {
        this.databaseInstanceName = value;
    }

    /**
     * Gets the value of the filterUsed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilterUsed() {
        return filterUsed;
    }

    /**
     * Sets the value of the filterUsed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilterUsed(String value) {
        this.filterUsed = value;
    }

    /**
     * Gets the value of the filterStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFilterStartDate() {
        return filterStartDate;
    }

    /**
     * Sets the value of the filterStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFilterStartDate(XMLGregorianCalendar value) {
        this.filterStartDate = value;
    }

    /**
     * Gets the value of the filterEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFilterEndDate() {
        return filterEndDate;
    }

    /**
     * Sets the value of the filterEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFilterEndDate(XMLGregorianCalendar value) {
        this.filterEndDate = value;
    }

    /**
     * Gets the value of the swkbtBuildNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSwkbtBuildNumber() {
        return swkbtBuildNumber;
    }

    /**
     * Sets the value of the swkbtBuildNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSwkbtBuildNumber(String value) {
        this.swkbtBuildNumber = value;
    }

    /**
     * Gets a map that contains attributes that aren't bound to any typed property on this class.
     * 
     * <p>
     * the map is keyed by the name of the attribute and 
     * the value is the string value of the attribute.
     * 
     * the map returned by this method is live, and you can add new attribute
     * by updating the map directly. Because of this design, there's no setter.
     * 
     * 
     * @return
     *     always non-null
     */
    public Map<QName, String> getOtherAttributes() {
        return otherAttributes;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Source" type="{}DefintionSourceType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "source"
    })
    public static class DefinitionSources {

        @XmlElement(name = "Source")
        protected List<DefintionSourceType> source;

        /**
         * Gets the value of the source property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the source property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSource().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DefintionSourceType }
         * 
         * 
         */
        public List<DefintionSourceType> getSource() {
            if (source == null) {
                source = new ArrayList<DefintionSourceType>();
            }
            return this.source;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Link" type="{}IdentityLinkType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "link"
    })
    public static class IdentityLinks {

        @XmlElement(name = "Link")
        protected List<IdentityLinkType> link;

        /**
         * Gets the value of the link property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the link property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLink().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IdentityLinkType }
         * 
         * 
         */
        public List<IdentityLinkType> getLink() {
            if (link == null) {
                link = new ArrayList<IdentityLinkType>();
            }
            return this.link;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Platform" type="{}PlatformType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "platform"
    })
    public static class Platforms {

        @XmlElement(name = "Platform", required = true)
        protected List<PlatformType> platform;

        /**
         * Gets the value of the platform property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the platform property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPlatform().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PlatformType }
         * 
         * 
         */
        public List<PlatformType> getPlatform() {
            if (platform == null) {
                platform = new ArrayList<PlatformType>();
            }
            return this.platform;
        }

    }

}
