SELECT
A.PRIMBILL AS "Customer Number",
B.CNDBACCT AS "Account",
A.PRIMNAME AS "Customer Name",
A.CMRCITY AS "City",
B.CUSTTYPE AS "Account Type",
B.INDUSTRY AS "Industry",
B.SECTOR AS "Sector",
B.CNDBDPE AS "DPE",
A.MACHTYPE AS "Type",
A.MODEL AS "Model",
A.SERIAL AS "Serial",
A.MFGSER AS "MFG Serial",
A.OTHMACH AS "Other Machine Type",
A.OEMSER AS "OEM Serial",
A.ICCBILL AS "Lease CN",
A.MAINCUST AS "Maint CN",
A.UCUSTOMR AS "Maint USING CN",
A.SAPCUST AS "Depreciation CN",
A.LPID AS "LPID",
A.SAPLPID AS "Depreciation LPID",
A.LEASSTRT AS "Lease Start",
A.LEASEND AS "Lease End",
A.LEASTERM AS "Lease Term",
A.TRANSTYP AS "Transaction Type",
A.LEASETYP AS "Lease Type",
A.LEASEAMT AS "Monthly Lease",
A.CURRMMC AS "Monthly IBM Maint",
A.STATUS AS "Maintenance Status",
A.COVERAGE AS "IBM Coverage Level",
A.WUPGINDC AS "Warranty Coverage Level",
A.WARREND AS "Warranty End Date",
A.ORDERNO AS "Maintenance Contract .",
A.CMDEPR AS "Order Number",
A.DEPREND AS "Monthly Depreciation",
A.NBV AS "Depreciation End",
A.EMPNAMEL AS "Net Book Value",
A.EMPNAMEF AS "Owner Last",
A.ONPCF AS "Owner First",
A.INVENTRY AS "ON PCF",
A.SCANDATE AS "ON SAP",
A.SCANCITY AS "Inventoriable",
A.SCANBLDG AS "Scan Date",
A.SCANFLR AS "Scan City",
A.SCANRM AS "Scan Bldg",
A.SCANGRID AS "Scan Floor",
A.ASSETTAG AS "Scan Room",
A.DEFN AS "Scan Grid",
A.HWSTATUS AS "Asset Tag",
A.ONSAP AS "Defn",
A.WARRCOVG AS "Compliance Mgmt Status",
A.MAINTNUM AS "Amount Financed",
A.AMTFIN AS "Total Payment",
A.TOTALPAY AS "Future Year 1",
A.FUTYR1 AS "Future Year 2",
A.FUTYR2 AS "Future Year 3",
A.FUTYR3 AS "Future Year 4",
A.FUTYR4 AS "Financial Source",
A.FINSORC AS "Capital Release",
A.CAPNUM AS "Capdate",
A.CAPDATE AS "GAV",
A.GAV AS "On Chis",
A.ONCHIS AS "Chis Indicator",
A.CHISINDC AS "Warranty Upgrade Indicator",
A.BASEIND AS "Base Asset Indicator",
B.CMRST AS "State",
A.INSTADD3 AS "Installed Address 3",
A.PCFCUST AS "PCF Customer",
A.OCUSTOMR AS "Owning Customer",
A.TYPE AS "Asset Type",
C.LPAR AS "Hostname(s)"
FROM ATPPROD.MASTER A, ATPPROD.CUSTOMER B, ATPPROD.LPAR C
WHERE A.PRIMBILL=B.CUSTOMER
  AND B.CNDBACCT IN ('17320','31840','39800','39810','39820','39830','72370','72330','73240','72350','83830','96500')
  AND A.TYPE <> 'CUSTO'
  AND A.MACHTYPE=C.MACHTYPE
  AND A.SERIAL=C.SERIAL
  AND C.ISOCNTRY='US'
ORDER BY A.PRIMBILL,A.MACHTYPE,A.SERIAL,C.LPAR;
