INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (1, 'Customer owned, Customer managed', 'CUSTOCUSTM');
INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (2, 'Customer owned, IBM managed', 'CUSTOIBMM');
INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (3, 'IBM owned, IBM managed', 'IBMOIBMM');
INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (4, 'IBM owned, managed by 3rd party', 'IBMO3RDM');
INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (5, 'Customer owned, managed by 3rd party', 'CUSTO3RDM');
INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (6, 'IBM owned, IBM managed SW consumption based', 'IBMOIBMMSWCO');
INSERT INTO EAADMIN.SCOPE (ID, DESCRIPTION, NAME) VALUES (7, 'Customer owned, IBM managed SW consumption based', 'CUSTOIBMMSWCO');