--story 42595 by Abner
INSERT INTO EAADMIN.MANUFACTURER 
         (ID, DID, NAME, WEBSITE)
  VALUES (126, null, 'ADOBE', 'http://www.barronmccann.com'); 
INSERT INTO EAADMIN.MANUFACTURER 
         (ID, DID, NAME, WEBSITE)
  VALUES (3539, null, 'IBM', ' http://www.ibm.com'); 
INSERT INTO EAADMIN.MANUFACTURER 
         (ID, DID, NAME, WEBSITE)
  VALUES (609, null, 'CI SOLUTIONS',null); 
INSERT INTO EAADMIN.MANUFACTURER 
         (ID, DID, NAME, WEBSITE)
  VALUES (2161, NULL ,'PASSLOGIX',NULL);       
  