INSERT INTO EAADMIN.SOFTWARE_CATEGORY
(SOFTWARE_CATEGORY_ID,SOFTWARE_CATEGORY_NAME,CHANGE_JUSTIFICATION, COMMENTS ,REMOTE_USER, RECORD_TIME , STATUS)
VALUES(1000,'UNKNOWN','DEFAULT JUSTIFICATION','UNKNOWN','Container','LOADER','2004-06-30 23:59:59','ACTIVE');

