--story 42595 by Abner
INSERT INTO EAADMIN.SOFTWARE_ITEM 
           (ID, NAME, END_OF_SUPPORT, PRODUCT_ID, WEBSITE, ACTIVATION_DATE, PRODUCT_ROLE, SUB_CAPACITY_LICENSING, IPLA) 
    VALUES (999265, 'IBM AIX', null, null, null, '2009-10-04 16:00:00', 'SOFTWARE_PRODUCT', 0, null);
