INSERT INTO EAADMIN.SOURCE (ID, DESCRIPTION) VALUES (1, 'C&N contract reading');
INSERT INTO EAADMIN.SOURCE (ID, DESCRIPTION) VALUES (2, 'Contract language');
INSERT INTO EAADMIN.SOURCE (ID, DESCRIPTION) VALUES (3, 'Contract schedule');
INSERT INTO EAADMIN.SOURCE (ID, DESCRIPTION) VALUES (4, 'PE note');