INSERT INTO EAADMIN.HARDWARE_LPAR
(CUSTOMER_ID,HARDWARE_ID,ID,NAME,REMOTE_USER,RECORD_TIME,STATUS,EXT_ID,TECH_IMAGE_ID,SERVER_TYPE,PART_MIPS,PART_MSU,LPAR_STATUS,SPLA,SYSPLEX,INTERNET_ICC_FLAG,PART_GARTNER_MIPS,BACKUPMETHOD,CLUSTER_TYPE,VIRTUAL_MOBILITY_RESTRICTION,CAPPED_LPAR,VIRTUAL_FLAG,EFFECTIVE_THREADS,OS_TYPE,VCPU)
VALUES
(2541,569389,534941,'ZHYSZ','ATP',TIMESTAMP '2015-10-15 23:59:59', 'ACTIVE',null,null,'PRODUCTION',0,0,'ACTIVE',null,null,null,0.000,null,null,null,null,null,0.000,null,0.000)
;