INSERT INTO EAADMIN.HARDWARE
(MACHINE_TYPE_ID,SERIAL,COUNTRY,ID,OWNER,CUSTOMER_NUMBER,REMOTE_USER,RECORD_TIME,STATUS,HARDWARE_STATUS,ACCOUNT_NUMBER,CUSTOMER_ID BIGINT,MODEL,PROCESSOR_COUNT,CLASSIFICATION, CHIPS,PROCESSOR_TYPE,SERVER_TYPE,CPU_MIPS,CPU_MSU,MAST_PROCESSOR_TYPE,PROCESSOR_MANUFACTURER,PROCESSOR_MODEL,NBR_CORES_PER_CHIP,NBR_OF_CHIPS_MAX,SHARED,CPU_GARTNER_MIPS,SHARED_PROCESSOR,CLOUD_NAME,CHASSIS_ID,CPU_IFL)
VALUES
(312,'0ZHYSZ','US',569389,'CUSTO','35400XX','ATP',TIMESTAMP '2015-09-07 23:59:59','ACTIVE','ACTIVE','35400',2541,'mZHSE',4,'OEM SERVER',0,null,'PRODUCTION',0,0,null,null,null,0.00,0.00,'N',0.00,null,null,null,1);

 