--story 42595 by Abner
INSERT INTO EAADMIN.SCHEDULE_F 
(ID, CUSTOMER_ID, SOFTWARE_ID, SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID, SOURCE_LOCATION, STATUS_ID, BUSINESS_JUSTIFICATION, REMOTE_USER, RECORD_TIME, LEVEL, HW_OWNER, SERIAL, MACHINE_TYPE, HOSTNAME, SW_FINANCIAL_RESP, MANUFACTURER_NAME) 
VALUES 
(1, 2541, 999265, 'IBM AIX', 'IBM AIX', 'IBM', 1, 1, 'GDF-AP-ART-01', 2, 'df', 'dllhao@cn.ibm.com', '2015-05-12 02:22:21', 'PRODUCT', null, null, null, null, 'IBM', null);
INSERT INTO EAADMIN.SCHEDULE_F 
(ID, CUSTOMER_ID, SOFTWARE_ID, SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID, SOURCE_LOCATION, STATUS_ID, BUSINESS_JUSTIFICATION, REMOTE_USER, RECORD_TIME, LEVEL, HW_OWNER, SERIAL, MACHINE_TYPE, HOSTNAME, SW_FINANCIAL_RESP, MANUFACTURER_NAME) 
VALUES 
(2, 2541, 218119, 'MICROSOFT SQL SERVER 2000 CAL', 'MICROSOFT SQL SERVER 2000 CAL', 'MICROSOFT', 3, 3, 'Dalian',    2, 'TEST', 'dllhao@cn.ibm.com', '2015-1-28 23:59:59','PRODUCT', null, null, null, null, 'IBM', null);
INSERT INTO EAADMIN.SCHEDULE_F 
(ID, CUSTOMER_ID, SOFTWARE_ID, SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID, SOURCE_LOCATION, STATUS_ID, BUSINESS_JUSTIFICATION, REMOTE_USER, RECORD_TIME, LEVEL, HW_OWNER, SERIAL, MACHINE_TYPE, HOSTNAME, SW_FINANCIAL_RESP, MANUFACTURER_NAME) 
VALUES 
(3, 2541, 218097, 'IBM Lotus Notes','IBM Lotus Notes','IBM', 3, 4, 'AMCB-SLM-16206-03',2,'This is for test','zhysz@cn.ibm.com','2015-4-5 23:59:59','HWOWNER','IBM',NULL,NULL,NULL,'IBM','IBM');
INSERT INTO EAADMIN.SCHEDULE_F 
(ID, CUSTOMER_ID, SOFTWARE_ID, SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID, SOURCE_LOCATION, STATUS_ID, BUSINESS_JUSTIFICATION, REMOTE_USER, RECORD_TIME, LEVEL, HW_OWNER, SERIAL, MACHINE_TYPE, HOSTNAME, SW_FINANCIAL_RESP, MANUFACTURER_NAME) 
VALUES 
(4, 2541,NULL,NULL,NULL,'CI SOLUTIONS', 3, 4, 'JMCB-SLM-10197-03',2,'This is for Manufacturer Level','zhysz@cn.ibm.com','2015-4-13 20:59:59','MANUFACTURER',NULL,NULL,NULL,NULL,'IBM','CI SOLUTIONS');
