CREATE SCHEMA eaadmin;

CREATE TABLE eaadmin.software (
  MANUFACTURER_ID		BIGINT NOT NULL,
  SOFTWARE_CATEGORY_ID	BIGINT NOT NULL,
  SOFTWARE_ID			BIGINT NOT NULL,
  SOFTWARE_NAME			VARCHAR(581),
  VERSION				VARCHAR(64),
  PRIORITY				INTEGER NOT NULL,
  LEVEL					VARCHAR(13) NOT NULL,
  TYPE					VARCHAR(1) NOT NULL,
  CHANGE_JUSTIFICATION	VARCHAR(5) NOT NULL,
  COMMENTS				VARCHAR(17) NOT NULL,
  REMOTE_USER			VARCHAR(32) NOT NULL,
  RECORD_TIME			TIMESTAMP,
  STATUS				VARCHAR(8) NOT NULL,
  VENDOR_MANAGED		INTEGER NOT NULL,
  PRODUCT_ROLE			VARCHAR(255),
  PID					VARCHAR(32),
);

CREATE TABLE eaadmin.software_item (
  ID					BIGINT NOT NULL,
  NAME					VARCHAR(255),
  END_OF_SUPPORT		TIMESTAMP(6),
  PRODUCT_ID			VARCHAR(255),
  WEBSITE				VARCHAR(1000),
  ACTIVATION_DATE		TIMESTAMP(6),
  PRODUCT_ROLE			VARCHAR(255),
  SUB_CAPACITY_LICENSING	SMALLINT,
  IPLA					VARCHAR(255),
);

CREATE TABLE eaadmin.product (
  ID					BIGINT NOT NULL,
  MANUFACTURER_ID		BIGINT NOT NULL,
  FUNCTION				VARCHAR(255),
  PVU					SMALLINT,
  LICENSE_TYPE			SMALLINT,
);

CREATE TABLE eaadmin.product_info (
  ID					BIGINT NOT NULL,
  SOFTWARE_CATEGORY_ID	BIGINT NOT NULL,
  PRIORITY				INTEGER NOT NULL,
  LICENSABLE			SMALLINT NOT NULL,
  CHANGE_JUSTIFICATION	VARCHAR(5) NOT NULL,
  COMMENTS				VARCHAR(17),
  REMOTE_USER			VARCHAR(32) NOT NULL,
  RECORD_TIME			TIMESTAMP NOT NULL,
  STATUS				VARCHAR(8) NOT NULL,
);

CREATE TABLE eaadmin.manufacturer (
  ID					BIGINT NOT NULL,
  DID					VARCHAR(255),
  NAME					VARCHAR(255) NOT NULL,
  WEBSITE				VARCHAR(1000),
);

CREATE TABLE eaadmin.kb_definition (
  ID					BIGINT NOT NULL,
  ACTIVE				SMALLINT,
  CREATION_TIME			TIMESTAMP NOT NULL,
  CUSTOM_1				VARCHAR(255),
  CUSTOM_2				VARCHAR(255),
  CUSTOM_3				VARCHAR(255),
  DATA_INPUT			SMALLINT,
  DEFINITION_SOURCE		VARCHAR(255),
  DELETED				SMALLINT,
  DESCRIPTION			VARCHAR(1000),
  EXTERNAL_ID			VARCHAR(255),
  GUID					VARCHAR(255),
  MODIFICATION_TIME		TIMESTAMP,
);

CREATE TABLE eaadmin.product_alias (
  PRODUCT_ID			BIGINT NOT NULL,
  ALIAS_ID				BIGINT NOT NULL,
);

CREATE TABLE eaadmin.alias (
  ID					BIGINT NOT NULL,
  NAME					VARCHAR(255) NOT NULL,
  PREFERRED				SMALLINT NOT NULL,
);

CREATE TABLE eaadmin.customer (
  CUSTOMER_ID				BIGINT NOT NULL,
  CUSTOMER_TYPE_ID			BIGINT NOT NULL,             
  POD_ID					BIGINT NOT NULL,
  INDUSTRY_ID				BIGINT NOT NULL,
  ACCOUNT_NUMBER			BIGINT NOT NULL,
  CUSTOMER_NAME				VARCHAR(64),
  CONTACT_DPE_ID			BIGINT,
  CONTACT_FA_ID				BIGINT,
  CONTACT_HW_ID				BIGINT,
  CONTACT_SW_ID				BIGINT,
  CONTACT_FOCAL_ASSET_ID	BIGINT,
  CONTACT_TRANSITION_ID		BIGINT, 
  ASSET_TOOLS_BILLING_CODE	VARCHAR(64),
  STATUS					VARCHAR(32), 
  HW_INTERLOCK				VARCHAR(3),
  SW_INTERLOCK				VARCHAR(3), 
  INV_INTERLOCK				VARCHAR(3),
  SW_LICENSE_MGMT			VARCHAR(3),
  SW_SUPPORT				VARCHAR(3),
  HW_SUPPORT				VARCHAR(3), 
  TRANSITION_STATUS			VARCHAR(16),
  TRANSITION_EXIT_DATE		DATE,
  COUNTRY_CODE_ID			BIGINT, 
  SCAN_VALIDITY				INTEGER,
  SW_TRACKING				VARCHAR(3),
  SW_COMPLIANCE_MGMT		VARCHAR(3), 
  SW_FINANCIAL_RESPONSIBILITY		VARCHAR(16), 
  SW_FINANCIAL_MGMT			VARCHAR(3),
  CREATION_DATE_TIME		TIMESTAMP NOT NULL,
  UPDATE_DATE_TIME			TIMESTAMP NOT NULL,
  CONTRACT_SIGN_DATE		DATE,
  TME_OBJECT_ID				VARCHAR(255),              
);

CREATE TABLE eaadmin.schedule_f (
  ID						BIGINT NOT NULL,
  CUSTOMER_ID				BIGINT NOT NULL,
  SOFTWARE_ID				BIGINT NOT NULL, 
  SOFTWARE_TITLE			VARCHAR(256) NOT NULL,
  SOFTWARE_NAME				VARCHAR(128) NOT NULL,
  MANUFACTURER				VARCHAR(64) NOT NULL,
  SCOPE_ID					BIGINT NOT NULL,
  SOURCE_ID					BIGINT NOT NULL,
  SOURCE_LOCATION			VARCHAR(128) NOT NULL,
  STATUS_ID					BIGINT NOT NULL,
  BUSINESS_JUSTIFICATION	VARCHAR(256) NOT NULL,
  REMOTE_USER				VARCHAR(32) NOT NULL,
  RECORD_TIME				TIMESTAMP NOT NULL,
  LEVEL						VARCHAR(16),
  HW_OWNER					VARCHAR(64),
  SERIAL					VARCHAR(32),
  MACHINE_TYPE				VARCHAR(8),
  HOSTNAME					VARCHAR(255),
  SW_FINANCIAL_RESP			VARCHAR(16),            
);

CREATE TABLE eaadmin.scope (
  ID					BIGINT NOT NULL, 
  DESCRIPTION			VARCHAR(64) NOT NULL,
  NAME					VARCHAR(16) NOT NULL,
);

CREATE TABLE eaadmin.source (
  ID					BIGINT NOT NULL, 
  DESCRIPTION			VARCHAR(64) NOT NULL,
);

CREATE TABLE eaadmin.status (
  ID					BIGINT NOT NULL, 
  DESCRIPTION			VARCHAR(64) NOT NULL,
);

CREATE TABLE eaadmin.non_instance (
  ID					BIGINT NOT NULL,
  SOFTWARE_ID			BIGINT,
  MANUFACTURER_ID		BIGINT,
  RESTRICTION			VARCHAR(8),
  CAPACITY_TYPE_CODE	SMALLINT,
  BASE_ONLY				SMALLINT,
  STATUS_ID				BIGINT,
  REMOTE_USER			VARCHAR(32),
  RECORD_TIME			TIMESTAMP,
);