
--Insert MF_HOSTNAME - tap2 executed (589 created) - lex executed
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID, mf.id, sf.SOFTWARE_TITLE, sw.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 			join eaadmin.software sw on mf.id = sw.software_id 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mf.id 						and sl.name=sf.hostname 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='HOSTNAME' and sf.status_id=2 with ur ; 

--Insert MV_HOSTNAME - tap2 executed (no rows added) - lex executed(no rows)
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID,mv.id, sf.SOFTWARE_TITLE, sw.SOFTWARE_NAME, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.software sw on sw.software_id=mv.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id    				 where  					    iT.mainframe_feature_id=mv.id 						and sl.name=sf.hostname 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='HOSTNAME' and sf.status_id=2 with ur ; 

--Insert MF_HWBOX - tap2 executed (no rows added) - lex executed(no rows)
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID,mf.id, sf.SOFTWARE_TITLE, sw.SOFTWARE_NAME, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 			join eaadmin.software sw on sw.software_id=mf.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.hw_sw_composite hsc on hsc.software_lpar_id=is.software_lpar_id 						 join eaadmin.hardware_lpar hl on hsc.hardware_lpar_id = hl.id 						 join eaadmin.hardware h on hl.hardware_id = h.id 						 join eaadmin.machine_type mt on h.machine_type_id = mt.id 				 where  					    iT.mainframe_feature_id=mf.id 						and h.serial=sf.serial 						and mt.name = sf.machine_type 						and sf.customer_id=hl.customer_id				 			   )	 and sf.level='HWBOX' and sf.status_id=2 with ur ; 

--Insert MV_HWBOX - tap2 executed (no rows added) - lex executed(no rows) 
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID,mv.id, sf.SOFTWARE_TITLE, sw.SOFTWARE_NAME, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.software sw on sw.software_id=mv.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.hw_sw_composite hsc on hsc.software_lpar_id=is.software_lpar_id 						 join eaadmin.hardware_lpar hl on hsc.hardware_lpar_id = hl.id 						 join eaadmin.hardware h on hl.hardware_id = h.id 						 join eaadmin.machine_type mt on h.machine_type_id = mt.id 				 where  					    iT.mainframe_feature_id=mv.id 						and h.serial=sf.serial 						and mt.name = sf.machine_type 						and sf.customer_id=hl.customer_id				 			   )	 and sf.level='HWBOX' and sf.status_id=2 with ur ; 

--Insert MF_PRODUCT part 1 - tap2 executed - lex executed
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID, mf.id, sf.SOFTWARE_TITLE, sw.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 			join eaadmin.software sw on mf.id = sw.software_id 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mf.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 and sf.id < 602543 with ur ; 

--Insert MF_PRODUCT part 2 - tap2 executed (part 1 + 2 added 15160 rows) - lex executed
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID, mf.id, sf.SOFTWARE_TITLE, sw.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 			join eaadmin.software sw on mf.id = sw.software_id 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mf.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 and sf.id >= 602543 with ur ; 

--Insert MV_PRODUCT - tap2 executed (added 591 rows) - lex executed
insert into schedule_f (CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select sf.CUSTOMER_ID,mv.id, sf.SOFTWARE_TITLE, sw.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.software sw on mv.id = sw.software_id 	where 		exists ( select 1  						 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id						  					where  					    iT.mainframe_feature_id=mv.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 with ur ; 


--Add MF_HOSTNAME to history - tap2 executed (214 created) - lex executed
insert into eaadmin.schedule_f_h (SCHEDULE_F_ID, CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select distinct sf.id,sf.CUSTOMER_ID, sf.id, sf.SOFTWARE_TITLE, sf.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID, sf.BUSINESS_JUSTIFICATION, sf.REMOTE_USER,sf.RECORD_TIME, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id  	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mf.id 						and sl.name=sf.hostname 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='HOSTNAME' and sf.status_id=2 with ur ; 
--Set MF_HOSTNAME to inactivate - tap2 executed (214 updated) - lex executed
update eaadmin.schedule_f sf  set sf.status_id=1,sf.BUSINESS_JUSTIFICATION='This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.',sf.REMOTE_USER='ondrej_zivnustka@cz.ibm.com',sf.RECORD_TIME=current TIMESTAMP 	where 		exists ( select 1  				 	from eaadmin.software_item si 						join eaadmin.mainframe_version mv on mv.product_id=si.id 						join eaadmin.mainframe_feature mf on mf.version_id=mv.id 						join eaadmin.installed_TADZ iT  on iT.mainframe_feature_id=mf.id   						join eaadmin.installed_software is on is.id=iT.installed_software_id 						join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where   				        sl.name=sf.hostname 						and sf.customer_id=sl.customer_id 						and si.name=sf.software_name 									 			   )	 and sf.level='HOSTNAME' and sf.status_id=2 with ur ; 

--Add MV_HOSTNAME to history
insert into eaadmin.schedule_f_h (SCHEDULE_F_ID,CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select distinct sf.id,sf.CUSTOMER_ID, sf.id, sf.SOFTWARE_TITLE, sf.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID, sf.BUSINESS_JUSTIFICATION, sf.REMOTE_USER,sf.RECORD_TIME, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id    				 where  					    iT.mainframe_feature_id=mv.id 						and sl.name=sf.hostname 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='HOSTNAME' and sf.status_id=2 with ur ; 
--Set MV_HOSTNAME to inactive
update eaadmin.schedule_f  set sf.status_id=1,sf.BUSINESS_JUSTIFICATION='This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.',sf.REMOTE_USER='ondrej_zivnustka@cz.ibm.com',sf.RECORD_TIME=current TIMESTAMP  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 	where 		exists ( select 1  				 	from eaadmin.software_item si 						join eaadmin.mainframe_version mv on mv.product_id=si.id 						join eaadmin.installed_TADZ iT  on iT.mainframe_feature_id=mv.id   						join eaadmin.installed_software is on is.id=iT.installed_software_id 						join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where   				        sl.name=sf.hostname 						and sf.customer_id=sl.customer_id 						and si.name=sf.software_name 									 			   )	 and sf.level='HOSTNAME' and sf.status_id=2 with ur ; 

--Add MF_HWBOX to history
insert into eaadmin.schedule_f_h (SCHEDULE_F_ID, CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select distinct sf.id, sf.CUSTOMER_ID,mf.id, sf.SOFTWARE_TITLE, sf.SOFTWARE_NAME, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID, sf.BUSINESS_JUSTIFICATION, sf.REMOTE_USER,sf.RECORD_TIME, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.hw_sw_composite hsc on hsc.software_lpar_id=is.software_lpar_id 						 join eaadmin.hardware_lpar hl on hsc.hardware_lpar_id = hl.id 						 join eaadmin.hardware h on hl.hardware_id = h.id 						 join eaadmin.machine_type mt on h.machine_type_id = mt.id 				 where  					    iT.mainframe_feature_id=mf.id 						and h.serial=sf.serial 						and mt.name = sf.machine_type 						and sf.customer_id=hl.customer_id				 			   )	 and sf.level='HWBOX' and sf.status_id=2 with ur ; 
--Set MF_HWBOX to inactive
update eaadmin.schedule_f  set sf.status_id=1,sf.BUSINESS_JUSTIFICATION='This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.',sf.REMOTE_USER='ondrej_zivnustka@cz.ibm.com',sf.RECORD_TIME=current TIMESTAMP  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.hw_sw_composite hsc on hsc.software_lpar_id=is.software_lpar_id 						 join eaadmin.hardware_lpar hl on hsc.hardware_lpar_id = hl.id 						 join eaadmin.hardware h on hl.hardware_id = h.id 						 join eaadmin.machine_type mt on h.machine_type_id = mt.id 				 where  					    iT.mainframe_feature_id=mf.id 						and h.serial=sf.serial 						and mt.name = sf.machine_type 						and sf.customer_id=hl.customer_id				 			   )	 and sf.level='HWBOX' and sf.status_id=2 with ur ; 

--Add MV_HWBOX to history
insert into eaadmin.schedule_f_h (SCHEDULE_F_ID, CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select distinct sf.id, sf.CUSTOMER_ID,mv.id, sf.SOFTWARE_TITLE, sf.SOFTWARE_NAME, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID,'This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.', 'ondrej_zivnustka@cz.ibm.com',current TIMESTAMP, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.hw_sw_composite hsc on hsc.software_lpar_id=is.software_lpar_id 						 join eaadmin.hardware_lpar hl on hsc.hardware_lpar_id = hl.id 						 join eaadmin.hardware h on hl.hardware_id = h.id 						 join eaadmin.machine_type mt on h.machine_type_id = mt.id 				 where  					    iT.mainframe_feature_id=mv.id 						and h.serial=sf.serial 						and mt.name = sf.machine_type 						and sf.customer_id=hl.customer_id				 			   )	 and sf.level='HWBOX' and sf.status_id=2 with ur ;
--Add MV_HWBOX to inactive
update eaadmin.schedule_f  set sf.status_id=1  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 	 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.hw_sw_composite hsc on hsc.software_lpar_id=is.software_lpar_id 						 join eaadmin.hardware_lpar hl on hsc.hardware_lpar_id = hl.id 						 join eaadmin.hardware h on hl.hardware_id = h.id 						 join eaadmin.machine_type mt on h.machine_type_id = mt.id 				 where  					    iT.mainframe_feature_id=mv.id 						and h.serial=sf.serial 						and mt.name = sf.machine_type 						and sf.customer_id=hl.customer_id				 			   )	 and sf.level='HWBOX' and sf.status_id=2 with ur ;

--Add MF_PRODUCT to history - tap2 executed - lex executed
insert into eaadmin.schedule_f_h (SCHEDULE_F_ID, CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select distinct sf.id, sf.CUSTOMER_ID, sf.id, sf.SOFTWARE_TITLE, sf.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID, sf.BUSINESS_JUSTIFICATION, sf.REMOTE_USER, sf.RECORD_TIME, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 			join eaadmin.mainframe_feature mf on mf.version_id=mv.id 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mf.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 with ur ;
--Add MF_PRODUCT to inactive - tap2 executed - lex executed
update eaadmin.schedule_f sf  set sf.status_id=1,sf.BUSINESS_JUSTIFICATION='This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.',sf.REMOTE_USER='ondrej_zivnustka@cz.ibm.com',sf.RECORD_TIME=current TIMESTAMP  	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT 						 join eaadmin.software_item si on si.name=sf.software_name 						 join eaadmin.mainframe_version mv on mv.product_id=si.id 						 join eaadmin.mainframe_feature mf on mf.version_id=mv.id   						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mf.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 with ur ; 

--Add MV_PRODUCT to history - tap2 executed - lex executed
insert into eaadmin.schedule_f_h (SCHEDULE_F_ID, CUSTOMER_ID, SOFTWARE_ID,SOFTWARE_TITLE, SOFTWARE_NAME, MANUFACTURER, SCOPE_ID, SOURCE_ID,SOURCE_LOCATION, STATUS_ID,BUSINESS_JUSTIFICATION, REMOTE_USER,RECORD_TIME, LEVEL, HW_OWNER, SERIAL,MACHINE_TYPE, HOSTNAME)  select distinct sf.id, sf.CUSTOMER_ID, sf.id, sf.SOFTWARE_TITLE, sf.software_name, sf.MANUFACTURER, sf.SCOPE_ID, sf.SOURCE_ID, sf.SOURCE_LOCATION, sf.STATUS_ID, sf.BUSINESS_JUSTIFICATION, sf.REMOTE_USER, sf.RECORD_TIME, sf.LEVEL, sf.HW_OWNER, sf.SERIAL,sf.MACHINE_TYPE, sf.HOSTNAME  	from eaadmin.schedule_f sf 			join eaadmin.software_item si on si.name=sf.software_name 			join eaadmin.mainframe_version mv on mv.product_id=si.id 	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT     						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mv.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 with ur ; 
--Add MV_PRODUCT to inactive - tap2 executed - lex executed
update eaadmin.schedule_f sf  set sf.status_id=1,sf.BUSINESS_JUSTIFICATION='This migration is indicated in Business Justification field as "SCHEDULE F MIGRATION FOR TADZ FEATURES IN TRAILS AMCB-SLM-21455" for each record in scope of this migration.',sf.REMOTE_USER='ondrej_zivnustka@cz.ibm.com',sf.RECORD_TIME=current TIMESTAMP  	where 		exists ( select 1  				 from eaadmin.installed_TADZ iT 						 join eaadmin.software_item si on si.name=sf.software_name 						 join eaadmin.mainframe_version mv on mv.product_id=si.id  						 join eaadmin.installed_software is on is.id=iT.installed_software_id 						 join eaadmin.software_lpar sl on sl.id=is.software_lpar_id 				 where  					    iT.mainframe_feature_id=mv.id 						and sf.customer_id=sl.customer_id				 			   )	 and sf.level='PRODUCT' and sf.status_id=2 with ur ; 


--Add installed_software to recon queue - lex executed
insert into eaadmin.recon_installed_sw ( CUSTOMER_ID, INSTALLED_SOFTWARE_ID, ACTION, REMOTE_USER, RECORD_TIME  )  select distinct sl.customer_id,is.id,'UPDATE','ondrej_zivnustka@cz.ibm.com',current timestamp  from eaadmin.installed_TADZ iT 		join eaadmin.installed_software is  on iT.installed_software_id=is.id	  		join eaadmin.alert_unlicensed_sw aus on aus.installed_software_id=is.id 		join eaadmin.software_lpar sl on is.software_lpar_id=sl.id 		 		 where aus.open=1 with ur ; 
