//
// This file was generated by the JavaTM Architecture for 
// See <a href="http://java.sun.com/
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 11:19:21 AM EDT 
//

package com.ibm.asset.trails.domain;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Table;

import com.ibm.asset.swkbt.schema.RegistrySourceEnum;

@Entity
@Table(name = "INSTALL_REGISTRY_SIGNATURE")
public class InstallRegistrySignature extends Signature {

	private static final long serialVersionUID = 2868770245572077532L;

	@Basic
	@Column(name = "DATA")
	protected String data;

	@Basic
	@Column(name = "KEY")
	protected String key;

	@Basic
	@Column(name = "SOURCE")
	@Enumerated(EnumType.STRING)
	protected RegistrySourceEnum source;

	public String getData() {
		return data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public RegistrySourceEnum getSource() {
		return source;
	}

	public void setSource(RegistrySourceEnum source) {
		this.source = source;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((data == null) ? 0 : data.hashCode());
		result = prime * result + ((key == null) ? 0 : key.hashCode());
		result = prime * result + ((source == null) ? 0 : source.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (!super.equals(obj)) {
			return false;
		}
		if (!(obj instanceof InstallRegistrySignature)) {
			return false;
		}
		InstallRegistrySignature other = (InstallRegistrySignature) obj;
		if (data == null) {
			if (other.data != null) {
				return false;
			}
		} else if (!data.equals(other.data)) {
			return false;
		}
		if (key == null) {
			if (other.key != null) {
				return false;
			}
		} else if (!key.equals(other.key)) {
			return false;
		}
		if (source != other.source) {
			return false;
		}
		return super.equals(obj);
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("InstallRegistrySignature [data=");
		builder.append(data);
		builder.append(", key=");
		builder.append(key);
		builder.append(", source=");
		builder.append(source);
		builder.append("]");
		return builder.toString();
	}

}
