//
// This file was generated by the JavaTM Architecture for 
// See <a href="http://java.sun.com/
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.28 at 11:19:21 AM EDT 
//

package com.ibm.asset.trails.domain;

import javax.persistence.Basic;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import com.ibm.asset.swkbt.schema.PlatformsEnum;

@Entity
@Table(name = "PLATFORM")
@Cacheable
public class Platform extends DomainEntity {
	private static final long serialVersionUID = 8352388500720958782L;

	@Id
	@Column(name = "ID")
	@GeneratedValue(strategy = GenerationType.AUTO)
	protected Long id;

	@Basic
	@Column(name = "SWKBT_ID")
	protected int swkbtId;

	@Basic
	@Column(name = "NAME", length = 255)
	@Enumerated(EnumType.STRING)
	protected PlatformsEnum name;

	@Override
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getSwkbtId() {
		return swkbtId;
	}

	public void setSwkbtId(int swkbtId) {
		this.swkbtId = swkbtId;
	}

	public PlatformsEnum getName() {
		return name;
	}

	public void setName(PlatformsEnum name) {
		this.name = name;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PlatformType [id=");
		builder.append(id);
		builder.append(", swkbtId=");
		builder.append(swkbtId);
		builder.append(", name=");
		builder.append(name);
		builder.append("]");
		return builder.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		result = prime * result + swkbtId;
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (!(obj instanceof Platform)) {
			return false;
		}
		Platform other = (Platform) obj;
		if (name != other.name) {
			return false;
		}
		if (swkbtId != other.swkbtId) {
			return false;
		}
		return super.equals(obj);
	}

}
