package IBM::Schema::CNDB::CdcustomerB;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("CDCUSTOMER_B");
__PACKAGE__->add_columns(
  "ibmsnap_commitseq",
  { data_type => "CHAR () FOR BIT DATA", is_nullable => 0, size => 10 },
  "ibmsnap_intentseq",
  { data_type => "CHAR () FOR BIT DATA", is_nullable => 0, size => 10 },
  "ibmsnap_operation",
  { data_type => "CHAR", is_nullable => 0, size => 1 },
  "customer_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "customer_type_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "pod_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "parent_request_number_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "industry_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "contact_dpe_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "contact_fa_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "contact_hw_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "contact_sw_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "contact_focal_asset_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "contact_transition_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "account_number",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "customer_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 64 },
  "abbr_customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sign_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "contract_start_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "contract_end_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "contract_value",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_hw_transfers",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_transfers_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_transfers",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_transfers_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "hostname_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tme_object_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "tlm_deployment_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "asset_tools_billing_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "status",
  { data_type => "VARCHAR", is_nullable => 0, size => 32 },
  "maint_only",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_only_cn",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "legacy_area",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "hw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "sw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "inv_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "clli",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "validated_by",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_license_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "sw_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "hw_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "geography",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "transition_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "transition_exit_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "country_code_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
);


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:32
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:k59Xi3tQv/aX8kWhnPNC1Q


# You can replace this text with custom content, and it will be preserved on regeneration
1;
