//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ApplicationServerSignatureType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ApplicationServerSignatureType">
 *   &lt;complexContent>
 *     &lt;extension base="{}SignatureType">
 *       &lt;sequence>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApplicationServerSignatureType", propOrder = { "additional" })
@XmlRootElement(name = "ApplicationServerSignature")
public class ApplicationServerSignatureType extends SignatureType {

	protected AdditionalStructureType additional;
	@XmlAttribute(required = true)
	protected String name;

	/**
	 * Gets the value of the additional property.
	 * 
	 * @return possible object is {@link AdditionalStructureType }
	 * 
	 */
	public AdditionalStructureType getAdditional() {
		return additional;
	}

	/**
	 * Sets the value of the additional property.
	 * 
	 * @param value
	 *            allowed object is {@link AdditionalStructureType }
	 * 
	 */
	public void setAdditional(final AdditionalStructureType value) {
		this.additional = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(final String value) {
		this.name = value;
	}

}
