//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FileSignatureType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="FileSignatureType">
 *   &lt;complexContent>
 *     &lt;extension base="{}SignatureType">
 *       &lt;sequence>
 *         &lt;element name="file" type="{}FileType" maxOccurs="unbounded"/>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="operator" type="{}signatureOperatorType" />
 *       &lt;attribute name="scope" type="{}fileSignatureScopeEnum" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FileSignatureType", propOrder = { "file", "additional" })
@XmlRootElement(name = "FileSignature")
public class FileSignatureType extends SignatureType {

	@XmlElement(required = true)
	protected List<FileType> file;
	protected AdditionalStructureType additional;
	@XmlAttribute
	protected SignatureOperatorType operator;
	@XmlAttribute
	protected FileSignatureScopeEnum scope;

	/**
	 * Gets the value of the file property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the file property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getFile().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list {@link FileType }
	 * 
	 * 
	 */
	public List<FileType> getFile() {
		if (file == null) {
			file = new ArrayList<FileType>();
		}
		return this.file;
	}

	/**
	 * Gets the value of the additional property.
	 * 
	 * @return possible object is {@link AdditionalStructureType }
	 * 
	 */
	public AdditionalStructureType getAdditional() {
		return additional;
	}

	/**
	 * Sets the value of the additional property.
	 * 
	 * @param value
	 *            allowed object is {@link AdditionalStructureType }
	 * 
	 */
	public void setAdditional(AdditionalStructureType value) {
		this.additional = value;
	}

	/**
	 * Gets the value of the operator property.
	 * 
	 * @return possible object is {@link SignatureOperatorType }
	 * 
	 */
	public SignatureOperatorType getOperator() {
		return operator;
	}

	/**
	 * Sets the value of the operator property.
	 * 
	 * @param value
	 *            allowed object is {@link SignatureOperatorType }
	 * 
	 */
	public void setOperator(SignatureOperatorType value) {
		this.operator = value;
	}

	/**
	 * Gets the value of the scope property.
	 * 
	 * @return possible object is {@link FileSignatureScopeEnum }
	 * 
	 */
	public FileSignatureScopeEnum getScope() {
		return scope;
	}

	/**
	 * Sets the value of the scope property.
	 * 
	 * @param value
	 *            allowed object is {@link FileSignatureScopeEnum }
	 * 
	 */
	public void setScope(FileSignatureScopeEnum value) {
		this.scope = value;
	}

}
