//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for MainframeProductType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="MainframeProductType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="alias" type="{}AliasType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="guid" use="required" type="{}GUIDType" />
 *       &lt;attribute name="manufacturer" use="required" type="{}GUIDType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productRole" type="{}productRoleEnumeration" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "MainframeProductType", propOrder = { "alias", "additional" })
@XmlType(name = "MainframeProductType" )
//@XmlType(name = "MainframeProductType", propOrder = { "productRole", "guid", "name", "manufacturer" })
@XmlRootElement(name = "MainframeProduct")
public class MainframeProductType extends SoftwareItemType {

	@XmlElement(required = true)
	protected List<AliasType> alias;
	protected AdditionalStructureType additional;
//	@XmlAttribute(required = true)
//	protected String guid;
	@XmlAttribute
//	protected Integer licenseType;
//	@XmlAttribute(required = true)
	protected String manufacturer;
//	@XmlAttribute
//	protected String name;
//	@XmlAttribute
//	protected ProductRoleEnumeration productRole;
//	@XmlAnyAttribute
//	private Map<QName, String> otherAttributes = new HashMap<QName, String>();

	/**
	 * Gets the value of the alias property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the alias property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAlias().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AliasType }
	 * 
	 * 
	 */
	public List<AliasType> getAlias() {
		if (alias == null) {
			alias = new ArrayList<AliasType>();
		}
		return this.alias;
	}

	/**
	 * Gets the value of the additional property.
	 * 
	 * @return possible object is {@link AdditionalStructureType }
	 * 
	 */
	public AdditionalStructureType getAdditional() {
		return additional;
	}

	/**
	 * Sets the value of the additional property.
	 * 
	 * @param value
	 *            allowed object is {@link AdditionalStructureType }
	 * 
	 */
	public void setAdditional(AdditionalStructureType value) {
		this.additional = value;
	}

	/**
	 * Gets the value of the guid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
//	public String getGuid() {
//		return guid;
//	}

	/**
	 * Sets the value of the guid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
//	public void setGuid(String value) {
//		this.guid = value;
//	}

	/**
	 * Gets the value of the manufacturer property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getManufacturer() {
		return manufacturer;
	}

	/**
	 * Sets the value of the manufacturer property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setManufacturer(String value) {
		this.manufacturer = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
//	public String getName() {
//		return name;
//	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
//	public void setName(String value) {
//		this.name = value;
//	}

	/**
	 * Gets the value of the productRole property.
	 * 
	 * @return possible object is {@link ProductRoleEnumeration }
	 * 
	 */
//    public ProductRoleEnumeration getProductRole() {
//		return productRole;
//	}

	/**
	 * Sets the value of the productRole property.
	 * 
	 * @param value
	 *            allowed object is {@link ProductRoleEnumeration }
	 * 
	 */
//	public void setProductRole(ProductRoleEnumeration value) {
//		this.productRole = value;
//	}

//	public Integer getLicenseType() {
//		return licenseType;
//	}

	/**
	 * Sets the value of the licenseType property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
//	public void setLicenseType(Integer value) {
//		this.licenseType = value;
//	}
	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 * 
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 * 
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 * 
	 * 
	 * @return always non-null
	 */
//	public Map<QName, String> getOtherAttributes() {
//		return otherAttributes;
//	}

}
