//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for ManufacturerType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="ManufacturerType">
 *   &lt;complexContent>
 *     &lt;extension base="{}KbDefinitionType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="alias" type="{}AliasType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="dId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="website" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManufacturerType", propOrder = { "aliasAndAdditional" })
@XmlRootElement(name = "Manufacturer")
public class ManufacturerType extends KbDefinitionType {

	@XmlElements({
			@XmlElement(name = "additional", required = true, type = AdditionalStructureType.class),
			@XmlElement(name = "alias", required = true, type = AliasType.class) })
	protected List<Object> aliasAndAdditional;
	@XmlAttribute
	protected String dId;
	@XmlAttribute(required = true)
	protected String name;
	@XmlAttribute
	protected String website;

	/**
	 * Gets the value of the aliasAndAdditional property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the aliasAndAdditional property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getAliasAndAdditional().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link AdditionalStructureType } {@link AliasType }
	 * 
	 * 
	 */
	public List<Object> getAliasAndAdditional() {
		if (aliasAndAdditional == null) {
			aliasAndAdditional = new ArrayList<Object>();
		}
		return this.aliasAndAdditional;
	}

	/**
	 * Gets the value of the dId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDId() {
		return dId;
	}

	/**
	 * Sets the value of the dId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDId(String value) {
		this.dId = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the website property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * Sets the value of the website property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWebsite(String value) {
		this.website = value;
	}

}
