//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for platformsEnum.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="platformsEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AIX"/>
 *     &lt;enumeration value="LINUX"/>
 *     &lt;enumeration value="SUN"/>
 *     &lt;enumeration value="HPUX"/>
 *     &lt;enumeration value="UNIX"/>
 *     &lt;enumeration value="WINDOWS"/>
 *     &lt;enumeration value="I5OS"/>
 *     &lt;enumeration value="ANY"/>
 *     &lt;enumeration value="z/OS"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum PlatformsEnum {

	AIX("AIX"), ANY("ANY"), HPUX("HPUX"), @XmlEnumValue("I5OS")
	I_5_OS("I5OS"), LINUX("LINUX"), SUN("SUN"), UNIX("UNIX"), WINDOWS("WINDOWS"), @XmlEnumValue("z/OS")
	Z_OS("z/OS");
	private final String value;

	PlatformsEnum(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static PlatformsEnum fromValue(String v) {
		for (PlatformsEnum c : PlatformsEnum.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v.toString());
	}

}
