//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;

/**
 * <p>
 * Java class for RegistryDataTypeEnum.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="RegistryDataTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="binary"/>
 *     &lt;enumeration value="dword"/>
 *     &lt;enumeration value="expand_string"/>
 *     &lt;enumeration value="multi_string"/>
 *     &lt;enumeration value="string"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum RegistryDataTypeEnum {

	@XmlEnumValue("binary")
	BINARY("binary"), @XmlEnumValue("dword")
	DWORD("dword"), @XmlEnumValue("expand_string")
	EXPAND_STRING("expand_string"), @XmlEnumValue("multi_string")
	MULTI_STRING("multi_string"), @XmlEnumValue("string")
	STRING("string");
	private final String value;

	RegistryDataTypeEnum(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static RegistryDataTypeEnum fromValue(String v) {
		for (RegistryDataTypeEnum c : RegistryDataTypeEnum.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v.toString());
	}

}
