//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * 
 * Relationships between SoftwareItems
 * 
 * 
 * <p>
 * Java class for RelationshipType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="RelationshipType">
 *   &lt;complexContent>
 *     &lt;extension base="{}KbDefinitionType">
 *       &lt;attribute name="sink" type="{}GUIDType" />
 *       &lt;attribute name="source" type="{}GUIDType" />
 *       &lt;attribute name="type" type="{}relationshipTypeEnum" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RelationshipType")
@XmlRootElement(name = "Relationship")
public class RelationshipType extends KbDefinitionType {

	@XmlAttribute
	protected String sink;
	@XmlAttribute
	protected String source;
	@XmlAttribute
	protected RelationshipTypeEnum type;

	/**
	 * Gets the value of the sink property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSink() {
		return sink;
	}

	/**
	 * Sets the value of the sink property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSink(String value) {
		this.sink = value;
	}

	/**
	 * Gets the value of the source property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSource() {
		return source;
	}

	/**
	 * Sets the value of the source property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSource(String value) {
		this.source = value;
	}

	/**
	 * Gets the value of the type property.
	 * 
	 * @return possible object is {@link RelationshipTypeEnum }
	 * 
	 */
	public RelationshipTypeEnum getType() {
		return type;
	}

	/**
	 * Sets the value of the type property.
	 * 
	 * @param value
	 *            allowed object is {@link RelationshipTypeEnum }
	 * 
	 */
	public void setType(RelationshipTypeEnum value) {
		this.type = value;
	}

}
