//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SignatureType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SignatureType">
 *   &lt;complexContent>
 *     &lt;extension base="{}KbDefinitionType">
 *       &lt;attribute name="cVersionPlatform" type="{}platformsEnum" />
 *       &lt;attribute name="confidenceLevel" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="discoveredItem" type="{}GUIDType" />
 *       &lt;attribute name="platform" use="required" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SignatureType")
public class SignatureType extends KbDefinitionType {

	@XmlAttribute
	protected PlatformsEnum cVersionPlatform;
	@XmlAttribute
	protected Integer confidenceLevel;
	@XmlAttribute
	protected String discoveredItem;
	@XmlAttribute(required = true)
	protected int platform;

	/**
	 * Gets the value of the cVersionPlatform property.
	 * 
	 * @return possible object is {@link PlatformsEnum }
	 * 
	 */
	public PlatformsEnum getCVersionPlatform() {
		return cVersionPlatform;
	}

	/**
	 * Sets the value of the cVersionPlatform property.
	 * 
	 * @param value
	 *            allowed object is {@link PlatformsEnum }
	 * 
	 */
	public void setCVersionPlatform(PlatformsEnum value) {
		this.cVersionPlatform = value;
	}

	/**
	 * Gets the value of the confidenceLevel property.
	 * 
	 * @return possible object is {@link Integer }
	 * 
	 */
	public Integer getConfidenceLevel() {
		return confidenceLevel;
	}

	/**
	 * Sets the value of the confidenceLevel property.
	 * 
	 * @param value
	 *            allowed object is {@link Integer }
	 * 
	 */
	public void setConfidenceLevel(Integer value) {
		this.confidenceLevel = value;
	}

	/**
	 * Gets the value of the discoveredItem property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDiscoveredItem() {
		return discoveredItem;
	}

	/**
	 * Sets the value of the discoveredItem property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDiscoveredItem(String value) {
		this.discoveredItem = value;
	}

	/**
	 * Gets the value of the platform property.
	 * 
	 */
	public int getPlatform() {
		return platform;
	}

	/**
	 * Sets the value of the platform property.
	 * 
	 */
	public void setPlatform(int value) {
		this.platform = value;
	}

}
