//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for SoftwareKnowledgeBase element declaration.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;element name="SoftwareKnowledgeBase">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;extension base="{}SwkbType">
 *       &lt;/extension>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareKnowledgeBase")
@XmlRootElement(name = "SoftwareKnowledgeBase")
public class SoftwareKnowledgeBase {
	
	@XmlAttribute
	protected String databaseInstanceName;

	public String getDatabaseInstanceName() {
		return databaseInstanceName;
	}

	public void setDatabaseInstanceName(String databaseInstanceName) {
		this.databaseInstanceName = databaseInstanceName;
	}

}
