//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for SoftwareItemType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SoftwareItemType">
 *   &lt;complexContent>
 *     &lt;extension base="{}KbDefinitionType">
 *       &lt;attribute name="activationDate" type="{}dateTimeType" />
 *       &lt;attribute name="endOfSupport" type="{}dateTimeType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productIds" type="{}spaceDelimStringListType" />
 *       &lt;attribute name="productRole" type="{}productRoleEnumeration" />
 *       &lt;attribute name="website" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SoftwareItemType")
public class SoftwareItemType extends KbDefinitionType {

	@XmlAttribute
	protected XMLGregorianCalendar activationDate;
	@XmlAttribute
	protected XMLGregorianCalendar endOfSupport;
	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected String productId;
	@XmlAttribute
	protected String productIds;
	@XmlAttribute
	protected ProductRoleEnumeration productRole;
	@XmlAttribute
	protected String website;

	/**
	 * Gets the value of the activationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getActivationDate() {
		return activationDate;
	}

	/**
	 * Sets the value of the activationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setActivationDate(XMLGregorianCalendar value) {
		this.activationDate = value;
	}

	/**
	 * Gets the value of the endOfSupport property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getEndOfSupport() {
		return endOfSupport;
	}

	/**
	 * Sets the value of the endOfSupport property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setEndOfSupport(XMLGregorianCalendar value) {
		this.endOfSupport = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the productId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductId() {
		return productId;
	}

	/**
	 * Sets the value of the productId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductId(String value) {
		this.productId = value;
	}

	/**
	 * Gets the value of the productIds property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getProductIds() {
		return productIds;
	}

	/**
	 * Sets the value of the productIds property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setProductIds(String value) {
		this.productIds = value;
	}

	/**
	 * Gets the value of the productRole property.
	 * 
	 * @return possible object is {@link ProductRoleEnumeration }
	 * 
	 */
	public ProductRoleEnumeration getProductRole() {
		return productRole;
	}

	/**
	 * Sets the value of the productRole property.
	 * 
	 * @param value
	 *            allowed object is {@link ProductRoleEnumeration }
	 * 
	 */
	public void setProductRole(ProductRoleEnumeration value) {
		this.productRole = value;
	}

	/**
	 * Gets the value of the website property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getWebsite() {
		return website;
	}

	/**
	 * Sets the value of the website property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setWebsite(String value) {
		this.website = value;
	}

}
