//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b52-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.10.19 at 09:53:30 PM EDT 
//

package com.ibm.asset.swkbt.schema;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyAttribute;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;

/**
 * <p>
 * Java class for SwkbType complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="SwkbType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Platforms">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Platform" type="{}PlatformType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="DefinitionSources" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Source" type="{}DefintionSourceType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="KbIdentity" type="{}KbIdentityType" maxOccurs="unbounded"/>
 *         &lt;element name="IdentityLinks" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Link" type="{}IdentityLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="additional" type="{}additionalStructureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="contact" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="copyright" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="creationDate" use="required" type="{}dateTimeType" />
 *       &lt;attribute name="dataVersion" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="databaseInstanceId" type="{}GUIDType" />
 *       &lt;attribute name="databaseInstanceName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="filterEndDate" type="{}dateTimeType" />
 *       &lt;attribute name="filterStartDate" type="{}dateTimeType" />
 *       &lt;attribute name="filterUsed" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="guid" type="{}GUIDType" />
 *       &lt;attribute name="lastModification" type="{}dateTimeType" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="schemaVersion" type="{}schemaVersionType" />
 *       &lt;attribute name="sourceType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="swkbtBuildNumber" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SwkbType")
public class SwkbType {

	@XmlAttribute
	protected String contact;
	@XmlAttribute
	protected String copyright;
	@XmlAttribute(required = true)
	protected XMLGregorianCalendar creationDate;
	@XmlAttribute
	protected Long dataVersion;
	@XmlAttribute
	protected String databaseInstanceId;
	@XmlAttribute
	protected String databaseInstanceName;
	@XmlAttribute
	protected String description;
	@XmlAttribute
	protected XMLGregorianCalendar filterEndDate;
	@XmlAttribute
	protected XMLGregorianCalendar filterStartDate;
	@XmlAttribute
	protected String filterUsed;
	@XmlAttribute
	protected String guid;
	@XmlAttribute
	protected XMLGregorianCalendar lastModification;
	@XmlAttribute
	protected String name;
	@XmlAttribute
	protected String schemaVersion;
	@XmlAttribute
	protected String sourceType;
	@XmlAttribute
	protected String swkbtBuildNumber;
	@XmlAnyAttribute
	private Map<QName, String> otherAttributes = new HashMap<QName, String>();


	/**
	 * Gets the value of the contact property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * Sets the value of the contact property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setContact(String value) {
		this.contact = value;
	}

	/**
	 * Gets the value of the copyright property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getCopyright() {
		return copyright;
	}

	/**
	 * Sets the value of the copyright property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setCopyright(String value) {
		this.copyright = value;
	}

	/**
	 * Gets the value of the creationDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getCreationDate() {
		return creationDate;
	}

	/**
	 * Sets the value of the creationDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setCreationDate(XMLGregorianCalendar value) {
		this.creationDate = value;
	}

	/**
	 * Gets the value of the dataVersion property.
	 * 
	 * @return possible object is {@link Long }
	 * 
	 */
	public Long getDataVersion() {
		return dataVersion;
	}

	/**
	 * Sets the value of the dataVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link Long }
	 * 
	 */
	public void setDataVersion(Long value) {
		this.dataVersion = value;
	}

	/**
	 * Gets the value of the databaseInstanceId property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDatabaseInstanceId() {
		return databaseInstanceId;
	}

	/**
	 * Sets the value of the databaseInstanceId property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDatabaseInstanceId(String value) {
		this.databaseInstanceId = value;
	}

	/**
	 * Gets the value of the databaseInstanceName property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDatabaseInstanceName() {
		return databaseInstanceName;
	}

	/**
	 * Sets the value of the databaseInstanceName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDatabaseInstanceName(String value) {
		this.databaseInstanceName = value;
	}

	/**
	 * Gets the value of the description property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * Sets the value of the description property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setDescription(String value) {
		this.description = value;
	}

	/**
	 * Gets the value of the filterEndDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFilterEndDate() {
		return filterEndDate;
	}

	/**
	 * Sets the value of the filterEndDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFilterEndDate(XMLGregorianCalendar value) {
		this.filterEndDate = value;
	}

	/**
	 * Gets the value of the filterStartDate property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getFilterStartDate() {
		return filterStartDate;
	}

	/**
	 * Sets the value of the filterStartDate property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setFilterStartDate(XMLGregorianCalendar value) {
		this.filterStartDate = value;
	}

	/**
	 * Gets the value of the filterUsed property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFilterUsed() {
		return filterUsed;
	}

	/**
	 * Sets the value of the filterUsed property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setFilterUsed(String value) {
		this.filterUsed = value;
	}

	/**
	 * Gets the value of the guid property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getGuid() {
		return guid;
	}

	/**
	 * Sets the value of the guid property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setGuid(String value) {
		this.guid = value;
	}

	/**
	 * Gets the value of the lastModification property.
	 * 
	 * @return possible object is {@link XMLGregorianCalendar }
	 * 
	 */
	public XMLGregorianCalendar getLastModification() {
		return lastModification;
	}

	/**
	 * Sets the value of the lastModification property.
	 * 
	 * @param value
	 *            allowed object is {@link XMLGregorianCalendar }
	 * 
	 */
	public void setLastModification(XMLGregorianCalendar value) {
		this.lastModification = value;
	}

	/**
	 * Gets the value of the name property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getName() {
		return name;
	}

	/**
	 * Sets the value of the name property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setName(String value) {
		this.name = value;
	}

	/**
	 * Gets the value of the schemaVersion property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSchemaVersion() {
		return schemaVersion;
	}

	/**
	 * Sets the value of the schemaVersion property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSchemaVersion(String value) {
		this.schemaVersion = value;
	}

	/**
	 * Gets the value of the sourceType property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSourceType() {
		return sourceType;
	}

	/**
	 * Sets the value of the sourceType property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSourceType(String value) {
		this.sourceType = value;
	}

	/**
	 * Gets the value of the swkbtBuildNumber property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getSwkbtBuildNumber() {
		return swkbtBuildNumber;
	}

	/**
	 * Sets the value of the swkbtBuildNumber property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 * 
	 */
	public void setSwkbtBuildNumber(String value) {
		this.swkbtBuildNumber = value;
	}

	/**
	 * Gets a map that contains attributes that aren't bound to any typed
	 * property on this class.
	 * 
	 * <p>
	 * the map is keyed by the name of the attribute and the value is the string
	 * value of the attribute.
	 * 
	 * the map returned by this method is live, and you can add new attribute by
	 * updating the map directly. Because of this design, there's no setter.
	 * 
	 * 
	 * @return always non-null
	 */
	public Map<QName, String> getOtherAttributes() {
		return otherAttributes;
	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Source" type="{}DefintionSourceType" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "source" })
	public static class DefinitionSources {

		@XmlElement(name = "Source", required = true)
		protected List<DefintionSourceType> source;

		/**
		 * Gets the value of the source property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the source property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getSource().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link DefintionSourceType }
		 * 
		 * 
		 */
		public List<DefintionSourceType> getSource() {
			if (source == null) {
				source = new ArrayList<DefintionSourceType>();
			}
			return this.source;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Link" type="{}IdentityLinkType" maxOccurs="unbounded" minOccurs="0"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "link" })
	public static class IdentityLinks {

		@XmlElement(name = "Link", required = true)
		protected List<IdentityLinkType> link;

		/**
		 * Gets the value of the link property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the link property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getLink().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link IdentityLinkType }
		 * 
		 * 
		 */
		public List<IdentityLinkType> getLink() {
			if (link == null) {
				link = new ArrayList<IdentityLinkType>();
			}
			return this.link;
		}

	}

	/**
	 * <p>
	 * Java class for anonymous complex type.
	 * 
	 * <p>
	 * The following schema fragment specifies the expected content contained
	 * within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	 *       &lt;sequence>
	 *         &lt;element name="Platform" type="{}PlatformType" maxOccurs="unbounded"/>
	 *       &lt;/sequence>
	 *     &lt;/restriction>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "platform" })
	public static class Platforms {

		@XmlElement(name = "Platform", required = true)
		protected List<PlatformType> platform;

		/**
		 * Gets the value of the platform property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list, not a
		 * snapshot. Therefore any modification you make to the returned list
		 * will be present inside the JAXB object. This is why there is not a
		 * <CODE>set</CODE> method for the platform property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * 
		 * <pre>
		 * getPlatform().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link PlatformType }
		 * 
		 * 
		 */
		public List<PlatformType> getPlatform() {
			if (platform == null) {
				platform = new ArrayList<PlatformType>();
			}
			return this.platform;
		}

	}

}
