#!/bin/sh
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/hwLparActiveNoSwLparHwStatusNotActiveOpenAlert.txt |awk -F '|' '{print "insert into recon_hw_lpar(customer_id,hardware_lpar_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/swLparInactiveOpenNoHwAlert.txt |awk -F '|' '{print "insert into recon_sw_lpar(customer_id,software_lpar_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/hwLparNoSwLparNoAlert.txt |awk -F '|' '{print "insert into recon_hw_lpar(customer_id,hardware_lpar_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/hwLparInactiveOpenAlert.txt |awk -F '|' '{print "insert into recon_hw_lpar(customer_id,hardware_lpar_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/instSwUnlicensableRecon.txt |awk -F '|' '{print "insert into recon_installed_sw(customer_id,installed_software_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/instSwInReconBaseNoAlert.txt |awk -F '|' '{print "insert into recon_installed_sw(customer_id,installed_software_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/instSwUnlicensableOpenAlert.txt |awk -F '|' '{print "insert into recon_installed_sw(customer_id,installed_software_id, action, remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
cat /opt/IBMIHS/htdocs/en_US/bravo_hchks/instSwInactiveOpenAlert.txt |awk -F '|' '{print "insert into recon_installed_sw(customer_id,installed_software_id,action,remote_user,record_time) values(" $1 "," $2 ",'"'"'UPDATE'"'"','"'"'STAGING'"'"',current timestamp);"}' |uniq >> temp.sql
#db2 -tvf temp.sql
