------------------------------------------------
-- DDL Statements for Table "EAADMIN "."SOFTWARE_SCRIPT"
------------------------------------------------
 

CREATE TABLE "EAADMIN "."SOFTWARE_SCRIPT"  (
		  "SOFTWARE_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "SOFTWARE_NAME" VARCHAR(128) NOT NULL , 
		  "SOFTWARE_VERSION" VARCHAR(64) NULL , 
		  "MAP_SOFTWARE_VERSION" VARCHAR(64) , 
		  "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL , 
		  "COMMENTS" VARCHAR(255) , 
		  "REMOTE_USER" VARCHAR(32) NOT NULL , 
		  "RECORD_TIME" TIMESTAMP NOT NULL , 
		  "STATUS" VARCHAR(32) NOT NULL , 
		  "CATALOG_TYPE" VARCHAR(32) )   
		 DATA CAPTURE CHANGES  
		 IN "SOFTWARE" INDEX IN "SOFTWAREINDEX" ; 



-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF1SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("SOFTWARE_ID" ASC,
		 "STATUS" ASC,
		 "SOFTWARE_SCRIPT_ID" ASC,
		 "SOFTWARE_NAME" ASC,
		 "SOFTWARE_VERSION" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF2SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("SOFTWARE_NAME" ASC,
		 "SOFTWARE_VERSION" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF3SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("SOFTWARE_SCRIPT_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF4SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("SOFTWARE_SCRIPT_ID" ASC)
		INCLUDE ("MAP_SOFTWARE_VERSION" )
		
		COMPRESS NO ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "EAADMIN "."SOFTWARE_SCRIPT"

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE INDEX "EAADMIN "."IF5SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("STATUS" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
		
		
ALTER TABLE "EAADMIN "."SOFTWARE_SCRIPT" 
	ADD CONSTRAINT "PKSOFTWARESCRIPT" PRIMARY KEY
		("SOFTWARE_SCRIPT_ID");



/*
------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CD"."SOFTWARE_SCRIPT"
------------------------------------------------
 

CREATE TABLE "TRAILSPD_CD"."SOFTWARE_SCRIPT"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "SOFTWARE_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "SOFTWARE_NAME" VARCHAR(128) NOT NULL , 
		  "SOFTWARE_VERSION" VARCHAR(64) NOT NULL , 
		  "MAP_SOFTWARE_VERSION" VARCHAR(64) , 
		  "END_OF_SUPPORT" TIMESTAMP , 
		  "OS_TYPE" VARCHAR(32) , 
		  "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL , 
		  "COMMENTS" VARCHAR(255) , 
		  "REMOTE_USER" VARCHAR(32) NOT NULL , 
		  "RECORD_TIME" TIMESTAMP NOT NULL , 
		  "STATUS" VARCHAR(32) NOT NULL , 
		  "CATALOG_TYPE" VARCHAR(32) )   
		 IN "TRAILSPD_CD_TABLES" INDEX IN "TRAILSPD_CD_INDEX" ; 

ALTER TABLE "TRAILSPD_CD"."SOFTWARE_SCRIPT" VOLATILE CARDINALITY;






-- DDL Statements for Indexes on Table "TRAILSPD_CD"."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "TRAILSPD_CD"."IXSOFTWARE_SCRIPT" ON "TRAILSPD_CD"."SOFTWARE_SCRIPT" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CC"."SOFTWARE_SCRIPT"
------------------------------------------------
 

CREATE TABLE "TRAILSPD_CC"."SOFTWARE_SCRIPT"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "SOFTWARE_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "SOFTWARE_NAME" VARCHAR(128) NOT NULL , 
		  "SOFTWARE_VERSION" VARCHAR(64) NOT NULL , 
		  "MAP_SOFTWARE_VERSION" VARCHAR(64) , 
		  "END_OF_SUPPORT" TIMESTAMP , 
		  "OS_TYPE" VARCHAR(32) , 
		  "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL , 
		  "COMMENTS" VARCHAR(255) , 
		  "REMOTE_USER" VARCHAR(32) NOT NULL , 
		  "RECORD_TIME" TIMESTAMP NOT NULL , 
		  "STATUS" VARCHAR(32) NOT NULL , 
		  "CATALOG_TYPE" VARCHAR(32) )   
		 IN "TRAILSPD_CD_TABLES" INDEX IN "TRAILSPD_CD_INDEX" ; 

ALTER TABLE "TRAILSPD_CC"."SOFTWARE_SCRIPT" VOLATILE CARDINALITY;






-- DDL Statements for Indexes on Table "TRAILSPD_CC"."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "TRAILSPD_CC"."IXSOFTWARE_SCRIPT" ON "TRAILSPD_CC"."SOFTWARE_SCRIPT" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;





*/


--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

 
GRANT DELETE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT INSERT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT SELECT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT UPDATE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT REFERENCES ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT DELETE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT INSERT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT SELECT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT UPDATE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO GROUP "TRAILUPD" ;

