
------------------------------------------------
-- DDL Statements for Table "EAADMIN "."INSTALLED_SCRIPT"
------------------------------------------------
 

CREATE TABLE "EAADMIN "."INSTALLED_SCRIPT"  (
		  "ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +2147483647  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) ,
		  "INSTALLED_SOFTWARE_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "BANK_ACCOUNT_ID" BIGINT NOT NULL ,
		  "STATUS" VARCHAR(32) NULL 
		  )   
		 DATA CAPTURE CHANGES  
		 IN "INSTALLED" INDEX IN "INSTALLEDINDEX" ; 



-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF1INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT" 
		("INSTALLED_SOFTWARE_ID" ASC,
		 "SOFTWARE_SCRIPT_ID" ASC,
		 "BANK_ACCOUNT_ID" ASC,
		 "STATUS" ASC,
		 "ID" ASC)
		CLUSTER 
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF2INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT" 
		("BANK_ACCOUNT_ID" ASC,
		 "INSTALLED_SOFTWARE_ID" ASC,
		 "ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF3INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT" 
		("SOFTWARE_SCRIPT_ID" ASC,
		 "INSTALLED_SOFTWARE_ID" ASC,
		 "BANK_ACCOUNT_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE INDEX "EAADMIN "."IF4INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT" 
		("INSTALLED_SOFTWARE_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."PKINSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT" 
		("ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "EAADMIN "."INSTALLED_SCRIPT"

ALTER TABLE "EAADMIN "."INSTALLED_SCRIPT" 
	ADD CONSTRAINT "PKINSTALLEDSCRIPT" PRIMARY KEY
		("ID");





------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CD"."INSTALLED_SCRIPT"
------------------------------------------------
/*

CREATE TABLE "TRAILSPD_CD"."INSTALLED_SCRIPT"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "INSTALLED_SOFTWARE_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "BANK_ACCOUNT_ID" BIGINT NOT NULL , 
		  "ID" INTEGER NOT NULL WITH DEFAULT  )   
		 IN "TRAILSPD_CD_TABLES" INDEX IN "TRAILSPD_CD_INDEX" ; 

ALTER TABLE "TRAILSPD_CD"."INSTALLED_SCRIPT" VOLATILE CARDINALITY;






-- DDL Statements for Indexes on Table "TRAILSPD_CD"."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "TRAILSPD_CD"."IXINSTALLED_SCRIPT" ON "TRAILSPD_CD"."INSTALLED_SCRIPT" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;

------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CC"."INSTALLED_SCRIPT"
------------------------------------------------
 

CREATE TABLE "TRAILSPD_CC"."INSTALLED_SCRIPT"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "INSTALLED_SOFTWARE_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "BANK_ACCOUNT_ID" BIGINT NOT NULL , 
		  "ID" INTEGER NOT NULL WITH DEFAULT  )   
		 IN "TRAILSPD_CD_TABLES" INDEX IN "TRAILSPD_CD_INDEX" ; 

ALTER TABLE "TRAILSPD_CC"."INSTALLED_SCRIPT" VOLATILE CARDINALITY;






-- DDL Statements for Indexes on Table "TRAILSPD_CC"."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "TRAILSPD_CC"."IXINSTALLED_SCRIPT" ON "TRAILSPD_CC"."INSTALLED_SCRIPT" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Foreign Keys on Table "EAADMIN "."INSTALLED_SCRIPT"

ALTER TABLE "EAADMIN "."INSTALLED_SCRIPT" 
	ADD CONSTRAINT "INSTALLEDSOFTWARE" FOREIGN KEY
		("INSTALLED_SOFTWARE_ID")
	REFERENCES "EAADMIN "."INSTALLED_SOFTWARE"
		("ID")
	ON DELETE RESTRICT
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;

*/


--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

 
GRANT DELETE ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT INSERT ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT SELECT ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT UPDATE ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT REFERENCES ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILPRD" ;

GRANT DELETE ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT INSERT ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT SELECT ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT UPDATE ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILUPD" ;

GRANT REFERENCES ON TABLE "EAADMIN "."INSTALLED_SCRIPT" TO GROUP "TRAILUPD" ;

