
------------------------------------------------
-- DDL Statements for Table "EAADMIN "."SOFTWARE_SCRIPT"
------------------------------------------------
 

CREATE TABLE "EAADMIN "."SOFTWARE_SCRIPT"  (
		  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
		  "SCAN_RECORD_ID" BIGINT NOT NULL , 
		  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL , 
		  "SOFTWARE_ID" BIGINT NOT NULL , 
		  "STATUS" VARCHAR(32) NOT NULL ,
		  "ACTION" VARCHAR(32) NOT NULL
)   
IN "SCANRECORD" ; 


-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF1SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("SCAN_RECORD_ID" ASC,
		 "SOFTWARE_SCRIPT_ID" ASC,
		 "SOFTWARE_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE INDEX "EAADMIN "."IF2SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("SCAN_RECORD_ID" ASC,
		 "STATUS" ASC,
		 "ACTION" ASC,
		 "SOFTWARE_ID" ASC,
		 "SOFTWARE_SCRIPT_ID" ASC,
		 "ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."SC_ID" ON "EAADMIN "."SOFTWARE_SCRIPT" 
		("ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "EAADMIN "."SOFTWARE_SCRIPT"

ALTER TABLE "EAADMIN "."SOFTWARE_SCRIPT" 
	ADD CONSTRAINT "SC_PK" PRIMARY KEY
		("ID");



-- DDL Statements for Aliases based on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE ALIAS "STAGING "."SOFTWARE_SCRIPT" FOR TABLE "EAADMIN "."SOFTWARE_SCRIPT";

-- DDL Statements for Foreign Keys on Table "EAADMIN "."SOFTWARE_SCRIPT"

ALTER TABLE "EAADMIN "."SOFTWARE_SCRIPT" 
	ADD CONSTRAINT "SCANRECORD" FOREIGN KEY
		("SCAN_RECORD_ID")
	REFERENCES "EAADMIN "."SCAN_RECORD"
		("ID")
	ON DELETE CASCADE
	ON UPDATE NO ACTION
	ENFORCED
	ENABLE QUERY OPTIMIZATION;







--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

 
GRANT DELETE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO USER "EAADMIN " ;

GRANT INSERT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO USER "EAADMIN " ;

GRANT SELECT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO USER "EAADMIN " ;

GRANT UPDATE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT" TO USER "EAADMIN " ;


