-- DROP TABLE EAADMIN.MQT_OP_METRICS_SWTRACKING;

CREATE SUMMARY TABLE EAADMIN.MQT_OP_METRICS_SWTRACKING
(
   ID,
   CUSTOMER_ID,
   DISPLAY_NAME,
   ASSET_TYPE,
   RECORD_TIME,
   ASSIGNED,
   RED,
   YELLOW,
   GREEN,
   RED91,
   RED121,
   RED151,
   RED181,
   RED366,
   ASSET_TOTAL
)
AS
(
   SELECT
   ID ,
   CUSTOMER_ID ,
   DISPLAY_NAME ,
   ASSET_TYPE ,
   CURRENT TIMESTAMP ,
   ASSIGNED ,
   RED ,
   YELLOW ,
   GREEN ,
   RED91 ,
   RED121 ,
   RED151 ,
   RED181 ,
   RED366 ,
   ASSET_TOTAL
   FROM
   (
      SELECT
      'HARDWARE' || CASE WHEN H.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1a: HW WITH HOSTNAME' AS DISPLAY_NAME ,
      CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AH.REMOTE_USER IS NULL THEN NULL WHEN AH.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM(CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) > 365 THEN 1 ELSE 0 END) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END) AS RED91 ,
      SUM( CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.HARDWARE H ON H.CUSTOMER_ID = C.CUSTOMER_ID AND H.STATUS = 'ACTIVE'
								AND ((C.SW_LICENSE_MGMT IS NULL ) OR (C.SW_LICENSE_MGMT != 'YES')) AND C.SW_TRACKING = 'YES'
								AND C.STATUS = 'ACTIVE' 
      LEFT OUTER JOIN EAADMIN.ALERT_HARDWARE AH ON AH.HARDWARE_ID = H.ID AND AH.OPEN = 1 
      LEFT OUTER JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'HARDWARE' || CASE WHEN H.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'HARDWARE' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1a: HW WITH HOSTNAME' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE ((C.SW_LICENSE_MGMT IS NULL ) OR (C.SW_LICENSE_MGMT != 'YES'))
      AND C.STATUS = 'ACTIVE'
      AND C.SW_TRACKING = 'YES' 
      UNION
      ALL
      SELECT
      'HARDWARE' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1a: HW WITH HOSTNAME' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.SW_TRACKING = 'YES' 
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HW_LPAR' || CASE WHEN HL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2a: HW LPAR WITH SW LPAR' AS DISPLAY_NAME ,
      CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AHL.REMOTE_USER IS NULL THEN NULL WHEN AHL.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      SUM( CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' AND HL.LPAR_STATUS != 'HWCOUNT' THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C JOIN
      EAADMIN.HARDWARE_LPAR HL ON HL.CUSTOMER_ID = C.CUSTOMER_ID AND HL.STATUS = 'ACTIVE' 
										AND (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' )) AND C.SW_TRACKING = 'YES' AND C.STATUS = 'ACTIVE'
      JOIN EAADMIN.HARDWARE H ON H.ID = HL.HARDWARE_ID 
      LEFT OUTER JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID 
      LEFT OUTER JOIN EAADMIN.ALERT_HW_LPAR AHL ON AHL.HARDWARE_LPAR_ID = HL.ID AND AHL.OPEN = 1
      GROUP BY 'HW_LPAR' || CASE WHEN HL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'HW_LPAR' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2a: HW LPAR WITH SW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE ((C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.SW_TRACKING = 'YES' 
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HW_LPAR' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2a: HW LPAR WITH SW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.SW_TRACKING = 'YES' 
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SW_LPAR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2b: SW LPAR WITH HW LPAR' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ASL.REMOTE_USER IS NULL THEN NULL WHEN ASL.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(SL.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID 
				AND SL.STATUS = 'ACTIVE' AND (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' )) 
				AND C.SW_TRACKING = 'YES' AND C.STATUS = 'ACTIVE' 
      LEFT OUTER JOIN EAADMIN.ALERT_SW_LPAR ASL ON SL.ID = ASL.SOFTWARE_LPAR_ID AND ASL.OPEN = 1 
      LEFT OUTER JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID 
      LEFT OUTER JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID 
      LEFT OUTER JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID 
      LEFT OUTER JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'SW_LPAR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SW_LPAR' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2b: SW LPAR WITH HW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.SW_TRACKING = 'YES' 
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SW_LPAR' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2b: SW LPAR WITH HW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.SW_TRACKING = 'YES' 
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'EXP_SCAN' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2c: UNEXPIRED SW LPAR' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AES.REMOTE_USER IS NULL THEN NULL WHEN AES.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 0 AND 45 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(SL.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C JOIN EAADMIN.SOFTWARE_LPAR SL ON C.CUSTOMER_ID = SL.CUSTOMER_ID
			AND C.SW_TRACKING = 'YES' AND (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
			AND C.STATUS = 'ACTIVE' AND SL.STATUS = 'ACTIVE' 
      LEFT OUTER JOIN EAADMIN.ALERT_EXPIRED_SCAN AES ON AES.SOFTWARE_LPAR_ID = SL.ID AND AES.OPEN = 1 
      LEFT OUTER JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID 
      LEFT OUTER JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID 
      LEFT OUTER JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID 
      LEFT OUTER JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'EXP_SCAN' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'EXP_SCAN' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2c: UNEXPIRED SW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_TRACKING = 'YES' AND (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'EXP_SCAN' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2c: UNEXPIRED SW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_TRACKING = 'YES' AND (( C.SW_LICENSE_MGMT IS NULL ) OR ( C.SW_LICENSE_MGMT != 'YES' ))
      AND C.STATUS = 'ACTIVE'
   )
   AS T
)
DATA INITIALLY DEFERRED REFRESH DEFERRED ENABLE QUERY OPTIMIZATION MAINTAINED BY SYSTEM IN "MISC" INDEX IN "MISCINDEX"
;

ALTER TABLE "EAADMIN "."MQT_OP_METRICS_SWTRACKING" DEACTIVATE ROW ACCESS CONTROL;

SET INTEGRITY FOR "EAADMIN"."MQT_OP_METRICS_SWTRACKING" IMMEDIATE CHECKED;

GRANT CONTROL ON EAADMIN.MQT_OP_METRICS_SWTRACKING TO USER EAADMIN		
;			
GRANT SELECT ON EAADMIN.MQT_OP_METRICS_SWTRACKING TO GROUP TRAILRPT		
;	
