ALTER TABLE "EAADMIN"."BANK_ACCOUNT" ALTER COLUMN NAME SET DATA TYPE VARCHAR(64)
;
ALTER TABLE TRAILSPD_CD.BANK_ACCOUNT ALTER COLUMN NAME SET DATA TYPE VARCHAR(64); 
ALTER TABLE TRAILSPD_CC.BANK_ACCOUNT ALTER COLUMN NAME SET DATA TYPE VARCHAR(64); 
REORG TABLE EAADMIN.BANK_ACCOUNT;
REORG TABLE TRAILSPD_CD.BANK_ACCOUNT;
REORG TABLE TRAILSPD_CC.BANK_ACCOUNT;
RUNSTATS ON TABLE EAADMIN.BANK_ACCOUNT ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.BANK_ACCOUNT ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.BANK_ACCOUNT ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;