
-- LIST OF RECOMMENDED INDEXES
-- ===========================
-- index[1],    6.548MB
   CREATE INDEX "EAADMIN "."IDX1608062047050" ON "EAADMIN "."SCHEDULE_F"
   ("LEVEL" ASC, "SCOPE_ID" ASC, "STATUS_ID" ASC, "MANUFACTURER"
   ASC, "ID" ASC, "CUSTOMER_ID" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- index[2],    6.571MB
   CREATE INDEX "EAADMIN "."IDX1608062046370" ON "EAADMIN "."SCHEDULE_F"
   ("LEVEL" ASC, "SCOPE_ID" ASC, "STATUS_ID" ASC, "SOFTWARE_NAME"
   ASC, "ID" ASC, "HW_OWNER" ASC, "CUSTOMER_ID" ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- index[3],    8.341MB
   CREATE INDEX "EAADMIN "."IDX1608062046130" ON "EAADMIN "."SCHEDULE_F"
   ("LEVEL" ASC, "SCOPE_ID" ASC, "STATUS_ID" ASC, "SOFTWARE_NAME"
   ASC, "ID" ASC, "MACHINE_TYPE" ASC, "SERIAL" ASC, "CUSTOMER_ID"
   ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- index[4],   50.349MB
   CREATE INDEX "EAADMIN "."IDX1608062045460" ON "EAADMIN "."SCHEDULE_F"
   ("SCOPE_ID" ASC, "LEVEL" ASC, "STATUS_ID" ASC, "SOFTWARE_NAME"
   ASC, "ID" ASC, "HOSTNAME" ASC, "CUSTOMER_ID" ASC)
   ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- index[5],    0.790MB
   CREATE INDEX "EAADMIN "."IDX1608062040490" ON "EAADMIN "."CUSTOMER"
   ("SW_LICENSE_MGMT" ASC, "STATUS" ASC, "CUSTOMER_ID"
   ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;

-- index[6],  139.899MB
   CREATE INDEX "EAADMIN "."IDX1608062041350" ON "EAADMIN "."HARDWARE_LPAR"
   ("LPAR_STATUS" ASC, "STATUS" ASC, "HARDWARE_ID" ASC,
   "ID" ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
 
-- index[7],   32.899MB
   CREATE INDEX "EAADMIN "."IDX1608062043510" ON "EAADMIN "."HARDWARE"
   ("MACHINE_TYPE_ID" ASC, "HARDWARE_STATUS" ASC, "STATUS"
   ASC, "OWNER" ASC, "SERIAL" ASC, "ID" ASC) ALLOW REVERSE
   SCANS COLLECT SAMPLED DETAILED STATISTICS;
 
-- index[8],  391.935MB
   CREATE INDEX "EAADMIN "."IDX1608062043450" ON "EAADMIN "."INSTALLED_SOFTWARE"
   ("SOFTWARE_LPAR_ID" ASC, "STATUS" ASC, "ID" ASC, "SOFTWARE_ID"
   ASC) ALLOW REVERSE SCANS COLLECT SAMPLED DETAILED STATISTICS;
 
   CREATE INDEX "EAADMIN "."IDXFCSLLSCHEDULEF" ON "EAADMIN "."SCHEDULE_F"
                ("CUSTOMER_ID" ASC,
                 "LEVEL" ASC) COMPRESS NO ALLOW REVERSE SCANS;
   CREATE INDEX "EAADMIN "."IDXFICSSCHEDULEF" ON "EAADMIN "."SCHEDULE_F"
                ("CUSTOMER_ID" ASC,
                "ID" ASC)
                COMPRESS NO ALLOW REVERSE SCANS;
   CREATE INDEX "EAADMIN "."IDXFSSTSCHEDULEF" ON "EAADMIN "."SCHEDULE_F"
                ("STATUS_ID" ASC, 
                "ID" ASC)
                COMPRESS NO ALLOW REVERSE SCANS;
   CREATE INDEX "EAADMIN "."IDXFCNLSCHEDULEF" ON "EAADMIN "."SCHEDULE_F"
                ("CUSTOMER_ID" ASC,
                 "SOFTWARE_NAME" ASC,
				 "LEVEL" ASC)
                COMPRESS NO ALLOW REVERSE SCANS;
   COMMIT WORK ;