ALTER TABLE "EAADMIN"."ALERT_TYPE" ADD COLUMN IS_DQ SMALLINT
;
REORG TABLE EAADMIN.ALERT_TYPE;

INSERT INTO ASN.IBMSNAP_SUBS_COLS (APPLY_QUAL, SET_NAME ,  
 WHOS_ON_FIRST, TARGET_OWNER, TARGET_TABLE, 
 COL_TYPE, TARGET_NAME, IS_KEY, COLNO, EXPRESSION) 
SELECT 'PD_TO_RP_QUAL','RPREP1','S','EAADMIN','ALERT_TYPE','A', 
'IS_DQ',' ', MAX(COLNO + 1),'IS_DQ' 
FROM ASN.IBMSNAP_SUBS_COLS 
 WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='ALERT_TYPE';
