ALTER TABLE "EAADMIN"."ALERT_TYPE" ADD COLUMN IS_DQ SMALLINT
;
ALTER TABLE TRAILSPD_CD.ALERT_TYPE ADD COLUMN IS_DQ SMALLINT; 
ALTER TABLE TRAILSPD_CC.ALERT_TYPE ADD COLUMN IS_DQ SMALLINT; 
REORG TABLE EAADMIN.ALERT_TYPE;
REORG TABLE TRAILSPD_CD.ALERT_TYPE;
REORG TABLE TRAILSPD_CC.ALERT_TYPE;
RUNSTATS ON TABLE EAADMIN.ALERT_TYPE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.ALERT_TYPE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.ALERT_TYPE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;