INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_RP_QUAL', 'RPREP1', 'S', 'EAADMIN', 'SCARLET_RECONCILE', 'RECONCILE_MD5_HEX', 'A', 'N', MAX(COLNO + 1), 'RECONCILE_MD5_HEX' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='SCARLET_RECONCILE';