ALTER TABLE TRAILSPD_CD.SCARLET_RECONCILE ADD RECONCILE_MD5_HEX VARCHAR(50);
ALTER TABLE TRAILSPD_CC.SCARLET_RECONCILE ADD RECONCILE_MD5_HEX VARCHAR(50);
REORG TABLE TRAILSPD_CD.SCARLET_RECONCILE;
REORG TABLE TRAILSPD_CC.SCARLET_RECONCILE;
RUNSTATS ON TABLE TRAILSPD_CD.SCARLET_RECONCILE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.SCARLET_RECONCILE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;