Drop table eaadmin.SOFT_MQT ;
ALTER TABLE "EAADMIN"."SCAN_RECORD" ADD COLUMN SYSPLEX	VARCHAR(8)
;
ALTER TABLE "EAADMIN"."SOFTWARE_LPAR" ADD COLUMN SYSPLEX	VARCHAR(8)
;
REORG TABLE EAADMIN.SOFTWARE_LPAR use TEMPSPACE1
;
REORG TABLE EAADMIN.SCAN_RECORD use TEMPSPACE1
;

create table eaadmin.SOFT_MQT as ( select * from ( SELECT sr.customer_id, ss.id FROM EAADMIN.SOFTWARE_SIGNATURE ss, EAADMIN.SCAN_RECORD sr WHERE ss.scan_record_id = sr.id and sr.n_action ='SAVEUPDATE' and sr.customer_id not in (0, 999999) AND ss.n_action ='UPDATE' ORDER BY sr.customer_id, sr.id, ss.software_id, ss.software_signature_id ASC ) as t) DATA INITIALLY DEFERRED REFRESH DEFERRED ENABLE QUERY OPTIMIZATION MAINTAINED BY SYSTEM IN "TB_MQT" ;


ALTER TABLE "EAADMIN "."SOFT_MQT" DEACTIVATE ROW ACCESS CONTROL;
SET INTEGRITY FOR "EAADMIN"."SOFT_MQT" IMMEDIATE CHECKED;	
GRANT CONTROL ON EAADMIN.SOFT_MQT TO USER EAADMIN		
;