package com.ibm.asset.trails.domain;

// Generated Oct 23, 2009 4:03:54 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MipsId generated by hbm2java
 */
@Embeddable
public class MipsId implements java.io.Serializable {

	private long machineTypeId;
	private String model;
	private String mipsGroup;
	private String vendor;
	private String mipsvendor;

	public MipsId() {
	}

	public MipsId(long machineTypeId, String model, String mipsGroup,
			String vendor, String mipsvendor) {
		this.machineTypeId = machineTypeId;
		this.model = model;
		this.mipsGroup = mipsGroup;
		this.vendor = vendor;
		this.mipsvendor = mipsvendor;
	}

	@Column(name = "MACHINE_TYPE_ID", nullable = false)
	public long getMachineTypeId() {
		return this.machineTypeId;
	}

	public void setMachineTypeId(long machineTypeId) {
		this.machineTypeId = machineTypeId;
	}

	@Column(name = "MODEL", nullable = false, length = 20)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "MIPS_GROUP", nullable = false, length = 3)
	public String getMipsGroup() {
		return this.mipsGroup;
	}

	public void setMipsGroup(String mipsGroup) {
		this.mipsGroup = mipsGroup;
	}

	@Column(name = "VENDOR", nullable = false, length = 10)
	public String getVendor() {
		return this.vendor;
	}

	public void setVendor(String vendor) {
		this.vendor = vendor;
	}

	@Column(name = "MIPSVENDOR", nullable = false, length = 10)
	public String getMipsvendor() {
		return this.mipsvendor;
	}

	public void setMipsvendor(String mipsvendor) {
		this.mipsvendor = mipsvendor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MipsId))
			return false;
		MipsId castOther = (MipsId) other;

		return (this.getMachineTypeId() == castOther.getMachineTypeId())
				&& ((this.getModel() == castOther.getModel()) || (this
						.getModel() != null
						&& castOther.getModel() != null && this.getModel()
						.equals(castOther.getModel())))
				&& ((this.getMipsGroup() == castOther.getMipsGroup()) || (this
						.getMipsGroup() != null
						&& castOther.getMipsGroup() != null && this
						.getMipsGroup().equals(castOther.getMipsGroup())))
				&& ((this.getVendor() == castOther.getVendor()) || (this
						.getVendor() != null
						&& castOther.getVendor() != null && this.getVendor()
						.equals(castOther.getVendor())))
				&& ((this.getMipsvendor() == castOther.getMipsvendor()) || (this
						.getMipsvendor() != null
						&& castOther.getMipsvendor() != null && this
						.getMipsvendor().equals(castOther.getMipsvendor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getMachineTypeId();
		result = 37 * result
				+ (getModel() == null ? 0 : this.getModel().hashCode());
		result = 37 * result
				+ (getMipsGroup() == null ? 0 : this.getMipsGroup().hashCode());
		result = 37 * result
				+ (getVendor() == null ? 0 : this.getVendor().hashCode());
		result = 37
				* result
				+ (getMipsvendor() == null ? 0 : this.getMipsvendor()
						.hashCode());
		return result;
	}

}
