DROP TABLE EAADMIN.CONFIG_RECORD;
------------------------------------------------
-- DDL Statements for Table "EAADMIN "."CONFIG_RECORD"
------------------------------------------------
 

CREATE TABLE "EAADMIN "."CONFIG_RECORD"  (
		  "ID" BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (  
		    START WITH +1  
		    INCREMENT BY +1  
		    MINVALUE +1  
		    MAXVALUE +9223372036854775807  
		    NO CYCLE  
		    CACHE 20  
		    NO ORDER ) , 
			"NAME" VARCHAR(255) NOT NULL,
            "SERIAL_NUMBER" VARCHAR(128) NOT NULL,
            "SOFTWARE_LPAR_ID" BIGINT ,
            "VCPU" INTEGER,
            "VMWARE_CLUSTER" VARCHAR(255),
            "VM_CAN_MIGRATE" SMALLINT,
            "HYPER_THREADING" SMALLINT,
			"BANK_ACCOUNT_ID" BIGINT NOT NULL,
			"COMPUTER_ID" VARCHAR(255) NOT NULL
)   
IN "HARDWARE" INDEX IN "HARDWAREINDEX" ; 


-- DDL Statements for Indexes on Table "EAADMIN "."CONFIG_RECORD"

CREATE UNIQUE INDEX "EAADMIN "."IF1CONFIGIDRECORD" ON "EAADMIN "."CONFIG_RECORD" 
		("BANK_ACCOUNT_ID" ASC,
		 "NAME" ASC,
		 "SERIAL_NUMBER" ASC)		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."CONFIG_RECORD"

CREATE INDEX "EAADMIN "."IF2CONFIGIDRECORD" ON "EAADMIN "."CONFIG_RECORD" 
		("SOFTWARE_LPAR_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
		
-- DDL Statements for Indexes on Table "EAADMIN "."CONFIG_RECORD"

CREATE INDEX "EAADMIN "."IF3CONFIGIDRECORD" ON "EAADMIN "."CONFIG_RECORD" 
		("COMPUTER_ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."CONFIG_RECORD"

CREATE UNIQUE INDEX "EAADMIN "."IN01CFREIDPK" ON "EAADMIN "."CONFIG_RECORD" 
		("ID" ASC)
		
		COMPRESS NO ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "EAADMIN "."CONFIG_RECORD"

ALTER TABLE "EAADMIN "."CONFIG_RECORD" 
	ADD CONSTRAINT "CT01CFREIDPK" PRIMARY KEY
		("ID");
-- DDL Statements for unique constraint on Table "EAADMIN "."CONFIG_RECORD"
 ALTER TABLE "EAADMIN "."CONFIG_RECORD" 
      ADD CONSTRAINT "UNI01CFREIDPK" UNIQUE(NAME, SERIAL_NUMBER, BANK_ACCOUNT_ID);

--------------------------------------------
-- Authorization Statements on Tables/Views 
--------------------------------------------

ALTER TABLE EAADMIN.CONFIG_RECORD DATA CAPTURE CHANGES;
---------- Privilege For CONFIG_RECORD ----------
GRANT REFERENCES ON TABLE "EAADMIN "."CONFIG_RECORD"       TO GROUP "TRAILUPD" ;
GRANT DELETE ON TABLE "EAADMIN "."CONFIG_RECORD"           TO GROUP "TRAILPRD" ;    
GRANT INSERT ON TABLE "EAADMIN "."CONFIG_RECORD"           TO GROUP "TRAILPRD" ;    
GRANT SELECT ON TABLE "EAADMIN "."CONFIG_RECORD"           TO GROUP "TRAILPRD" ;    
GRANT UPDATE ON TABLE "EAADMIN "."CONFIG_RECORD"           TO GROUP "TRAILPRD" ; 

GRANT REFERENCES ON TABLE "EAADMIN "."CONFIG_RECORD"       TO USER eaadmin ;   
GRANT DELETE ON TABLE "EAADMIN "."CONFIG_RECORD"           TO USER eaadmin ;   
GRANT INSERT ON TABLE "EAADMIN "."CONFIG_RECORD"           TO USER eaadmin ;   
GRANT SELECT ON TABLE "EAADMIN "."CONFIG_RECORD"           TO USER eaadmin ;   
GRANT UPDATE ON TABLE "EAADMIN "."CONFIG_RECORD"           TO USER eaadmin ; 



------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CD"."CONFIG_RECORD"
------------------------------------------------
DROP table   TRAILSPD_CD.CONFIG_RECORD                           
;

CREATE TABLE "TRAILSPD_CD"."CONFIG_RECORD"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "ID" BIGINT NOT NULL,
		  "NAME" VARCHAR(255) NOT NULL,
          "SERIAL_NUMBER" VARCHAR(128) NOT NULL,
          "SOFTWARE_LPAR_ID" BIGINT ,
          "VCPU" INTEGER,
          "VMWARE_CLUSTER" VARCHAR(255),
          "VM_CAN_MIGRATE" SMALLINT,
          "HYPER_THREADING" SMALLINT,
	      "BANK_ACCOUNT_ID" BIGINT NOT NULL,
		  "COMPUTER_ID" VARCHAR(255) NOT NULL )   
		 IN TRAILSPD_CD_TABLES  INDEX IN TRAILSPD_CD_INDEX  ; 

ALTER TABLE "TRAILSPD_CD"."CONFIG_RECORD" VOLATILE CARDINALITY;


-- DDL Statements for Indexes on Table "TRAILSPD_CD"."CONFIG_RECORD"

CREATE UNIQUE INDEX "TRAILSPD_CD"."IXCDCONFIG_SCRIPT" ON "TRAILSPD_CD"."CONFIG_RECORD" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CC"."CONFIG_RECORD"
------------------------------------------------
 DROP table   TRAILSPD_CC.CONFIG_RECORD                           
;

CREATE TABLE "TRAILSPD_CC"."CONFIG_RECORD"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "ID" BIGINT NOT NULL,
		  "NAME" VARCHAR(255) NOT NULL,
          "SERIAL_NUMBER" VARCHAR(128) NOT NULL,
          "SOFTWARE_LPAR_ID" BIGINT ,
          "VCPU" INTEGER,
          "VMWARE_CLUSTER" VARCHAR(255),
          "VM_CAN_MIGRATE" SMALLINT,
          "HYPER_THREADING" SMALLINT,
	      "BANK_ACCOUNT_ID" BIGINT NOT NULL,
		  "COMPUTER_ID" VARCHAR(255) NOT NULL )   
		 IN TRAILSPD_CD_TABLES  INDEX IN TRAILSPD_CD_INDEX  ; 

ALTER TABLE "TRAILSPD_CC"."CONFIG_RECORD" VOLATILE CARDINALITY;



-- DDL Statements for Indexes on Table "TRAILSPD_CC"."CONFIG_RECORD"

CREATE UNIQUE INDEX "TRAILSPD_CC"."IXCCCONFIG_SCRIPT" ON "TRAILSPD_CC"."CONFIG_RECORD" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;

		
----------------------------------------------------------------------
-- DDL Statements for registering CONFIG_RECORD TRAILSPD_CD
----------------------------------------------------------------------
DELETE FROM ASN.IBMSNAP_REGISTER where SOURCE_OWNER='EAADMIN' 
and SOURCE_TABLE='CONFIG_RECORD' 
and CD_OWNER='TRAILSPD_CD' 
and CD_TABLE='CONFIG_RECORD' 
and PHYS_CHANGE_OWNER='TRAILSPD_CD' 
and PHYS_CHANGE_TABLE='CONFIG_RECORD'
;
INSERT INTO ASN.IBMSNAP_REGISTER (SOURCE_OWNER, SOURCE_TABLE,
SOURCE_VIEW_QUAL, GLOBAL_RECORD, SOURCE_STRUCTURE, SOURCE_CONDENSED,
SOURCE_COMPLETE, CD_OWNER, CD_TABLE, PHYS_CHANGE_OWNER, 
PHYS_CHANGE_TABLE, CD_OLD_SYNCHPOINT, CD_NEW_SYNCHPOINT, 
DISABLE_REFRESH, CCD_OWNER, CCD_TABLE, CCD_OLD_SYNCHPOINT, 
SYNCHPOINT, SYNCHTIME, CCD_CONDENSED, CCD_COMPLETE, ARCH_LEVEL, 
DESCRIPTION, BEFORE_IMG_PREFIX, CONFLICT_LEVEL, 
CHG_UPD_TO_DEL_INS, CHGONLY, RECAPTURE, OPTION_FLAGS,
STOP_ON_ERROR, STATE, STATE_INFO ) VALUES(
'EAADMIN',
'CONFIG_RECORD',
0,
'N',
1,
'Y',
'Y',
'TRAILSPD_CD',
'CONFIG_RECORD',
'TRAILSPD_CD',
'CONFIG_RECORD',
null,
null,
0,
null,
null,
null,
null,
null,
null,
null,
'0801',
null,
null,
'0',
'N',
'N',
'Y',
'NNNN',
'Y',
'I',
null );
----------------------------------------------------------------------
-- DDL Statements for registering CONFIG_RECORD for TRAILSPD_CC
----------------------------------------------------------------------
DELETE FROM NEWASN.IBMSNAP_REGISTER where SOURCE_OWNER='EAADMIN' 
and SOURCE_TABLE='CONFIG_RECORD' 
and CD_OWNER='TRAILSPD_CC' 
and CD_TABLE='CONFIG_RECORD' 
and PHYS_CHANGE_OWNER='TRAILSPD_CC' 
and PHYS_CHANGE_TABLE='CONFIG_RECORD'
;
INSERT INTO NEWASN.IBMSNAP_REGISTER (SOURCE_OWNER, SOURCE_TABLE,
SOURCE_VIEW_QUAL, GLOBAL_RECORD, SOURCE_STRUCTURE, SOURCE_CONDENSED,
SOURCE_COMPLETE, CD_OWNER, CD_TABLE, PHYS_CHANGE_OWNER, 
PHYS_CHANGE_TABLE, CD_OLD_SYNCHPOINT, CD_NEW_SYNCHPOINT, 
DISABLE_REFRESH, CCD_OWNER, CCD_TABLE, CCD_OLD_SYNCHPOINT, 
SYNCHPOINT, SYNCHTIME, CCD_CONDENSED, CCD_COMPLETE, ARCH_LEVEL, 
DESCRIPTION, BEFORE_IMG_PREFIX, CONFLICT_LEVEL, 
CHG_UPD_TO_DEL_INS, CHGONLY, RECAPTURE, OPTION_FLAGS,
STOP_ON_ERROR, STATE, STATE_INFO ) VALUES(
'EAADMIN',
'CONFIG_RECORD',
0,
'N',
1,
'Y',
'Y',
'TRAILSPD_CC',
'CONFIG_RECORD',
'TRAILSPD_CC',
'CONFIG_RECORD',
null,
null,
0,
null,
null,
null,
null,
null,
null,
null,
'0801',
null,
null,
'0',
'N',
'N',
'Y',
'NNNN',
'Y',
'I',
null );

-----------------------------------------------------------------------------
-- DDL Statements for registering  NEWASN PrunControl CONFIG_RECORD for PD_TO_RP_QUAL
-----------------------------------------------------------------------------
DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE APPLY_QUAL = 'PD_TO_RP_QUAL' 
and SET_NAME = 'RPREP1'
and CNTL_SERVER = 'TRAILSRP'
and SOURCE_OWNER ='EAADMIN'
and SOURCE_TABLE = 'CONFIG_RECORD'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'CONFIG_RECORD'
and TARGET_SERVER = 'TRAILSRP'
and PHYS_CHANGE_OWNER = 'TRAILSPD_CC'
and PHYS_CHANGE_TABLE = 'CONFIG_RECORD'
;
INSERT INTO NEWASN.IBMSNAP_PRUNCNTL ( 
 APPLY_QUAL, SET_NAME, CNTL_SERVER, CNTL_ALIAS, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_SERVER, 
 TARGET_STRUCTURE, MAP_ID, 
 PHYS_CHANGE_OWNER, PHYS_CHANGE_TABLE 
 ) SELECT 
'PD_TO_RP_QUAL',
 'RPREP1',
 'TRAILSRP',
 'TRAILSRP',
 'EAADMIN',
 'CONFIG_RECORD',
 0,
 'EAADMIN',
 'CONFIG_RECORD',
 'TRAILSRP',
 8,
 coalesce ( char(max(INT(MAP_ID)+1) ), '0' ),
 'TRAILSPD_CC',
 'CONFIG_RECORD' FROM NEWASN.IBMSNAP_PRUNCNTL;
 -----------------------------------------------------------------------------
-- DDL Statements for registering ASN PrunControl CONFIG_RECORD for PD_TO_ST_QUAL
-----------------------------------------------------------------------------
DELETE FROM ASN.IBMSNAP_PRUNCNTL WHERE APPLY_QUAL = 'PD_TO_ST_QUAL' 
and SET_NAME = 'STREP1'
and CNTL_SERVER = 'TRAILSST'
and SOURCE_OWNER ='EAADMIN'
and SOURCE_TABLE = 'CONFIG_RECORD'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'CONFIG_RECORD'
and TARGET_SERVER = 'TRAILSST'
and PHYS_CHANGE_OWNER = 'TRAILSPD_CD'
and PHYS_CHANGE_TABLE = 'CONFIG_RECORD'
;
 INSERT INTO ASN.IBMSNAP_PRUNCNTL ( 
 APPLY_QUAL, SET_NAME, CNTL_SERVER, CNTL_ALIAS, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_SERVER, 
 TARGET_STRUCTURE, MAP_ID, 
 PHYS_CHANGE_OWNER, PHYS_CHANGE_TABLE 
 ) SELECT 
'PD_TO_ST_QUAL',
 'STREP1',
 'TRAILSST',
 'TRAILSST',
 'EAADMIN',
 'CONFIG_RECORD',
 0,
 'EAADMIN',
 'CONFIG_RECORD',
 'TRAILSST',
 8,
 coalesce ( char(max(INT(MAP_ID)+1) ), '0' ),
 'TRAILSPD_CD',
 'CONFIG_RECORD' FROM ASN.IBMSNAP_PRUNCNTL;


COMMIT ;


