package IBM::Schema::CNDB::CndbMldbView;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("CNDB_MLDB_VIEW");
__PACKAGE__->add_columns(
  "customer_number",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "sector_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "industry_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "customer_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 64 },
  "pod_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "app_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "customer_type_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "dpe_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "dpe_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "pool_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "pool_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cno_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cno_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "fa_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "fa_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "fa_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tower",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sub_group",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "division",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "state",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "country",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "postal_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address_title",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address1",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "city",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "central_recv_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "dock_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "dock_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "taxable_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "exemption_reason",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "charge_to_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "lpid",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "major",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "function",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "igf_customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "branch_office_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "maint_only",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_only_cn",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sign_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "contract_start_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "contract_end_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "contract_value",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_hw_transfers",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_transfers_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_transfers",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_transfers_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "field",
  { data_type => "VARCHAR", is_nullable => 0, size => 0 },
  "claim_work_item",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "claim_activity_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "status",
  { data_type => "VARCHAR", is_nullable => 0, size => 32 },
  "active_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "cnc_comments",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "validation_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "validated_by",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "abbr_customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "transition_team_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "transition_team_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "focal_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "focal_asset_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "legacy_area",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "sw_asset_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "hw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "hw_asset_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "hostname_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tme_object_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "tlm_deployment_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "account_number",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "acct_hw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "acct_hw_asset_serial",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "delegate_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 256 },
);


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:37
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:Vx93UTyn7/DlODYQdZLKVw


# You can replace this text with custom content, and it will be preserved on regeneration
1;
