package IBM::Schema::CNDB::CustomerRequestData;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("CUSTOMER_REQUEST_DATA");
__PACKAGE__->add_columns(
  "customer_request_data_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "customer_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "pod",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "abbr_customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sector",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "industry",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "dpe_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "dpe_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "fa_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "fa_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sign_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "contract_start_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "contract_end_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "contract_value",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_orders",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_orders",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_transfer",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_transfer_count",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_transfer",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_transfer_count",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "transition_team_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "transition_team_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "focal_assset_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "focal_assset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "legacy_area",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_asset_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "hw_asset_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "hw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "hostname_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tme_object_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "tlm_deploy",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "asset_tools_billing_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "maint_only",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_only_cn",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "comment",
  { data_type => "VARCHAR", is_nullable => 1, size => 128 },
  "hs_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "hw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "sw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "inv_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "account_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_date",
  { data_type => "DATE", is_nullable => 1, size => 10 },
  "validated_by",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "sw_license_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "sw_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "hw_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "geography",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "tier",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "transition_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "transition_exit_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "country_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 2 },
  "sw_tracking",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "sw_compliance_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "sw_financial_responsibility",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "sw_financial_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "om_org",
  { data_type => "VARCHAR", is_nullable => 1, size => 128 },
  "om_business_level",
  { data_type => "VARCHAR", is_nullable => 1, size => 128 },
  "om_sid",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "customer_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "customer_suffix",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "scan_validity",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
);
__PACKAGE__->set_primary_key("customer_request_data_id");


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:39
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:BEtflfCenaMeYWwihTPWAQ


# You can replace this text with custom content, and it will be preserved on regeneration
1;
