package IBM::Schema::CNDB::CndbDownloadAccountView;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("CNDB_DOWNLOAD_ACCOUNT_VIEW");
__PACKAGE__->add_columns(
  "status",
  { data_type => "VARCHAR", is_nullable => 0, size => 32 },
  "country_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sector_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "industry_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "customer_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 64 },
  "pod_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "customer_type_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "dpe_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "fa_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "maint_only",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_only_cn",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sign_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "contract_start_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "contract_end_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "contract_value",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_hw_transfer",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_transfer_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_transfer",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_transfer_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "abbr_customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "aa_transition_team_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "aa_focal_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "aa_hostname_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "aa_tme_object_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "aa_tlm_deploy",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "aa_hw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_sw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_inv_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_sw_license_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_sw_tracking",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_sw_compliance_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_sw_financial_responsibility",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "aa_sw_financial_mgmt",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_hw_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_sw_support",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_tier",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "aa_transition_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "aa_transition_exit_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "aa_account_hw_contact_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "aa_account_sw_contact_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "validation_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "validatied_by",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "om_org",
  { data_type => "VARCHAR", is_nullable => 1, size => 128 },
  "om_business_level",
  { data_type => "VARCHAR", is_nullable => 1, size => 128 },
  "om_sid",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "customer_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "customer_suffix",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "scan_validity",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "account_number",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
);


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:36
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:kiw1w4x0S962TuOqKhiDig


# You can replace this text with custom content, and it will be preserved on regeneration
1;
