ALTER TABLE "EAADMIN"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;

REORG TABLE EAADMIN.SCHEDULE_F_H;

 
