ALTER TABLE "EAADMIN"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
ALTER TABLE "TRAILSPD_CD"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "TRAILSPD_CD"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "TRAILSPD_CD"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
ALTER TABLE "TRAILSPD_CC"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "TRAILSPD_CC"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "TRAILSPD_CC"."SCHEDULE_F_H" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
REORG TABLE EAADMIN.SCHEDULE_F_H;
REORG TABLE TRAILSPD_CD.SCHEDULE_F_H;
REORG TABLE TRAILSPD_CC.SCHEDULE_F_H;
RUNSTATS ON TABLE EAADMIN.SCHEDULE_F_H ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.SCHEDULE_F_H ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.SCHEDULE_F_H ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;