DROP INDEX "EAADMIN "."IF1INDUSTRY"
;

ALTER TABLE "EAADMIN "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;
ALTER TABLE "TRAILSPD_CC "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;
ALTER TABLE "TRAILSPD_CD "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;
REORG TABLE EAADMIN.INDUSTRY;
REORG TABLE TRAILSPD_CD.INDUSTRY;
REORG TABLE TRAILSPD_CC.INDUSTRY;

ALTER TABLE "EAADMIN "."CUSTOMER" ADD COLUMN "SECTOR_ID" BIGINT
;
ALTER TABLE "TRAILSPD_CC "."CUSTOMER" ADD COLUMN "SECTOR_ID" BIGINT
;
ALTER TABLE "TRAILSPD_CD "."CUSTOMER" ADD COLUMN "SECTOR_ID" BIGINT
;
REORG TABLE EAADMIN.CUSTOMER;
REORG TABLE TRAILSPD_CD.CUSTOMER;
REORG TABLE TRAILSPD_CC.CUSTOMER;

RUNSTATS ON TABLE EAADMIN.INDUSTRY ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.INDUSTRY ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.INDUSTRY ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE EAADMIN.CUSTOMER ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.CUSTOMER ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.CUSTOMER ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;