DROP INDEX "EAADMIN "."IF1INDUSTRY"
;

ALTER TABLE "EAADMIN "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;
ALTER TABLE "TRAILSPD_CC "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;
ALTER TABLE "TRAILSPD_CD "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;

ALTER TABLE "EAADMIN "."CUSTOMER" ADD "SECTOR_ID" BIGINT
;
ALTER TABLE "TRAILSPD_CC "."CUSTOMER" ADD "SECTOR_ID" BIGINT
;
ALTER TABLE "TRAILSPD_CD "."CUSTOMER" ADD "SECTOR_ID" BIGINT
;

