DROP INDEX "EAADMIN "."IF1INDUSTRY"
;

ALTER TABLE "EAADMIN "."INDUSTRY" DROP COLUMN "SECTOR_ID"
;

ALTER TABLE "EAADMIN "."CUSTOMER" ADD COLUMN "SECTOR_ID" BIGINT
;
REORG TABLE EAADMIN.INDUSTRY;
REORG TABLE EAADMIN.CUSTOMER;

DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
and SET_NAME = 'STREP1'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'INDUSTRY'
and TARGET_NAME = 'SECTOR_ID'
and EXPRESSION = 'SECTOR_ID'
;

INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_ST_QUAL', 'STREP1', 'S', 'EAADMIN', 'CUSTOMER', 'SECTOR_ID', 'A', 'N', MAX(COLNO + 1), 'SECTOR_ID' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_ST_QUAL' AND SET_NAME='STREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='CUSTOMER';