DROP TABLE EAADMIN.MQT_ALERT_REPORT;
DROP TABLE eaadmin.v_installed_software_mqt;
alter table eaadmin.software_lpar alter column OS_INST_DATE set data type TIMESTAMP;
alter table trailspd_cc.software_lpar alter column OS_INST_DATE set data type TIMESTAMP;
alter table trailspd_cd.software_lpar alter column OS_INST_DATE set data type TIMESTAMP;
reorg table eaadmin.software_lpar ;
reorg table trailspd_cc.software_lpar ;
reorg table trailspd_cd.software_lpar ;
RUNSTATS ON TABLE EAADMIN.software_lpar ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.software_lpar ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.software_lpar ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;

ALTER TABLE EAADMIN.HARDWARE_LPAR ADD COLUMN VCPU DECIMAL(4 , 0)
;
ALTER TABLE TRAILSPD_CD.HARDWARE_LPAR ADD COLUMN VCPU DECIMAL(4 , 0); 
ALTER TABLE TRAILSPD_CC.HARDWARE_LPAR ADD COLUMN VCPU DECIMAL(4 , 0); 
REORG TABLE EAADMIN.HARDWARE_LPAR ;
REORG TABLE TRAILSPD_CD.HARDWARE_LPAR ;
REORG TABLE TRAILSPD_CC.HARDWARE_LPAR ;
RUNSTATS ON TABLE EAADMIN.HARDWARE_LPAR ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.HARDWARE_LPAR ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.HARDWARE_LPAR ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;


CREATE SUMMARY TABLE EAADMIN.MQT_ALERT_REPORT
(
   ID,
   CUSTOMER_ID,
   DISPLAY_NAME,
   ASSET_TYPE,
   RECORD_TIME,
   ASSIGNED,
   RED,
   YELLOW,
   GREEN,
   RED91,
   RED121,
   RED151,
   RED181,
   RED366,
   ASSET_TOTAL
)
AS
(
   SELECT
   ID ,
   CUSTOMER_ID ,
   DISPLAY_NAME ,
   ASSET_TYPE ,
   CURRENT TIMESTAMP ,
   ASSIGNED ,
   RED ,
   YELLOW ,
   GREEN ,
   RED91 ,
   RED121 ,
   RED151 ,
   RED181 ,
   RED366 ,
   ASSET_TOTAL
   FROM
   (
      SELECT
      'HARDWARE' || CASE WHEN H.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1a: HW WITH HOSTNAME' AS DISPLAY_NAME ,
      CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AH.REMOTE_USER IS NULL THEN NULL WHEN AH.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM(CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) > 365 THEN 1 ELSE 0 END) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END) AS RED91 ,
      SUM( CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.HARDWARE H ON H.CUSTOMER_ID = C.CUSTOMER_ID AND H.STATUS = 'ACTIVE' AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_HARDWARE AH ON AH.HARDWARE_ID = H.ID AND AH.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'HARDWARE' || CASE WHEN H.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'HARDWARE' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1a: HW WITH HOSTNAME' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HARDWARE' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1a: HW WITH HOSTNAME' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HW_LPAR' || CASE WHEN HL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2a: HW LPAR WITH SW LPAR' AS DISPLAY_NAME ,
      CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AHL.REMOTE_USER IS NULL THEN NULL WHEN AHL.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      SUM( CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' AND HL.LPAR_STATUS != 'HWCOUNT' THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C JOIN
      EAADMIN.HARDWARE_LPAR HL ON HL.CUSTOMER_ID = C.CUSTOMER_ID AND HL.STATUS = 'ACTIVE' 
										AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE'
      JOIN EAADMIN.HARDWARE H ON H.ID = HL.HARDWARE_ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID LEFT OUTER
      JOIN EAADMIN.ALERT_HW_LPAR AHL ON AHL.HARDWARE_LPAR_ID = HL.ID AND AHL.OPEN = 1
      GROUP BY 'HW_LPAR' || CASE WHEN HL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'HW_LPAR' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2a: HW LPAR WITH SW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HW_LPAR' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2a: HW LPAR WITH SW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SW_LPAR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2b: SW LPAR WITH HW LPAR' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ASL.REMOTE_USER IS NULL THEN NULL WHEN ASL.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(SL.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID 
				AND SL.STATUS = 'ACTIVE' AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_SW_LPAR ASL ON SL.ID = ASL.SOFTWARE_LPAR_ID AND ASL.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'SW_LPAR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SW_LPAR' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2b: SW LPAR WITH HW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SW_LPAR' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2b: SW LPAR WITH HW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'EXP_SCAN' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2c: UNEXPIRED SW LPAR' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AES.REMOTE_USER IS NULL THEN NULL WHEN AES.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 0 AND 45 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(SL.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C JOIN EAADMIN.SOFTWARE_LPAR SL ON C.CUSTOMER_ID = SL.CUSTOMER_ID
			AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' AND SL.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_EXPIRED_SCAN AES ON AES.SOFTWARE_LPAR_ID = SL.ID AND AES.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'EXP_SCAN' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'EXP_SCAN' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2c: UNEXPIRED SW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'EXP_SCAN' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM2c: UNEXPIRED SW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWISCOPE' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM3: SW INSTANCES WITH DEFINED CONTRACT SCOPE' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ( AUS.REMOTE_USER IS NULL ) THEN NULL
				WHEN ( AUS.REMOTE_USER != 'STAGING' ) THEN 1 ELSE 0 END ) AS ASSIGNED ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 90 ) THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 46 AND 90) THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) < 46) THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 365) THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 181 AND 365 ) THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 151 AND 180 ) THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 121 AND 150 ) THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 91 AND 120 ) THEN 1 ELSE 0 END ) AS RED91 ,
      SUM( CASE WHEN ( PI.LICENSABLE = 1 ) THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' AND SL.STATUS = 'ACTIVE'
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID AND HL.STATUS = 'ACTIVE' AND HL.LPAR_STATUS != 'HWCOUNT'
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID AND H.STATUS = 'ACTIVE'
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      JOIN EAADMIN.INSTALLED_SOFTWARE IS ON SL.ID = IS.SOFTWARE_LPAR_ID AND IS.STATUS = 'ACTIVE'
      JOIN EAADMIN.PRODUCT_INFO PI ON IS.SOFTWARE_ID = PI.ID LEFT OUTER
      JOIN EAADMIN.ALERT_UNLICENSED_SW AUS ON AUS.INSTALLED_SOFTWARE_ID = IS.ID AND AUS.TYPE = 'SCOPE' AND AUS.OPEN = 1
      GROUP BY 'SWISCOPE' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SWISCOPE' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM3: SW INSTANCES WITH DEFINED CONTRACT SCOPE' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWISCOPE' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM3: SW INSTANCES WITH DEFINED CONTRACT SCOPE' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWIBM' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4a: IBM SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ( AUS.REMOTE_USER IS NULL ) THEN NULL
      		 WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
			 WHEN ( AUS.REMOTE_USER != 'STAGING' ) THEN 1 ELSE 0 END ) AS ASSIGNED ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0 
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 90 ) THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 46 AND 90) THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) < 46) THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 365) THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 181 AND 365 ) THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 151 AND 180 ) THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 121 AND 150 ) THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 91 AND 120 ) THEN 1 ELSE 0 END ) AS RED91 ,
      SUM( CASE WHEN ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) != 0 ) THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' AND SL.STATUS = 'ACTIVE'
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID AND HL.STATUS = 'ACTIVE' AND HL.LPAR_STATUS != 'HWCOUNT'
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID AND H.STATUS = 'ACTIVE'
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      JOIN EAADMIN.INSTALLED_SOFTWARE IS ON SL.ID = IS.SOFTWARE_LPAR_ID AND IS.STATUS = 'ACTIVE'
      LEFT OUTER JOIN EAADMIN.PRODUCT P ON P.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.MAINFRAME_VERSION MV ON MV.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.MAINFRAME_FEATURE MF ON MF.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.MAINFRAME_VERSION MFV ON MFV.ID = MF.VERSION_ID
      LEFT OUTER JOIN EAADMIN.IBM_BRAND IB ON IB.MANUFACTURER_ID = COALESCE ( P.MANUFACTURER_ID, MV.MANUFACTURER_ID, MFV.MANUFACTURER_ID )
      LEFT OUTER JOIN EAADMIN.SOFTWARE_ITEM SI ON SI.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF0 ON ( ( SF0.SOFTWARE_NAME = SI.NAME OR SF0.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF0.CUSTOMER_ID = SL.CUSTOMER_ID
					AND SF0.STATUS_ID = 2 AND SF0.LEVEL = 'PRODUCT' )
	  LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF2 ON ( ( SF2.SOFTWARE_NAME = SI.NAME OR SF2.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF2.CUSTOMER_ID = SL.CUSTOMER_ID
	 				AND SF2.STATUS_ID = 2 AND SF2.LEVEL = 'HWOWNER' AND H.OWNER = SF2.HW_OWNER )
	  LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF4 ON ( ( SF4.SOFTWARE_NAME = SI.NAME OR SF4.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF4.CUSTOMER_ID = SL.CUSTOMER_ID
	 				AND SF4.STATUS_ID = 2 AND SF4.LEVEL = 'HWBOX' AND H.SERIAL = SF4.SERIAL AND MT.NAME = SF4.MACHINE_TYPE )
      LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF6 ON ( ( SF6.SOFTWARE_NAME = SI.NAME OR SF6.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF6.CUSTOMER_ID = SL.CUSTOMER_ID
					AND SF6.STATUS_ID = 2 AND SF6.LEVEL = 'HOSTNAME' AND SF6.HOSTNAME = SL.NAME )
      LEFT OUTER JOIN EAADMIN.ALERT_UNLICENSED_SW AUS ON AUS.INSTALLED_SOFTWARE_ID = IS.ID AND AUS.TYPE = 'IBM' AND AUS.OPEN = 1
      LEFT OUTER JOIN EAADMIN.REPORT_DELIVERY_TRACKING RDT ON RDT.CUSTOMER_ID = SL.CUSTOMER_ID
      WHERE IB.ID IS NOT NULL
      GROUP BY 'SWIBM' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SWIBM' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4a: IBM SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWIBM' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4a: IBM SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWISVPR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4b: PRIORITY ISV SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ( AUS.REMOTE_USER IS NULL ) THEN NULL
      		 WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
			 WHEN ( AUS.REMOTE_USER != 'STAGING' ) THEN 1 ELSE 0 END ) AS ASSIGNED ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0 
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 90 ) THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 46 AND 90) THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) < 46) THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 365) THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 181 AND 365 ) THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 151 AND 180 ) THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 121 AND 150 ) THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 91 AND 120 ) THEN 1 ELSE 0 END ) AS RED91 ,
      SUM( CASE WHEN ( ( PIS.ID IS NOT NULL ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) != 0 ) ) THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' AND SL.STATUS = 'ACTIVE'
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID AND HL.STATUS = 'ACTIVE' AND HL.LPAR_STATUS != 'HWCOUNT'
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID AND H.STATUS = 'ACTIVE'
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      JOIN EAADMIN.INSTALLED_SOFTWARE IS ON SL.ID = IS.SOFTWARE_LPAR_ID AND IS.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.PRODUCT P ON P.ID = IS.SOFTWARE_ID LEFT OUTER
      JOIN EAADMIN.MAINFRAME_VERSION MV ON MV.ID = IS.SOFTWARE_ID LEFT OUTER
      JOIN EAADMIN.MAINFRAME_FEATURE MF ON MF.ID = IS.SOFTWARE_ID LEFT OUTER
      JOIN EAADMIN.MAINFRAME_VERSION MFV ON MFV.ID = MF.VERSION_ID LEFT OUTER
      JOIN EAADMIN.PRIORITY_ISV_SW PIS ON PIS.MANUFACTURER_ID = COALESCE ( P.MANUFACTURER_ID, MV.MANUFACTURER_ID, MFV.MANUFACTURER_ID )
      LEFT OUTER JOIN EAADMIN.SOFTWARE_ITEM SI ON SI.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF0 ON ( ( SF0.SOFTWARE_NAME = SI.NAME OR SF0.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF0.CUSTOMER_ID = SL.CUSTOMER_ID
					AND SF0.STATUS_ID = 2 AND SF0.LEVEL = 'PRODUCT' )
      LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF2 ON ( ( SF2.SOFTWARE_NAME = SI.NAME OR SF2.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF2.CUSTOMER_ID = SL.CUSTOMER_ID
	 				AND SF2.STATUS_ID = 2 AND SF2.LEVEL = 'HWOWNER' AND H.OWNER = SF2.HW_OWNER )
	  LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF4 ON ( ( SF4.SOFTWARE_NAME = SI.NAME OR SF4.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF4.CUSTOMER_ID = SL.CUSTOMER_ID
	 				AND SF4.STATUS_ID = 2 AND SF4.LEVEL = 'HWBOX' AND H.SERIAL = SF4.SERIAL AND MT.NAME = SF4.MACHINE_TYPE )
	  LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF6 ON ( ( SF6.SOFTWARE_NAME = SI.NAME OR SF6.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF6.CUSTOMER_ID = SL.CUSTOMER_ID
					AND SF6.STATUS_ID = 2 AND SF6.LEVEL = 'HOSTNAME' AND SF6.HOSTNAME = SL.NAME )
      JOIN EAADMIN.ALERT_UNLICENSED_SW AUS ON AUS.INSTALLED_SOFTWARE_ID = IS.ID AND AUS.TYPE = 'ISVPRIO' AND AUS.OPEN = 1
      LEFT OUTER JOIN EAADMIN.REPORT_DELIVERY_TRACKING RDT ON RDT.CUSTOMER_ID = SL.CUSTOMER_ID
      WHERE ( ( ( PIS.LEVEL = 'GLOBAL' ) AND ( PIS.CUSTOMER_ID IS NULL ) ) OR
			  ( ( PIS.LEVEL = 'ACCOUNT' ) AND ( PIS.CUSTOMER_ID = SL.CUSTOMER_ID ) ) )
      GROUP BY 'SWISVPR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SWISVPR' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4b: PRIORITY ISV SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWISVPR' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4b: PRIORITY ISV SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL      
      SELECT
      'SWISVNPR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4c: ISV SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ( AUS.REMOTE_USER IS NULL ) THEN NULL
      		 WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
			 WHEN ( AUS.REMOTE_USER != 'STAGING' ) THEN 1 ELSE 0 END ) AS ASSIGNED ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0 
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 90 ) THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 46 AND 90) THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) < 46) THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 365) THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 181 AND 365 ) THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 151 AND 180 ) THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 121 AND 150 ) THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN ( ( RDT.NEXT_DELIVERY IS NOT NULL ) AND ( RDT.NEXT_DELIVERY > CURRENT TIMESTAMP ) AND ( COALESCE ( SF6.SW_FINANCIAL_RESP, SF4.SW_FINANCIAL_RESP, SF2.SW_FINANCIAL_RESP, SF0.SW_FINANCIAL_RESP, 'BOOO' ) = 'CUSTO' ) AND ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) = 2 ) ) THEN 0
      		 WHEN ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 91 AND 120 ) THEN 1 ELSE 0 END ) AS RED91 ,
      SUM( CASE WHEN ( COALESCE ( SF6.SCOPE_ID, SF4.SCOPE_ID, SF2.SCOPE_ID, SF0.SCOPE_ID, 0 ) != 0 ) THEN 1 ELSE 0 END ) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID AND C.SW_LICENSE_MGMT = 'YES' AND C.STATUS = 'ACTIVE' AND SL.STATUS = 'ACTIVE'
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID AND HL.STATUS = 'ACTIVE' AND HL.LPAR_STATUS != 'HWCOUNT'
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID AND H.STATUS = 'ACTIVE'
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      JOIN EAADMIN.INSTALLED_SOFTWARE IS ON SL.ID = IS.SOFTWARE_LPAR_ID AND IS.STATUS = 'ACTIVE'
      LEFT OUTER JOIN EAADMIN.PRODUCT P ON P.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.MAINFRAME_VERSION MV ON MV.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.MAINFRAME_FEATURE MF ON MF.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.MAINFRAME_VERSION MFV ON MFV.ID = MF.VERSION_ID
      LEFT OUTER JOIN EAADMIN.IBM_BRAND IB ON IB.MANUFACTURER_ID = COALESCE ( P.MANUFACTURER_ID, MV.MANUFACTURER_ID, MFV.MANUFACTURER_ID )
      LEFT OUTER JOIN EAADMIN.PRIORITY_ISV_SW PIS ON PIS.MANUFACTURER_ID = COALESCE ( P.MANUFACTURER_ID, MV.MANUFACTURER_ID, MFV.MANUFACTURER_ID )
				AND ( ( ( PIS.LEVEL = 'GLOBAL' ) AND ( PIS.CUSTOMER_ID IS NULL ) ) OR
			  ( ( PIS.LEVEL = 'ACCOUNT' ) AND ( PIS.CUSTOMER_ID = SL.CUSTOMER_ID ) ) )
      LEFT OUTER JOIN EAADMIN.SOFTWARE_ITEM SI ON SI.ID = IS.SOFTWARE_ID
      LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF0 ON ( ( SF0.SOFTWARE_NAME = SI.NAME OR SF0.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF0.CUSTOMER_ID = SL.CUSTOMER_ID
					AND SF0.STATUS_ID = 2 AND SF0.LEVEL = 'PRODUCT' )
      LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF2 ON ( ( SF2.SOFTWARE_NAME = SI.NAME OR SF2.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF2.CUSTOMER_ID = SL.CUSTOMER_ID
	 				AND SF2.STATUS_ID = 2 AND SF2.LEVEL = 'HWOWNER' AND H.OWNER = SF2.HW_OWNER )
	  LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF4 ON ( ( SF4.SOFTWARE_NAME = SI.NAME OR SF4.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF4.CUSTOMER_ID = SL.CUSTOMER_ID
	 				AND SF4.STATUS_ID = 2 AND SF4.LEVEL = 'HWBOX' AND H.SERIAL = SF4.SERIAL AND MT.NAME = SF4.MACHINE_TYPE )
	  LEFT OUTER JOIN EAADMIN.SCHEDULE_F SF6 ON ( ( SF6.SOFTWARE_NAME = SI.NAME OR SF6.SOFTWARE_ID = IS.SOFTWARE_ID ) AND SF6.CUSTOMER_ID = SL.CUSTOMER_ID
					AND SF6.STATUS_ID = 2 AND SF6.LEVEL = 'HOSTNAME' AND SF6.HOSTNAME = SL.NAME )
      LEFT OUTER JOIN EAADMIN.ALERT_UNLICENSED_SW AUS ON AUS.INSTALLED_SOFTWARE_ID = IS.ID AND AUS.TYPE IN ( 'ISV', 'ISVNOPRIO' ) AND AUS.OPEN = 1
      LEFT OUTER JOIN EAADMIN.REPORT_DELIVERY_TRACKING RDT ON RDT.CUSTOMER_ID = SL.CUSTOMER_ID
      WHERE ( ( IB.ID IS NULL ) AND ( PIS.ID IS NULL ) )
      GROUP BY 'SWISVNPR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN '_NON-WORKSTATION_' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN '_NON-WORKSTATION_' ELSE '_WORKSTATION_' END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SWISVNPR' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4c: ISV SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SWISVNPR' || '_WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM4c: ISV SW INSTANCES REVIEWED' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HWCFGDTA' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1b: HW BOX CRITICAL CONFIGURATION DATA POPULATED' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      SUM( CASE WHEN AHC.REMOTE_USER IS NULL THEN NULL WHEN AHC.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM(CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) > 365 THEN 1 ELSE 0 END) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END) AS RED91 ,
      SUM( CASE WHEN ( H.HARDWARE_STATUS = 'ACTIVE' AND MT.TYPE != 'WORKSTATION' ) THEN 1 ELSE 0 END )
      AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      JOIN ( SELECT DISTINCT HARDWARE_ID,CUSTOMER_ID FROM EAADMIN.HARDWARE_LPAR WHERE STATUS = 'ACTIVE' AND LPAR_STATUS = 'ACTIVE' ) X
					ON X.CUSTOMER_ID = C.CUSTOMER_ID AND C.STATUS = 'ACTIVE' AND C.SW_LICENSE_MGMT = 'YES'
      JOIN EAADMIN.HARDWARE H ON X.HARDWARE_ID = H.ID AND H.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_HARDWARE_CFGDATA AHC ON AHC.HARDWARE_ID = H.ID  AND AHC.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      GROUP BY 'HWCFGDTA' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID
      UNION
      ALL
      SELECT
      'HWCFGDTA' || '_NON-WORKSTATION_' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1b: HW BOX CRITICAL CONFIGURATION DATA POPULATED' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
   )
   AS T
)
DATA INITIALLY DEFERRED REFRESH DEFERRED ENABLE QUERY OPTIMIZATION MAINTAINED BY SYSTEM IN "MISC" INDEX IN "MISCINDEX"
;

ALTER TABLE "EAADMIN "."MQT_ALERT_REPORT" DEACTIVATE ROW ACCESS CONTROL;		
			
SET INTEGRITY FOR "EAADMIN"."MQT_ALERT_REPORT" IMMEDIATE CHECKED;		
		
GRANT CONTROL ON EAADMIN.MQT_ALERT_REPORT TO USER EAADMIN		
;		
GRANT REFERENCES ON EAADMIN.MQT_ALERT_REPORT TO GROUP TRAILPRD		
;		
GRANT SELECT ON EAADMIN.MQT_ALERT_REPORT TO GROUP TRAILPRD		
;		
GRANT REFERENCES ON EAADMIN.MQT_ALERT_REPORT TO GROUP TRAILUPD		
;		
GRANT SELECT ON EAADMIN.MQT_ALERT_REPORT TO GROUP TRAILUPD
;

create summary table eaadmin.v_installed_software_mqt as (select a.id as software_lpar_id ,a.customer_id as customer_id ,a.name as nodename ,a.model as model ,a.bios_serial ,a.processor_count as processor_count ,a.scantime as scantime ,a.os_minor_vers as os_minor_vers,a.os_sub_vers as os_sub_vers ,a.acquisition_time as acquisition_time ,a.status as software_lpar_status ,b.id as installed_software_id ,b.software_id as software_id ,b.users as users ,b.processor_count as inst_processor_count ,b.authenticated as authenticated ,b.status as inst_status ,b.discrepancy_type_id as discrepancy_type_id ,c.id as installed_product_id,c.software_filter_id as product_id ,c.bank_account_id as bank_account_id ,d.map_software_version as version ,'FILTER' as product_type from EAADMIN.software_lpar a ,EAADMIN.installed_software b ,EAADMIN.installed_filter c ,EAADMIN.software_filter d where a.id = b.software_lpar_id and b.id = c.installed_software_id and c.software_filter_id = d.software_filter_id union all select a.id as software_lpar_id ,a.customer_id as customer_id ,a.name as nodename ,a.model as model ,a.bios_serial ,a.processor_count as processor_count ,a.scantime as scantime ,a.os_minor_vers as os_minor_vers,a.os_sub_vers as os_sub_vers ,a.acquisition_time as acquisition_time ,a.status as software_lpar_status ,b.id as installed_software_id ,b.software_id as software_id ,b.users as users ,b.processor_count as inst_processor_count ,b.authenticated as authenticated ,b.status as inst_status ,b.discrepancy_type_id as discrepancy_type_id ,c.id as installed_product_id,c.software_signature_id as product_id ,c.bank_account_id as bank_account_id ,d.software_version as version ,'SIGNATURE' as product_type from EAADMIN.software_lpar a ,EAADMIN.installed_software b ,EAADMIN.installed_signature c ,EAADMIN.software_signature d where a.id = b.software_lpar_id and b.id = c.installed_software_id and c.software_signature_id = d.software_signature_id union all select a.id as software_lpar_id ,a.customer_id as customer_id ,a.name as nodename ,a.model as model ,a.bios_serial ,a.processor_count as processor_count ,a.scantime as scantime ,a.os_minor_vers as os_minor_vers,a.os_sub_vers as os_sub_vers ,a.acquisition_time as acquisition_time ,a.status as software_lpar_status ,b.id as installed_software_id ,b.software_id as software_id ,b.users as users ,b.processor_count as inst_processor_count ,b.authenticated as authenticated ,b.status as inst_status ,b.discrepancy_type_id as discrepancy_type_id ,c.id as installed_product_id,c.sa_product_id as product_id ,c.bank_account_id as bank_account_id ,d.version as version ,'SOFTAUDIT' as product_type from EAADMIN.software_lpar a ,EAADMIN.installed_software b ,EAADMIN.installed_sa_product c ,EAADMIN.sa_product d where a.id = b.software_lpar_id and b.id = c.installed_software_id and c.sa_product_id = d.id union all select a.id as software_lpar_id ,a.customer_id as customer_id ,a.name as nodename ,a.model as model ,a.bios_serial ,a.processor_count as processor_count ,a.scantime as scantime ,a.os_minor_vers as os_minor_vers,a.os_sub_vers as os_sub_vers ,a.acquisition_time as acquisition_time ,a.status as software_lpar_status ,b.id as installed_software_id ,b.software_id as software_id ,b.users as users ,b.processor_count as inst_processor_count ,b.authenticated as authenticated ,b.status as inst_status ,b.discrepancy_type_id as discrepancy_type_id ,c.id as installed_product_id,c.mainframe_feature_id as product_id ,c.bank_account_id as bank_account_id ,CHAR(d.version) as version ,'TADZ' as product_type from EAADMIN.software_lpar a ,EAADMIN.installed_software b ,EAADMIN.installed_tadz c , EAADMIN.MAINFRAME_VERSION d where a.id = b.software_lpar_id and b.id = c.installed_software_id and c.MAINFRAME_FEATURE_ID=d.id union all select a.id as software_lpar_id ,a.customer_id as customer_id ,a.name as nodename ,a.model as model ,a.bios_serial ,a.processor_count as processor_count ,a.scantime as scantime ,a.os_minor_vers as os_minor_vers,a.os_sub_vers as os_sub_vers ,a.acquisition_time as acquisition_time ,a.status as software_lpar_status ,b.id as installed_software_id ,b.software_id as software_id ,b.users as users ,b.processor_count as inst_processor_count ,b.authenticated as authenticated ,b.status as inst_status ,b.discrepancy_type_id as discrepancy_type_id ,c.id as installed_product_id,c.mainframe_feature_id as product_id ,c.bank_account_id as bank_account_id ,CHAR(d.version) as version ,'TADZ' as product_type from EAADMIN.software_lpar a ,EAADMIN.installed_software b ,EAADMIN.installed_tadz c ,EAADMIN.MAINFRAME_VERSION d , EAADMIN.MAINFRAME_FEATURE e where a.id = b.software_lpar_id and b.id = c.installed_software_id and c.MAINFRAME_FEATURE_ID=e.id and e.version_id=d.id union all select a.id as software_lpar_id ,a.customer_id as customer_id ,a.name as nodename ,a.model as model ,a.bios_serial ,a.processor_count as processor_count ,a.scantime as scantime ,a.os_minor_vers as os_minor_vers,a.os_sub_vers as os_sub_vers ,a.acquisition_time as acquisition_time ,a.status as software_lpar_status ,b.id as installed_software_id ,b.software_id as software_id ,b.users as users ,b.processor_count as inst_processor_count ,b.authenticated as authenticated ,b.status as inst_status ,b.discrepancy_type_id as discrepancy_type_id ,0 as installed_product_id,0 as product_id ,0 as bank_account_id ,'MANUAL' as version ,'MANUAL' as product_type from EAADMIN.software_lpar a ,EAADMIN.installed_software b where a.id = b.software_lpar_id and not exists( select 1 from EAADMIN.installed_filter c where c.installed_software_id = b.id ) and not exists( select 1 from EAADMIN.installed_signature d where d.installed_software_id = b.id ) and not exists( select 1 from EAADMIN.installed_sa_product e where e.installed_software_id = b.id ) and not exists( select 1 from EAADMIN.installed_tadz f where f.installed_software_id = b.id )) DATA INITIALLY DEFERRED REFRESH DEFERRED ENABLE QUERY OPTIMIZATION MAINTAINED BY SYSTEM IN "USERSPACE1" ;

ALTER TABLE EAADMIN.v_installed_software_mqt DEACTIVATE ROW ACCESS CONTROL;	

GRANT CONTROL ON eaadmin.v_installed_software_mqt TO USER EAADMIN
;
GRANT SELECT ON eaadmin.v_installed_software_mqt TO  USER EAADMIN
;
GRANT REFERENCES ON eaadmin.v_installed_software_mqt TO GROUP TRAILPRD
;
GRANT SELECT ON eaadmin.v_installed_software_mqt TO GROUP TRAILPRD
;
GRANT REFERENCES ON eaadmin.v_installed_software_mqt TO GROUP TRAILUPD
;
GRANT SELECT ON eaadmin.v_installed_software_mqt TO GROUP TRAILUPD
;