package IBM::Schema::CNDB::CustomerNumberRequestData;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("CUSTOMER_NUMBER_REQUEST_DATA");
__PACKAGE__->add_columns(
  "cust_num_request_data_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "major",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "lpid",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "customer_id",
  { data_type => "BIGINT", is_nullable => 1, size => 19 },
  "cnc_comments",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "claim_work_item",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "claim_activity_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "app_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "fa_code_description",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cost_pool_owner_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cost_pool_owner_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cno_exception_justification",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cno_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cno_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "fa_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "tower",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "sub_group",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "division",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "state",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "country",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "postal_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "address_title",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "address1",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "city",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "central_recv_supp",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "dock_contact_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "dock_contact_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "taxable_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "exemption_reason",
  { data_type => "VARCHAR", is_nullable => 1, size => 36 },
  "charge_to_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "function",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "igf_customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "branch_office_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "status",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "dpe_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "dpe_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "comment",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "hw_contact_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "hw_contact_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_contact_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_contact_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "area",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "clli",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "cr_service_level",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
);
__PACKAGE__->set_primary_key("cust_num_request_data_id");


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:39
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:tQmbgZ1e1dSuWVzJLCtq8g


# You can replace this text with custom content, and it will be preserved on regeneration
1;
