ALTER TABLE "EAADMIN"."ALERT_UNLICENSED_SW_H" ADD COLUMN TYPE VARCHAR(16)
;
ALTER TABLE TRAILSPD_CD.ALERT_UNLICENSED_SW_H ADD COLUMN TYPE VARCHAR(16); 
ALTER TABLE TRAILSPD_CC.ALERT_UNLICENSED_SW_H ADD COLUMN TYPE VARCHAR(16); 
REORG TABLE EAADMIN.ALERT_UNLICENSED_SW_H;
REORG TABLE TRAILSPD_CD.ALERT_UNLICENSED_SW_H;
REORG TABLE TRAILSPD_CC.ALERT_UNLICENSED_SW_H;
RUNSTATS ON TABLE EAADMIN.ALERT_UNLICENSED_SW_H ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.ALERT_UNLICENSED_SW_H ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.ALERT_UNLICENSED_SW_H ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;