ALTER TABLE "EAADMIN"."SOFTWARE_FILTER" ADD COLUMN CATALOG_TYPE VARCHAR(32)
;
ALTER TABLE "EAADMIN"."SOFTWARE_FILTER_H" ADD COLUMN CATALOG_TYPE VARCHAR(32)
;
REORG TABLE EAADMIN.SOFTWARE_FILTER;
REORG TABLE EAADMIN.SOFTWARE_FILTER_H;

INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_RP_QUAL', 'RPREP1', 'S', 'EAADMIN', 'SOFTWARE_FILTER', 'CATALOG_TYPE', 'A', 'N', MAX(COLNO + 1), 'CATALOG_TYPE' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='SOFTWARE_FILTER';
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_RP_QUAL', 'RPREP1', 'S', 'EAADMIN', 'SOFTWARE_FILTER_H', 'CATALOG_TYPE', 'A', 'N', MAX(COLNO + 1), 'CATALOG_TYPE' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='SOFTWARE_FILTER_H';