CREATE REGULAR TABLESPACE EVENT IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 4096 MANAGED BY DATABASE 
         USING (FILE '/db2/staging/staging/tables/event' 80000)
         EXTENTSIZE 32
         PREFETCHSIZE 32
         BUFFERPOOL BP_TABLE_SMALL
         OVERHEAD 12.670000
         TRANSFERRATE 0.180000 
         FILE SYSTEM CACHING  
         DROPPED TABLE RECOVERY ON;

GRANT USE OF TABLESPACE EVENT TO USER EAADMIN;

DROP TABLE EAADMIN.EVENT;
CREATE TABLE EAADMIN.EVENT(
 EVENT_ID INT NOT NULL,
 VALUE VARCHAR(256) NOT NULL,
 RECORD_TIME TIMESTAMP NOT NULL
)
   IN EVENT
;

DROP TABLE EAADMIN.EVENT_TYPE;
CREATE TABLE EAADMIN.EVENT_TYPE(
 EVENT_ID INT NOT NULL,
 NAME VARCHAR(64) NOT NULL,
 DESCRIPTION VARCHAR(256) NOT NULL,
 EVENT_GROUP_ID INT NOT NULL
)
   IN EVENT
;

ALTER TABLE EAADMIN.EVENT_TYPE
ADD CONSTRAINT EVENT_TYPE_PK PRIMARY KEY (EVENT_ID);

DROP TABLE EAADMIN.EVENT_GROUP;
CREATE TABLE EAADMIN.EVENT_GROUP(
 EVENT_GROUP_ID INT NOT NULL,
 NAME VARCHAR(64) NOT NULL,
 DESCRIPTION VARCHAR(256) NOT NULL
)
   IN EVENT
;

ALTER TABLE EAADMIN.EVENT_GROUP
ADD CONSTRAINT EVENT_GROUP_PK PRIMARY KEY (EVENT_GROUP_ID);

ALTER TABLE EAADMIN.EVENT_TYPE
  ADD FOREIGN KEY (EVENT_GROUP_ID) REFERENCES EAADMIN.EVENT_GROUP;

INSERT INTO EAADMIN.EVENT_GROUP(EVENT_GROUP_ID,NAME,DESCRIPTION) VALUES(1,'TRAILS_BRAVO_CORE_SCRIPTS','Trails And Bravo Core Scripts Event Group');
INSERT INTO EAADMIN.EVENT_TYPE(EVENT_ID,NAME,DESCRIPTION,EVENT_GROUP_ID) VALUES(1,'CONTINUOUS_RUN_SCRIPTS','Continuous Run Script Event Type for Trails And Bravo Core Scripts Event Group',1);

--HealthCheck and Monitor Module - Phase 2b
--atpToStaging start/stop script
INSERT INTO EAADMIN.EVENT_TYPE(EVENT_ID,NAME,DESCRIPTION,EVENT_GROUP_ID) VALUES(2,'ATPTOSTAGING_START_STOP_SCRIPT','atpToStaging Start And Stop Script Event Type for Trails And Bravo Core Scripts Event Group',1);
--swcmToStaging start/stop script
INSERT INTO EAADMIN.EVENT_TYPE(EVENT_ID,NAME,DESCRIPTION,EVENT_GROUP_ID) VALUES(3,'SWCMTOSTAGING_START_STOP_SCRIPT','swcmToStaging Start And Stop Script Event Type for Trails And Bravo Core Scripts Event Group',1);
--moveMainframe start/stop script
INSERT INTO EAADMIN.EVENT_TYPE(EVENT_ID,NAME,DESCRIPTION,EVENT_GROUP_ID) VALUES(4,'MOVEMAINFRAME_START_STOP_SCRIPT','moveMainframe Start And Stop Script Event Type for Trails And Bravo Core Scripts Event Group',1);
--bravoReportFork start/stop script
INSERT INTO EAADMIN.EVENT_TYPE(EVENT_ID,NAME,DESCRIPTION,EVENT_GROUP_ID) VALUES(5,'BRAVOREPORTFORK_START_STOP_SCRIPT','bravoReportFork Start And Stop Script Event Type for Trails And Bravo Core Scripts Event Group',1);
--stagingMove start/stop script
INSERT INTO EAADMIN.EVENT_TYPE(EVENT_ID,NAME,DESCRIPTION,EVENT_GROUP_ID) VALUES(6,'STAGINGMOVE_START_STOP_SCRIPT','stagingMove Start And Stop Script Event Type for Trails And Bravo Core Scripts Event Group',1);

COMMIT;
TERMINATE;