------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CD"."SCARLET_RECONCILE"
------------------------------------------------
DROP table   TRAILSPD_CD.SCARLET_RECONCILE                           
;

CREATE TABLE "TRAILSPD_CD"."SCARLET_RECONCILE"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "ID" BIGINT NOT NULL,
		  "LAST_VALIDATE_TIME" TIMESTAMP NOT NULL)   
		 IN TRAILSPD_CD_TABLES  INDEX IN TRAILSPD_CD_INDEX  ; 

ALTER TABLE "TRAILSPD_CD"."SCARLET_RECONCILE" VOLATILE CARDINALITY;


-- DDL Statements for Indexes on Table "TRAILSPD_CD"."SCARLET_RECONCILE"

CREATE UNIQUE INDEX "TRAILSPD_CD"."IXSCARLET_RECONCILE" ON "TRAILSPD_CD"."SCARLET_RECONCILE" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;
		
------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CC"."SCARLET_RECONCILE"
------------------------------------------------
 DROP table   TRAILSPD_CC.SCARLET_RECONCILE                           
;

CREATE TABLE "TRAILSPD_CC"."SCARLET_RECONCILE"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "ID" BIGINT NOT NULL,
		  "LAST_VALIDATE_TIME" TIMESTAMP NOT NULL )   
		 IN TRAILSPD_CD_TABLES  INDEX IN TRAILSPD_CD_INDEX  ; 

ALTER TABLE "TRAILSPD_CC"."SCARLET_RECONCILE" VOLATILE CARDINALITY;



-- DDL Statements for Indexes on Table "TRAILSPD_CC"."SCARLET_RECONCILE"

CREATE UNIQUE INDEX "TRAILSPD_CC"."IXSCARLET_RECONCILE" ON "TRAILSPD_CC"."SCARLET_RECONCILE" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;
		
----------------------------------------------------------------------
-- DDL Statements for registering SCARLET_RECONCILE TRAILSPD_CD
----------------------------------------------------------------------
DELETE FROM ASN.IBMSNAP_REGISTER where SOURCE_OWNER='EAADMIN' 
and SOURCE_TABLE='SCARLET_RECONCILE' 
and CD_OWNER='TRAILSPD_CD' 
and CD_TABLE='SCARLET_RECONCILE' 
and PHYS_CHANGE_OWNER='TRAILSPD_CD' 
and PHYS_CHANGE_TABLE='SCARLET_RECONCILE'
;
INSERT INTO ASN.IBMSNAP_REGISTER (SOURCE_OWNER, SOURCE_TABLE,
SOURCE_VIEW_QUAL, GLOBAL_RECORD, SOURCE_STRUCTURE, SOURCE_CONDENSED,
SOURCE_COMPLETE, CD_OWNER, CD_TABLE, PHYS_CHANGE_OWNER, 
PHYS_CHANGE_TABLE, CD_OLD_SYNCHPOINT, CD_NEW_SYNCHPOINT, 
DISABLE_REFRESH, CCD_OWNER, CCD_TABLE, CCD_OLD_SYNCHPOINT, 
SYNCHPOINT, SYNCHTIME, CCD_CONDENSED, CCD_COMPLETE, ARCH_LEVEL, 
DESCRIPTION, BEFORE_IMG_PREFIX, CONFLICT_LEVEL, 
CHG_UPD_TO_DEL_INS, CHGONLY, RECAPTURE, OPTION_FLAGS,
STOP_ON_ERROR, STATE, STATE_INFO ) VALUES(
'EAADMIN',
'SCARLET_RECONCILE',
0,
'N',
1,
'Y',
'Y',
'TRAILSPD_CD',
'SCARLET_RECONCILE',
'TRAILSPD_CD',
'SCARLET_RECONCILE',
null,
null,
0,
null,
null,
null,
null,
null,
null,
null,
'0801',
null,
null,
'0',
'N',
'N',
'Y',
'NNNN',
'Y',
'I',
null );
----------------------------------------------------------------------
-- DDL Statements for registering SCARLET_RECONCILE for TRAILSPD_CC
----------------------------------------------------------------------
DELETE FROM NEWASN.IBMSNAP_REGISTER where SOURCE_OWNER='EAADMIN' 
and SOURCE_TABLE='SCARLET_RECONCILE' 
and CD_OWNER='TRAILSPD_CC' 
and CD_TABLE='SCARLET_RECONCILE' 
and PHYS_CHANGE_OWNER='TRAILSPD_CC' 
and PHYS_CHANGE_TABLE='SCARLET_RECONCILE'
;
INSERT INTO NEWASN.IBMSNAP_REGISTER (SOURCE_OWNER, SOURCE_TABLE,
SOURCE_VIEW_QUAL, GLOBAL_RECORD, SOURCE_STRUCTURE, SOURCE_CONDENSED,
SOURCE_COMPLETE, CD_OWNER, CD_TABLE, PHYS_CHANGE_OWNER, 
PHYS_CHANGE_TABLE, CD_OLD_SYNCHPOINT, CD_NEW_SYNCHPOINT, 
DISABLE_REFRESH, CCD_OWNER, CCD_TABLE, CCD_OLD_SYNCHPOINT, 
SYNCHPOINT, SYNCHTIME, CCD_CONDENSED, CCD_COMPLETE, ARCH_LEVEL, 
DESCRIPTION, BEFORE_IMG_PREFIX, CONFLICT_LEVEL, 
CHG_UPD_TO_DEL_INS, CHGONLY, RECAPTURE, OPTION_FLAGS,
STOP_ON_ERROR, STATE, STATE_INFO ) VALUES(
'EAADMIN',
'SCARLET_RECONCILE',
0,
'N',
1,
'Y',
'Y',
'TRAILSPD_CC',
'SCARLET_RECONCILE',
'TRAILSPD_CC',
'SCARLET_RECONCILE',
null,
null,
0,
null,
null,
null,
null,
null,
null,
null,
'0801',
null,
null,
'0',
'N',
'N',
'Y',
'NNNN',
'Y',
'I',
null );

-----------------------------------------------------------------------------
-- DDL Statements for registering  NEWASN PrunControl SCARLET_RECONCILE for PD_TO_RP_QUAL
-----------------------------------------------------------------------------
DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE APPLY_QUAL = 'PD_TO_RP_QUAL' 
and SET_NAME = 'RPREP1'
and CNTL_SERVER = 'TRAILSRP'
and SOURCE_OWNER ='TRAILSRP'
and SOURCE_TABLE = 'SCARLET_RECONCILE'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'SCARLET_RECONCILE'
and TARGET_SERVER = 'TRAILSRP'
and PHYS_CHANGE_OWNER = 'TRAILSPD_CC'
and PHYS_CHANGE_TABLE = 'SCARLET_RECONCILE'
;
INSERT INTO NEWASN.IBMSNAP_PRUNCNTL ( 
 APPLY_QUAL, SET_NAME, CNTL_SERVER, CNTL_ALIAS, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_SERVER, 
 TARGET_STRUCTURE, MAP_ID, 
 PHYS_CHANGE_OWNER, PHYS_CHANGE_TABLE 
 ) SELECT 
'PD_TO_RP_QUAL',
 'RPREP1',
 'TRAILSRP',
 'TRAILSRP',
 'EAADMIN',
 'SCARLET_RECONCILE',
 0,
 'EAADMIN',
 'SCARLET_RECONCILE',
 'TRAILSRP',
 8,
 coalesce ( char(max(INT(MAP_ID)+1) ), '0' ),
 'TRAILSPD_CC',
 'SCARLET_RECONCILE' FROM NEWASN.IBMSNAP_PRUNCNTL;
 -----------------------------------------------------------------------------
-- DDL Statements for registering ASN PrunControl SCARLET_RECONCILE for PD_TO_ST_QUAL
-----------------------------------------------------------------------------
DELETE FROM ASN.IBMSNAP_PRUNCNTL WHERE APPLY_QUAL = 'PD_TO_ST_QUAL' 
and SET_NAME = 'STREP1'
and CNTL_SERVER = 'TRAILSST'
and SOURCE_OWNER ='TRAILSST'
and SOURCE_TABLE = 'SCARLET_RECONCILE'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'SCARLET_RECONCILE'
and TARGET_SERVER = 'TRAILSST'
and PHYS_CHANGE_OWNER = 'TRAILSPD_CD'
and PHYS_CHANGE_TABLE = 'SCARLET_RECONCILE'
;
 INSERT INTO ASN.IBMSNAP_PRUNCNTL ( 
 APPLY_QUAL, SET_NAME, CNTL_SERVER, CNTL_ALIAS, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_SERVER, 
 TARGET_STRUCTURE, MAP_ID, 
 PHYS_CHANGE_OWNER, PHYS_CHANGE_TABLE 
 ) SELECT 
'PD_TO_ST_QUAL',
 'STREP1',
 'TRAILSST',
 'TRAILSST',
 'EAADMIN',
 'SCARLET_RECONCILE',
 0,
 'EAADMIN',
 'SCARLET_RECONCILE',
 'TRAILSST',
 8,
 coalesce ( char(max(INT(MAP_ID)+1) ), '0' ),
 'TRAILSPD_CD',
 'SCARLET_RECONCILE' FROM ASN.IBMSNAP_PRUNCNTL;


COMMIT ;
CONNECT RESET;
 
 