package IBM::Schema::CNDB::Recon;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("RECON");
__PACKAGE__->add_columns(
  "recon_id",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "load_time",
  { data_type => "TIMESTAMP", is_nullable => 1, size => 26 },
  "record_time",
  { data_type => "TIMESTAMP", is_nullable => 1, size => 26 },
  "status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_cn_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "comment",
  { data_type => "VARCHAR", is_nullable => 1, size => 128 },
  "atp_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "aed_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "cmr_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "atp_export",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "aed_export",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "cmr_export",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "cn_filter",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "atp_filter",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "aed_filter",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "cmr_filter",
  { data_type => "SMALLINT", is_nullable => 1, size => 5 },
  "account_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cndb_account_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "app_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "cndb_app_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "app_desc",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "area",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_area",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "asset_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_asset_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "branch",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "cndb_branch",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "cust_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cndb_cust_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "enterprise",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "entity",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "fa_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "cndb_fa_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "fin_loc",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_fin_loc",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "function",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cndb_function",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "icc_own",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "cndb_icc_own",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "industry",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cndb_industry",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "lpid_desc",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "nickname",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_nickname",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "sector",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_sector",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "taxable_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_taxable_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "tower_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_tower_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "aed_emp",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_aed_emp",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "aed_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "cndb_aed_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "aed_div",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "cndb_aed_div",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "aed_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "lpid",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "cndb_lpid",
  { data_type => "VARCHAR", is_nullable => 1, size => 8 },
  "major",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "cndb_major",
  { data_type => "VARCHAR", is_nullable => 1, size => 4 },
  "abbr_cust",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_abbr_cust",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cmr_city",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_cmr_city",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cmr_st",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_cmr_st",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "inst_add1",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "cndb_inst_add1",
  { data_type => "VARCHAR", is_nullable => 1, size => 32 },
  "inst_add2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cndb_inst_add2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "inst_add3",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cndb_inst_add3",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "zip_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
  "cndb_zip_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 16 },
);
__PACKAGE__->set_primary_key("recon_id");


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:46
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:R/ah9O9/C2oUE1zMJeiM4g


# You can replace this text with custom content, and it will be preserved on regeneration
1;
