package IBM::Schema::CNDB::VAtp;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("V_ATP");
__PACKAGE__->add_columns(
  "customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "sector_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "industry_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "customer_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 64 },
  "pod_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "app_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "customer_type_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "fa_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tower",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "pool",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sub_group",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "area",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "division",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "state",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "country",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "postal_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address_title",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address1",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "city",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "taxable_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "charge_to_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "lpid_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "function",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "igf_customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "branch_office_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "abbr_customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "account_number",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
  "acct_status",
  { data_type => "VARCHAR", is_nullable => 0, size => 32 },
  "dpe_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "focal_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "acct_contact_hw_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cn_contact_hw_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "os_process_1",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "os_available_1",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "os_process_2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "os_available_2",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "cn_status",
  { data_type => "VARCHAR", is_nullable => 0, size => 32 },
  "aa_sw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "fa_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "hw_interlock",
  { data_type => "VARCHAR", is_nullable => 1, size => 3 },
  "aa_transition_team_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
);


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:50
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:rmyekyOtd8286bGFlBp3wg


# You can replace this text with custom content, and it will be preserved on regeneration
1;
