--export to CON_ASSET_ATP_SCHNEIDER.txt of del modified by nochardel coldelx7c
SELECT
A.PRIMBILL AS "Customer Number",
B.CNDBACCT AS "Account",
A.PRIMNAME AS "Customer Name",
A.CMRCITY AS "City",
B.CUSTTYPE AS "Account Type",
B.INDUSTRY AS "Industry",
B.SECTOR AS "Sector",
B.CNDBDPE AS "DPE",
A.MACHTYPE AS "Type",
A.MODEL AS "Model",
A.SERIAL AS "Serial",
A.MFGSER AS "MFG Serial",
A.OTHMACH AS "Other Machine Type",
A.OEMSER AS "OEM Serial",
A.ICCBILL AS "Lease CN",
A.MAINCUST AS "Maint CN",
A.UCUSTOMR AS "Maint USING CN",
A.SAPCUST AS "Depreciation CN",
A.LPID AS "LPID",
A.SAPLPID AS "Depreciation LPID",
A.LEASSTRT AS "Lease Start",
A.LEASEND AS "Lease End",
A.LEASTERM AS "Lease Term",
A.TRANSTYP AS "Transaction Type",
A.LEASETYP AS "Lease Type",
A.LEASEAMT AS "Monthly Lease",
A.CURRMMC AS "Monthly IBM Maint",
A.STATUS AS "Asset Status",
A.COVERAGE AS "IBM Coverage Level",
A.WUPGINDC AS "Warranty Coverage Level",
A.WARREND AS "Warranty End Date",
A.ORDERNO AS "Order Number",
A.CMDEPR AS "Monthly Depreciation",
A.DEPREND AS "Depreciation End,",
A.NBV AS "Net Book Value",
A.EMPNAMEL AS "Owner Last",
A.EMPNAMEF AS "Owner First",
A.ONPCF AS "ON PCF",
A.INVENTRY AS "Inventoriable",
A.SCANDATE AS "Scan Date",
A.SCANCITY AS "Scan City",
A.SCANBLDG AS "Scan Bldg",
A.SCANFLR AS "Scan Floor",
A.SCANRM AS "Scan Room",
A.SCANGRID AS "Scan Grid",
A.ASSETTAG AS "Asset Tag",
A.DEFN AS "Defn",
A.HWSTATUS AS "Compliance Mgmt Status",
A.ONSAP AS "ON SAP",
A.WARRCOVG AS "Warranty Coverage",
A.MAINTNUM AS "Maintenance Contract Number",
A.AMTFIN AS "Amount Financed",
A.TOTALPAY AS "Sum of Total Remaining Payments",
A.FUTYR1 AS "Future Year 1",
A.FUTYR2 AS "Future Year 2",
A.FUTYR3 AS "Future Year 3",
A.FUTYR4 AS "Future Year 4",
A.FINSORC AS "Financial Source",
A.CAPNUM AS "Capital Release",
A.CAPDATE AS "Capdate",
A.GAV AS "Gross Asset Value",
A.ONCHIS AS "On Chis",
A.CHISINDC AS "Chis Indicator",
A.BASEIND AS "Base Asset Indicator",
B.CMRST AS "State",
A.INSTADD3 AS "Installed Address 3",
A.PCFCUST AS "PCF Customer",
A.OCUSTOMR AS "Owning Customer",
A.TYPE AS "Asset Type",
C.LPAR AS "Hostname(s)"
FROM ATPPROD.MASTER A 
inner join atpprod.customer b on a.primbill=b.customer
left outer join atpprod.lpar c on (a.machtype=c.machtype and a.serial=c.serial)
WHERE 
--  A.PRIMBILL=B.CUSTOMER
 B.CNDBACCT IN ('37540','38020')
  AND A.TYPE <> 'CUSTO'
--  AND A.MACHTYPE=C.MACHTYPE
--  AND A.SERIAL=C.SERIAL
  AND ((C.ISOCNTRY='US') or (c.isocntry is null))
--left join atpprod.lpar c on a.machtype=c.machtype and a.serial=c.serial

ORDER BY A.PRIMBILL,A.MACHTYPE,A.SERIAL,C.LPAR;
