//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 05:31:23 PM EST 
//

package com.ibm.asset.trails.domain;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

@Entity(name = "Product")
@org.hibernate.annotations.Entity(mutable = false)
@Table(name = "PRODUCT")
public class Product extends SoftwareItem implements Serializable {

    private static final long serialVersionUID = -6616799008517128699L;

    @OneToMany(targetEntity = Alias.class, cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
    @JoinTable(name = "PRODUCT_ALIAS", joinColumns = { @JoinColumn(name = "PRODUCT_ID") }, inverseJoinColumns = { @JoinColumn(name = "ALIAS_ID") })
    private Set<Alias> alias = new HashSet<Alias>();

    @ManyToOne(cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
    private Manufacturer manufacturer;

    @Basic
    @Column(name = "SUB_CAPACITY_LICENSING")
    private Boolean subCapacityLicensing;

    @Basic
    @Column(name = "FUNCTION")
    private String function;

    @Basic
    @Column(name = "IPLA")
    @Enumerated(EnumType.STRING)
    private IPLAType ipla;

    @Basic
    @Column(name = "PVU")
    private Boolean pvu;

    @Basic
    @Column(name = "LICENSE_TYPE")
    private Integer licenseType;

    public Set<Alias> getAlias() {
        return alias;
    }

    public void setAlias(Set<Alias> alias) {
        this.alias = alias;
    }

    public Manufacturer getManufacturer() {
        return manufacturer;
    }

    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }

    public Boolean getSubCapacityLicensing() {
        return subCapacityLicensing;
    }

    public void setSubCapacityLicensing(Boolean subCapacityLicensing) {
        this.subCapacityLicensing = subCapacityLicensing;
    }

    public String getFunction() {
        return function;
    }

    public void setFunction(String function) {
        this.function = function;
    }

    public IPLAType getIpla() {
        return ipla;
    }

    public void setIpla(IPLAType ipla) {
        this.ipla = ipla;
    }

    public Boolean getPvu() {
        return pvu;
    }

    public void setPvu(Boolean pvu) {
        this.pvu = pvu;
    }

    public Integer getLicenseType() {
        return licenseType;
    }

    public void setLicenseType(Integer licenseType) {
        this.licenseType = licenseType;
    }

}
