ALTER TABLE "EAADMIN"."SCHEDULE_F" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
Reorg table EAADMIN.SCHEDULE_f;
RUNSTATS ON TABLE EAADMIN.SCHEDULE_F ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
