ALTER TABLE "EAADMIN"."SCHEDULE_F" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "EAADMIN"."SCHEDULE_F" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
ALTER TABLE "TRAILSPD_CD"."SCHEDULE_F" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "TRAILSPD_CD"."SCHEDULE_F" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "TRAILSPD_CD"."SCHEDULE_F" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
ALTER TABLE "TRAILSPD_CC"."SCHEDULE_F" ALTER COLUMN SOFTWARE_ID DROP NOT NULL;
ALTER TABLE "TRAILSPD_CC"."SCHEDULE_F" ALTER COLUMN SOFTWARE_NAME DROP NOT NULL;
ALTER TABLE "TRAILSPD_CC"."SCHEDULE_F" ALTER COLUMN SOFTWARE_TITLE DROP NOT NULL;
Reorg table EAADMIN.SCHEDULE_f;
Reorg table TRAILSPD_CD.SCHEDULE_F;
Reorg table TRAILSPD_CC.SCHEDULE_F;
RUNSTATS ON TABLE EAADMIN.SCHEDULE_F ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.SCHEDULE_F ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.SCHEDULE_F ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;