//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 05:31:23 PM EST 
//

package com.ibm.asset.swkbt.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity(name = "SoftwareItem")
@org.hibernate.annotations.Entity(mutable = false)
@Table(name = "SOFTWARE_ITEM")
public class SoftwareItem extends KbDefinition implements Serializable {

	private static final long serialVersionUID = -1698447978543795171L;

	@Basic
	@Column(name = "NAME")
	private String name;

	@Basic
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_OF_SUPPORT")
	private Date endOfSupport;

	@Basic
	@Column(name = "PRODUCT_ID")
	private String productId;

	@Basic
	@Column(name = "WEBSITE")
	private String website;

	@Basic
	@Column(name = "IPLA")
	@Enumerated(EnumType.STRING)
	private IPLAType ipla;

	@Basic
	@Column(name = "SUB_CAPACITY_LICENSING")
	private Boolean subCapacityLicensing;

	@Basic
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ACTIVATION_DATE")
	private Date activationDate;

	@Basic
	@Column(name = "PRODUCT_ROLE")
	@Enumerated(EnumType.STRING)
	private ProductRoleEnumeration productRole;

	@OneToMany(targetEntity = Pid.class, cascade = { CascadeType.ALL }, fetch = FetchType.LAZY)
	@JoinTable(name = "SOFTWARE_ITEM_PID", joinColumns = { @JoinColumn(name = "SOFTWARE_ITEM_ID") }, inverseJoinColumns = { @JoinColumn(name = "PID_ID") })
	private Set<Pid> pids = new HashSet<Pid>();

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getEndOfSupport() {
		return endOfSupport;
	}

	public void setEndOfSupport(Date endOfSupport) {
		this.endOfSupport = endOfSupport;
	}

	public String getProductId() {
		return productId;
	}

	public void setProductId(String productId) {
		this.productId = productId;
	}

	public Boolean getSubCapacityLicensing() {
		return subCapacityLicensing;
	}

	public void setSubCapacityLicensing(Boolean subCapacityLicensing) {
		this.subCapacityLicensing = subCapacityLicensing;
	}

	public IPLAType getIpla() {
		return ipla;
	}

	public void setIpla(IPLAType ipla) {
		this.ipla = ipla;
	}

	public String getWebsite() {
		return website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public Date getActivationDate() {
		return activationDate;
	}

	public void setActivationDate(Date activationDate) {
		this.activationDate = activationDate;
	}

	public ProductRoleEnumeration getProductRole() {
		return productRole;
	}

	public void setProductRole(ProductRoleEnumeration productRole) {
		this.productRole = productRole;
	}

	public Set<Pid> getPids() {
		return pids;
	}

	public void setPids(Set<Pid> pids) {
		this.pids = pids;
	}
}