
------------------------------------------------
-- DDL Statements for Table "EAADMIN "."INSTALLED_SCRIPT"
------------------------------------------------

CREATE TABLE "EAADMIN "."INSTALLED_SCRIPT"  (
                  "ID" BIGINT NOT NULL ,
                  "INSTALLED_SOFTWARE_ID" BIGINT NOT NULL ,
                  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL ,
                  "BANK_ACCOUNT_ID" BIGINT NOT NULL ,
                  "STATUS" VARCHAR(32) )
                 DATA CAPTURE CHANGES
                 IN "INSTALLED" INDEX IN "INSTALLEDINDEX" ;


-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF1INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT"
                ("INSTALLED_SOFTWARE_ID" ASC,
                 "SOFTWARE_SCRIPT_ID" ASC,
                 "BANK_ACCOUNT_ID" ASC,
                 "STATUS" ASC,
                 "ID" ASC)
                CLUSTER
                COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF2INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT"
                ("BANK_ACCOUNT_ID" ASC,
                 "INSTALLED_SOFTWARE_ID" ASC,
                 "ID" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."INSTALLED_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF3INSTALLEDSCRIPT" ON "EAADMIN "."INSTALLED_SCRIPT"
                ("SOFTWARE_SCRIPT_ID" ASC,
                 "INSTALLED_SOFTWARE_ID" ASC,
                 "BANK_ACCOUNT_ID" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;

---------- Privilege For INSTALLED_SCRIPT ----------
GRANT REFERENCES ON TABLE "EAADMIN "."INSTALLED_SCRIPT"      TO GROUP "TRAILUPD" ;       
GRANT SELECT ON TABLE "EAADMIN "."INSTALLED_SCRIPT"          TO GROUP "TRAILSTG" ; 
GRANT SELECT ON "EAADMIN"."INSTALLED_SCRIPT" TO USER EAADMIN
;
---------Delete records from SUBS_MEMEBER first if exist------
DELETE FROM ASN.IBMSNAP_SUBS_MEMBR  WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
and SET_NAME ='STREP1'
and SOURCE_OWNER ='EAADMIN'
and SOURCE_TABLE = 'INSTALLED_SCRIPT'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'INSTALLED_SCRIPT'
;
DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
and SET_NAME = 'STREP1'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'INSTALLED_SCRIPT'
;

---------Register columns into apply SUBS_MEMEBER-------
INSERT INTO ASN.IBMSNAP_SUBS_MEMBR (
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_STRUCTURE, 
 TARGET_CONDENSED, TARGET_COMPLETE, 
 PREDICATES, UOW_CD_PREDICATES, JOIN_UOW_CD, 
 MEMBER_STATE,TARGET_KEY_CHG,LOADX_TYPE, 
 LOADX_SRC_N_OWNER,LOADX_SRC_N_TABLE 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'INSTALLED_SCRIPT',
 0,
 'EAADMIN',
 'INSTALLED_SCRIPT',
 8,
 'Y',
 'Y',
 null,
 null,
 null,
 'N',
 'N',
 null,
 null,
 null
 );


INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'INSTALLED_SCRIPT',
 'ID',
 'A',
 'Y',
 1,
 'ID'
 );


INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'INSTALLED_SCRIPT',
 'INSTALLED_SOFTWARE_ID',
 'A',
 'N',
 2,
 'INSTALLED_SOFTWARE_ID'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'INSTALLED_SCRIPT',
 'SOFTWARE_SCRIPT_ID',
 'A',
 'N',
 3,
 'SOFTWARE_SCRIPT_ID'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'INSTALLED_SCRIPT',
 'BANK_ACCOUNT_ID',
 'A',
 'N',
 4,
 'BANK_ACCOUNT_ID'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'INSTALLED_SCRIPT',
 'STATUS',
 'A',
 'N',
 5,
 'STATUS'
 );
 
UPDATE ASN.IBMSNAP_SUBS_SET 
SET ACTIVATE = 1
  WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
  AND SET_NAME = 'STREP1';