
------------------------------------------------
-- DDL Statements for Table "EAADMIN "."SOFTWARE_SCRIPT"
------------------------------------------------
--DROP TABLE "EAADMIN "."SOFTWARE_SCRIPT"  ;

CREATE TABLE "EAADMIN "."SOFTWARE_SCRIPT"  (
                  "SOFTWARE_ID" BIGINT NOT NULL ,
                  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL ,
                  "SOFTWARE_NAME" VARCHAR(128) NOT NULL ,
                  "SOFTWARE_VERSION" VARCHAR(64) ,
                  "MAP_SOFTWARE_VERSION" VARCHAR(64) ,
                  "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL ,
                  "COMMENTS" VARCHAR(255) ,
                  "REMOTE_USER" VARCHAR(32) NOT NULL ,
                  "RECORD_TIME" TIMESTAMP NOT NULL ,
                  "STATUS" VARCHAR(32) NOT NULL ,
                  "CATALOG_TYPE" VARCHAR(32) )
                 DATA CAPTURE CHANGES
                 IN "SOFTWARE" INDEX IN "SOFTWAREINDEX" ;


-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF1SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("SOFTWARE_ID" ASC,
                 "STATUS" ASC,
                 "SOFTWARE_SCRIPT_ID" ASC,
                 "SOFTWARE_NAME" ASC,
                 "SOFTWARE_VERSION" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF2SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("SOFTWARE_NAME" ASC,
                 "SOFTWARE_VERSION" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF3SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("SOFTWARE_SCRIPT_ID" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;
-- DDL Statements for Primary Key on Table "EAADMIN "."SOFTWARE_SCRIPT"

ALTER TABLE "EAADMIN "."SOFTWARE_SCRIPT"
        ADD CONSTRAINT "PKSOFTWARESCRIPT" PRIMARY KEY
                ("SOFTWARE_SCRIPT_ID");




-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF4SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("SOFTWARE_SCRIPT_ID" ASC)
                INCLUDE ("MAP_SOFTWARE_VERSION" )

                COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE INDEX "EAADMIN "."IF5SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("STATUS" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;

ALTER TABLE EAADMIN.SOFTWARE_SCRIPT DATA CAPTURE CHANGES;
---------- Privilege For SOFTWARE_SCRIPT ----------
GRANT REFERENCES ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"       TO GROUP "TRAILUPD" ;
GRANT DELETE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO GROUP "TRAILPRD" ;    
GRANT INSERT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO GROUP "TRAILPRD" ;    
GRANT SELECT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO GROUP "TRAILPRD" ;    
GRANT UPDATE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO GROUP "TRAILPRD" ; 

GRANT REFERENCES ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"       TO USER eaadmin ;   
GRANT DELETE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO USER eaadmin ;   
GRANT INSERT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO USER eaadmin ;   
GRANT SELECT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO USER eaadmin ;   
GRANT UPDATE ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"           TO USER eaadmin ; 

------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CD"."SOFTWARE_SCRIPT"
------------------------------------------------
DROP table   TRAILSPD_CD.SOFTWARE_SCRIPT                           
;

CREATE TABLE "TRAILSPD_CD"."SOFTWARE_SCRIPT"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "SOFTWARE_ID" BIGINT NOT NULL ,
          "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL ,
          "SOFTWARE_NAME" VARCHAR(128) NOT NULL ,
          "SOFTWARE_VERSION" VARCHAR(64) ,
          "MAP_SOFTWARE_VERSION" VARCHAR(64) ,
          "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL ,
          "COMMENTS" VARCHAR(255) ,
          "REMOTE_USER" VARCHAR(32) NOT NULL ,
          "RECORD_TIME" TIMESTAMP NOT NULL ,
          "STATUS" VARCHAR(32) NOT NULL ,
          "CATALOG_TYPE" VARCHAR(32) )   
		 IN TRAILSPD_CD_TABLES  INDEX IN TRAILSPD_CD_INDEX  ; 

ALTER TABLE "TRAILSPD_CD"."SOFTWARE_SCRIPT" VOLATILE CARDINALITY;


-- DDL Statements for Indexes on Table "TRAILSPD_CD"."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "TRAILSPD_CD"."IXCDSOFTWARE_SCRIPT" ON "TRAILSPD_CD"."SOFTWARE_SCRIPT" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;
------------------------------------------------
-- DDL Statements for Table "TRAILSPD_CC"."SOFTWARE_SCRIPT"
------------------------------------------------
 DROP table   TRAILSPD_CC.SOFTWARE_SCRIPT                           
;

CREATE TABLE "TRAILSPD_CC"."SOFTWARE_SCRIPT"  (
		  "IBMSNAP_COMMITSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_INTENTSEQ" VARCHAR(16) FOR BIT DATA NOT NULL , 
		  "IBMSNAP_OPERATION" CHAR(1) NOT NULL , 
		  "SOFTWARE_ID" BIGINT NOT NULL ,
          "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL ,
          "SOFTWARE_NAME" VARCHAR(128) NOT NULL ,
          "SOFTWARE_VERSION" VARCHAR(64) ,
          "MAP_SOFTWARE_VERSION" VARCHAR(64) ,
          "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL ,
          "COMMENTS" VARCHAR(255) ,
          "REMOTE_USER" VARCHAR(32) NOT NULL ,
          "RECORD_TIME" TIMESTAMP NOT NULL ,
          "STATUS" VARCHAR(32) NOT NULL ,
          "CATALOG_TYPE" VARCHAR(32) )   
		 IN TRAILSPD_CD_TABLES  INDEX IN TRAILSPD_CD_INDEX  ; 

ALTER TABLE "TRAILSPD_CC"."SOFTWARE_SCRIPT" VOLATILE CARDINALITY;



-- DDL Statements for Indexes on Table "TRAILSPD_CC"."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "TRAILSPD_CC"."IXCCSOFTWARE_SCRIPT" ON "TRAILSPD_CC"."SOFTWARE_SCRIPT" 
		("IBMSNAP_COMMITSEQ" ASC,
		 "IBMSNAP_INTENTSEQ" ASC)
		PCTFREE 0 
		COMPRESS NO ALLOW REVERSE SCANS;

		
----------------------------------------------------------------------
-- DDL Statements for registering SOFTWARE_SCRIPT TRAILSPD_CD
----------------------------------------------------------------------
DELETE FROM ASN.IBMSNAP_REGISTER where SOURCE_OWNER='EAADMIN' 
and SOURCE_TABLE='SOFTWARE_SCRIPT' 
and CD_OWNER='TRAILSPD_CD' 
and CD_TABLE='SOFTWARE_SCRIPT' 
and PHYS_CHANGE_OWNER='TRAILSPD_CD' 
and PHYS_CHANGE_TABLE='SOFTWARE_SCRIPT'
;
INSERT INTO ASN.IBMSNAP_REGISTER (SOURCE_OWNER, SOURCE_TABLE,
SOURCE_VIEW_QUAL, GLOBAL_RECORD, SOURCE_STRUCTURE, SOURCE_CONDENSED,
SOURCE_COMPLETE, CD_OWNER, CD_TABLE, PHYS_CHANGE_OWNER, 
PHYS_CHANGE_TABLE, CD_OLD_SYNCHPOINT, CD_NEW_SYNCHPOINT, 
DISABLE_REFRESH, CCD_OWNER, CCD_TABLE, CCD_OLD_SYNCHPOINT, 
SYNCHPOINT, SYNCHTIME, CCD_CONDENSED, CCD_COMPLETE, ARCH_LEVEL, 
DESCRIPTION, BEFORE_IMG_PREFIX, CONFLICT_LEVEL, 
CHG_UPD_TO_DEL_INS, CHGONLY, RECAPTURE, OPTION_FLAGS,
STOP_ON_ERROR, STATE, STATE_INFO ) VALUES(
'EAADMIN',
'SOFTWARE_SCRIPT',
0,
'N',
1,
'Y',
'Y',
'TRAILSPD_CD',
'SOFTWARE_SCRIPT',
'TRAILSPD_CD',
'SOFTWARE_SCRIPT',
null,
null,
0,
null,
null,
null,
null,
null,
null,
null,
'0801',
null,
null,
'0',
'N',
'N',
'Y',
'NNNN',
'Y',
'I',
null );
----------------------------------------------------------------------
-- DDL Statements for registering SOFTWARE_SCRIPT for TRAILSPD_CC
----------------------------------------------------------------------
DELETE FROM NEWASN.IBMSNAP_REGISTER where SOURCE_OWNER='EAADMIN' 
and SOURCE_TABLE='SOFTWARE_SCRIPT' 
and CD_OWNER='TRAILSPD_CC' 
and CD_TABLE='SOFTWARE_SCRIPT' 
and PHYS_CHANGE_OWNER='TRAILSPD_CC' 
and PHYS_CHANGE_TABLE='SOFTWARE_SCRIPT'
;
INSERT INTO NEWASN.IBMSNAP_REGISTER (SOURCE_OWNER, SOURCE_TABLE,
SOURCE_VIEW_QUAL, GLOBAL_RECORD, SOURCE_STRUCTURE, SOURCE_CONDENSED,
SOURCE_COMPLETE, CD_OWNER, CD_TABLE, PHYS_CHANGE_OWNER, 
PHYS_CHANGE_TABLE, CD_OLD_SYNCHPOINT, CD_NEW_SYNCHPOINT, 
DISABLE_REFRESH, CCD_OWNER, CCD_TABLE, CCD_OLD_SYNCHPOINT, 
SYNCHPOINT, SYNCHTIME, CCD_CONDENSED, CCD_COMPLETE, ARCH_LEVEL, 
DESCRIPTION, BEFORE_IMG_PREFIX, CONFLICT_LEVEL, 
CHG_UPD_TO_DEL_INS, CHGONLY, RECAPTURE, OPTION_FLAGS,
STOP_ON_ERROR, STATE, STATE_INFO ) VALUES(
'EAADMIN',
'SOFTWARE_SCRIPT',
0,
'N',
1,
'Y',
'Y',
'TRAILSPD_CC',
'SOFTWARE_SCRIPT',
'TRAILSPD_CC',
'SOFTWARE_SCRIPT',
null,
null,
0,
null,
null,
null,
null,
null,
null,
null,
'0801',
null,
null,
'0',
'N',
'N',
'Y',
'NNNN',
'Y',
'I',
null );

-----------------------------------------------------------------------------
-- DDL Statements for registering  NEWASN PrunControl SOFTWARE_SCRIPT for PD_TO_RP_QUAL
-----------------------------------------------------------------------------
DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE APPLY_QUAL = 'PD_TO_RP_QUAL' 
and SET_NAME = 'RPREP1'
and CNTL_SERVER = 'TRAILSRP'
and SOURCE_OWNER ='EAADMIN'
and SOURCE_TABLE = 'SOFTWARE_SCRIPT'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'SOFTWARE_SCRIPT'
and TARGET_SERVER = 'TRAILSRP'
and PHYS_CHANGE_OWNER = 'TRAILSPD_CC'
and PHYS_CHANGE_TABLE = 'SOFTWARE_SCRIPT'
;
INSERT INTO NEWASN.IBMSNAP_PRUNCNTL ( 
 APPLY_QUAL, SET_NAME, CNTL_SERVER, CNTL_ALIAS, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_SERVER, 
 TARGET_STRUCTURE, MAP_ID, 
 PHYS_CHANGE_OWNER, PHYS_CHANGE_TABLE 
 ) SELECT 
'PD_TO_RP_QUAL',
 'RPREP1',
 'TRAILSRP',
 'TRAILSRP',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 0,
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'TRAILSRP',
 8,
 coalesce ( char(max(INT(MAP_ID)+1) ), '0' ),
 'TRAILSPD_CC',
 'SOFTWARE_SCRIPT' FROM NEWASN.IBMSNAP_PRUNCNTL;
 -----------------------------------------------------------------------------
-- DDL Statements for registering ASN PrunControl SOFTWARE_SCRIPT for PD_TO_ST_QUAL
-----------------------------------------------------------------------------
DELETE FROM ASN.IBMSNAP_PRUNCNTL WHERE APPLY_QUAL = 'PD_TO_ST_QUAL' 
and SET_NAME = 'STREP1'
and CNTL_SERVER = 'TRAILSST'
and SOURCE_OWNER ='EAADMIN'
and SOURCE_TABLE = 'SOFTWARE_SCRIPT'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'SOFTWARE_SCRIPT'
and TARGET_SERVER = 'TRAILSST'
and PHYS_CHANGE_OWNER = 'TRAILSPD_CD'
and PHYS_CHANGE_TABLE = 'SOFTWARE_SCRIPT'
;
 INSERT INTO ASN.IBMSNAP_PRUNCNTL ( 
 APPLY_QUAL, SET_NAME, CNTL_SERVER, CNTL_ALIAS, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_SERVER, 
 TARGET_STRUCTURE, MAP_ID, 
 PHYS_CHANGE_OWNER, PHYS_CHANGE_TABLE 
 ) SELECT 
'PD_TO_ST_QUAL',
 'STREP1',
 'TRAILSST',
 'TRAILSST',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 0,
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'TRAILSST',
 8,
 coalesce ( char(max(INT(MAP_ID)+1) ), '0' ),
 'TRAILSPD_CD',
 'SOFTWARE_SCRIPT' FROM ASN.IBMSNAP_PRUNCNTL;


COMMIT ;
