
------------------------------------------------
-- DDL Statements for Table "EAADMIN "."SOFTWARE_SCRIPT"
------------------------------------------------
DROP TABLE "EAADMIN "."SOFTWARE_SCRIPT"  ;

CREATE TABLE "EAADMIN "."SOFTWARE_SCRIPT"  (
                  "SOFTWARE_ID" BIGINT NOT NULL ,
                  "SOFTWARE_SCRIPT_ID" BIGINT NOT NULL ,
                  "SOFTWARE_NAME" VARCHAR(128) NOT NULL ,
                  "SOFTWARE_VERSION" VARCHAR(64) ,
                  "MAP_SOFTWARE_VERSION" VARCHAR(64) ,
                  "CHANGE_JUSTIFICATION" VARCHAR(128) NOT NULL ,
                  "COMMENTS" VARCHAR(255) ,
                  "REMOTE_USER" VARCHAR(32) NOT NULL ,
                  "RECORD_TIME" TIMESTAMP NOT NULL ,
                  "STATUS" VARCHAR(32) NOT NULL ,
                  "CATALOG_TYPE" VARCHAR(32) )
                 DATA CAPTURE CHANGES
                 IN "SOFTWARE" INDEX IN "SOFTWAREINDEX" ;


-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF1SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("SOFTWARE_ID" ASC,
                 "STATUS" ASC,
                 "SOFTWARE_SCRIPT_ID" ASC,
                 "SOFTWARE_NAME" ASC,
                 "SOFTWARE_VERSION" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;

-- DDL Statements for Indexes on Table "EAADMIN "."SOFTWARE_SCRIPT"

CREATE UNIQUE INDEX "EAADMIN "."IF2SOFTWARESCRIPT" ON "EAADMIN "."SOFTWARE_SCRIPT"
                ("SOFTWARE_NAME" ASC,
                 "SOFTWARE_VERSION" ASC)

                COMPRESS NO ALLOW REVERSE SCANS;
---------- Privilege For SOFTWARE_SCRIPT ----------
GRANT REFERENCES ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"      TO GROUP "TRAILUPD" ;       
GRANT SELECT ON TABLE "EAADMIN "."SOFTWARE_SCRIPT"          TO GROUP "TRAILSTG" ; 
GRANT SELECT ON "EAADMIN"."SOFTWARE_SCRIPT" TO USER EAADMIN
;
---------Delete records from SUBS_MEMEBER first if exist------
DELETE FROM ASN.IBMSNAP_SUBS_MEMBR  WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
and SET_NAME ='STREP1'
and SOURCE_OWNER ='EAADMIN'
and SOURCE_TABLE = 'SOFTWARE_SCRIPT'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'SOFTWARE_SCRIPT'
;
DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
and SET_NAME = 'STREP1'
and TARGET_OWNER = 'EAADMIN'
and TARGET_TABLE = 'SOFTWARE_SCRIPT'
;

---------Register columns into apply SUBS_MEMEBER-------
INSERT INTO ASN.IBMSNAP_SUBS_MEMBR (
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 SOURCE_OWNER, SOURCE_TABLE, SOURCE_VIEW_QUAL, 
 TARGET_OWNER, TARGET_TABLE, TARGET_STRUCTURE, 
 TARGET_CONDENSED, TARGET_COMPLETE, 
 PREDICATES, UOW_CD_PREDICATES, JOIN_UOW_CD, 
 MEMBER_STATE,TARGET_KEY_CHG,LOADX_TYPE, 
 LOADX_SRC_N_OWNER,LOADX_SRC_N_TABLE 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 0,
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 8,
 'Y',
 'Y',
 null,
 null,
 null,
 'N',
 'N',
 null,
 null,
 null
 );


INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'SOFTWARE_ID',
 'A',
 'N',
 1,
 'SOFTWARE_ID'
 );


INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'SOFTWARE_SCRIPT_ID',
 'A',
 'Y',
 2,
 'SOFTWARE_SCRIPT_ID'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'SOFTWARE_NAME',
 'A',
 'N',
 3,
 'SOFTWARE_NAME'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'SOFTWARE_VERSION',
 'A',
 'N',
 4,
 'SOFTWARE_VERSION'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'MAP_SOFTWARE_VERSION',
 'A',
 'N',
 5,
 'MAP_SOFTWARE_VERSION'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'CHANGE_JUSTIFICATION',
 'A',
 'N',
 6,
 'CHANGE_JUSTIFICATION'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'COMMENTS',
 'A',
 'N',
 7,
 'COMMENTS'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'REMOTE_USER',
 'A',
 'N',
 8,
 'REMOTE_USER'
 );
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'RECORD_TIME',
 'A',
 'N',
 9,
 'RECORD_TIME'
 );
 
  INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'STATUS',
 'A',
 'N',
 10,
 'STATUS'
 );
 
  INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 ) VALUES (
 'PD_TO_ST_QUAL',
 'STREP1',
 'S',
 'EAADMIN',
 'SOFTWARE_SCRIPT',
 'CATALOG_TYPE',
 'A',
 'N',
 11,
 'CATALOG_TYPE'
 );
 

UPDATE ASN.IBMSNAP_SUBS_SET 
SET ACTIVATE = 1
  WHERE APPLY_QUAL = 'PD_TO_ST_QUAL'
  AND SET_NAME = 'STREP1';