CREATE REGULAR TABLESPACE OPERATION_QUEUE IN DATABASE PARTITION GROUP IBMDEFAULTGROUP PAGESIZE 4096 MANAGED BY DATABASE 
         USING (FILE '/db2/staging/staging/tables/operation_queue' 80000)
         EXTENTSIZE 32
         PREFETCHSIZE 32
         BUFFERPOOL BP_TABLE_SMALL
         OVERHEAD 12.670000
         TRANSFERRATE 0.180000 
         FILE SYSTEM CACHING  
         DROPPED TABLE RECOVERY ON;

GRANT USE OF TABLESPACE OPERATION_QUEUE TO USER EAADMIN;

DROP TABLE EAADMIN.OPERATION_QUEUE;
--There are four values for the 'OPERATION_STATUS' column
--1. 'ADDED' - Operation Record is just added.
--2. 'PROGRESSING' - Operation Record is under progressing.
--3. 'FAILED' - Operation Record has been processed failed.
--4. 'DONE' -  Operation Record has been processed successfully.
CREATE TABLE EAADMIN.OPERATION_QUEUE(
 OPERATION_ID BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER),
 OPERATION_NAME_CODE VARCHAR(64) NOT NULL,
 OPERATION_NAME_DESCRIPTION VARCHAR(256) NOT NULL,
 OPERATION_PARMS VARCHAR(512) NOT NULL,
 OPERATION_STATUS VARCHAR(32) NOT NULL,
 OPERATION_USER VARCHAR(64) NOT NULL,
 OPERATION_ADD_TIME TIMESTAMP NOT NULL,
 OPERATION_UPDATE_TIME TIMESTAMP,
 COMMENTS VARCHAR(1024)
) 
 IN OPERATION_QUEUE
;

ALTER TABLE EAADMIN.OPERATION_QUEUE
    ADD CONSTRAINT PKOPERATIONQUEUE
PRIMARY KEY (OPERATION_ID);