CREATE TABLE "EAADMIN"."ALERT_HARDWARE_CFGDATA"
(
   HARDWARE_ID bigint NOT NULL,
   ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER ),
   COMMENTS varchar(255),
   REMOTE_USER varchar(32) NOT NULL,
   CREATION_TIME timestamp NOT NULL,
   RECORD_TIME timestamp NOT NULL,
   OPEN smallint NOT NULL,
   CONSTRAINT PKALERTHARDWARE_CFGDATA PRIMARY KEY (HARDWARE_ID,ID)
)  DATA CAPTURE CHANGES
   IN "ALERT" INDEX IN "ALERTINDEX"
;

CREATE UNIQUE INDEX "EAADMIN "."IF5ALERTHARDWARE_CFGDATA" ON "EAADMIN "."ALERT_HARDWARE_CFGDATA"
                ("HARDWARE_ID" ASC)
                COMPRESS NO ALLOW REVERSE SCANS; 

CREATE UNIQUE INDEX IF3ALERTHARDWARE_CFGDATA ON "EAADMIN"."ALERT_HARDWARE_CFGDATA"
(
  OPEN,
  HARDWARE_ID,
  REMOTE_USER,
  CREATION_TIME
)
;
CREATE UNIQUE INDEX IF2ALERTHARDWARE_CFGDATA ON "EAADMIN"."ALERT_HARDWARE_CFGDATA"(ID)
;
CREATE UNIQUE INDEX IF1ALERTHARDWARE_CFGDATA ON "EAADMIN"."ALERT_HARDWARE_CFGDATA"(HARDWARE_ID)
;
CREATE UNIQUE INDEX PKALERTHARDWARE_CFGDATA ON "EAADMIN"."ALERT_HARDWARE_CFGDATA"
(
  HARDWARE_ID,
  ID
)
;

CREATE UNIQUE INDEX IDX_01_HW_CFGDATA ON "EAADMIN"."ALERT_HARDWARE_CFGDATA"
(
  OPEN,
  HARDWARE_ID
)
;
CREATE INDEX IDX_02_HW_CFGDATA ON "EAADMIN"."ALERT_HARDWARE_CFGDATA"
(
  OPEN,
  ID,
  HARDWARE_ID
)
;




CREATE TABLE "EAADMIN"."ALERT_HARDWARE_CFGDATA_H"
(
   ALERT_HARDWARE_CFGDATA_ID bigint NOT NULL,
   ID bigint NOT NULL GENERATED ALWAYS AS IDENTITY (
                    START WITH +1
                    INCREMENT BY +1
                    MINVALUE +1
                    MAXVALUE +9223372036854775807
                    NO CYCLE
                    CACHE 20
                    NO ORDER ),
   COMMENTS varchar(255),
   REMOTE_USER varchar(32) NOT NULL,
   CREATION_TIME timestamp NOT NULL,
   RECORD_TIME timestamp NOT NULL,
   OPEN smallint NOT NULL,
   CONSTRAINT PKALERTHARDWARE_CFGDATAH PRIMARY KEY (ALERT_HARDWARE_CFGDATA_ID,ID)
) DATA CAPTURE CHANGES
  IN "HISTORY" INDEX IN "HISTORYINDEX" ;
;
CREATE UNIQUE INDEX IF1ALERTHARDWARE_CFGDATAH ON "EAADMIN"."ALERT_HARDWARE_CFGDATA_H"(ID)
;

INSERT INTO "EAADMIN"."ALERT_TYPE" (NAME,CODE) VALUES ('SOM1b: HW Box Critical Configuration Data Populated','HWCFGDTA');

INSERT INTO "EAADMIN"."ALERT_TYPE_CAUSE" (ALERT_TYPE_ID,ALERT_CAUSE_ID,STATUS) VALUES ( ( select id from eaadmin.alert_type where code = 'HWCFGDTA' ) , 1,'ACTIVE' /*not nullable*/);
