--TRAILSPD:
GRANT CONTROL ON EAADMIN.V_ALERTS TO USER EAADMIN
;
GRANT DELETE ON EAADMIN.V_ALERTS TO GROUP TRAILPRD
;
GRANT INSERT ON EAADMIN.V_ALERTS TO GROUP TRAILPRD
;
GRANT REFERENCES ON EAADMIN.V_ALERTS TO GROUP TRAILPRD
;
GRANT SELECT ON EAADMIN.V_ALERTS TO GROUP TRAILPRD
;
GRANT UPDATE ON EAADMIN.V_ALERTS TO GROUP TRAILPRD
;
GRANT DELETE ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
;
GRANT INSERT ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
;
GRANT REFERENCES ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
;
GRANT SELECT ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
;
GRANT UPDATE ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
;   
GRANT CONTROL ON EAADMIN.V_ALERT_RED_AGING TO USER EAADMIN
;
GRANT DELETE ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILPRD
;
GRANT INSERT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILPRD
;
GRANT REFERENCES ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILPRD
;
GRANT SELECT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILPRD
;
GRANT UPDATE ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILPRD
;
GRANT DELETE ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
;
GRANT INSERT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
;
GRANT REFERENCES ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
;
GRANT SELECT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
;
GRANT UPDATE ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
;   
GRANT CONTROL ON EAADMIN.V_ALERT_REPORT TO USER EAADMIN
;
GRANT DELETE ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILPRD
;
GRANT INSERT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILPRD
;
GRANT REFERENCES ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILPRD
;
GRANT SELECT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILPRD
;
GRANT UPDATE ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILPRD
;
GRANT DELETE ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
;
GRANT INSERT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
;
GRANT REFERENCES ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
;
GRANT SELECT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
;
GRANT UPDATE ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
;   



-- TRAILSST
GRANT CONTROL ON EAADMIN.V_ALERT_RED_AGING TO USER EAADMIN
;
GRANT REFERENCES ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILSTG
;
GRANT SELECT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILSTG
;
GRANT REFERENCES ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
;
GRANT SELECT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILUPD
; 
GRANT CONTROL ON EAADMIN.V_ALERTS TO USER EAADMIN
;
GRANT REFERENCES ON EAADMIN.V_ALERTS TO GROUP TRAILSTG
;
GRANT SELECT ON EAADMIN.V_ALERTS TO GROUP TRAILSTG
;
GRANT REFERENCES ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
;
GRANT SELECT ON EAADMIN.V_ALERTS TO GROUP TRAILUPD
; 
GRANT CONTROL ON EAADMIN.V_ALERT_REPORT TO USER EAADMIN
;
GRANT REFERENCES ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILSTG
;
GRANT SELECT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILSTG
;
GRANT REFERENCES ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
;
GRANT SELECT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILUPD
; 


--TRAILSRP
GRANT REFERENCES ON EAADMIN.V_ALERTS TO GROUP TRAILRPT
;
GRANT SELECT ON EAADMIN.V_ALERTS TO GROUP TRAILRPT
; 
GRANT REFERENCES ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILRPT
;
GRANT SELECT ON EAADMIN.V_ALERT_RED_AGING TO GROUP TRAILRPT
; 
GRANT REFERENCES ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILRPT
;
GRANT SELECT ON EAADMIN.V_ALERT_REPORT TO GROUP TRAILRPT
; 
