-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER_LOG';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER_SW';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HARDWARE';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HS_COMPOSITE';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HW_LPAR';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_INSTALLED_SW';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_LICENSE';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_PVU';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_SOFTWARE';


-- COMMIT ;


-- CONNECT TO TRAILSPD USER XXX USING XXX;


DELETE FROM NEWASN.IBMSNAP_PRUNCNTL WHERE 
CNTL_ALIAS = 'TRAILSRP'
 AND APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_SW_LPAR';


-- COMMIT ;


