-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_CUSTOMER'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_CUSTOMER'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER_LOG') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_CUSTOMER_LOG'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER_LOG') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_CUSTOMER_LOG'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER_SW') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_CUSTOMER_SW'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_CUSTOMER_SW') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_CUSTOMER_SW'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HARDWARE') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_HARDWARE'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HARDWARE') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_HARDWARE'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HS_COMPOSITE') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_HS_COMPOSITE'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HS_COMPOSITE') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_HS_COMPOSITE'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HW_LPAR') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_HW_LPAR'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_HW_LPAR') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_HW_LPAR'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_INSTALLED_SW') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_INSTALLED_SW'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_INSTALLED_SW') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_INSTALLED_SW'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_LICENSE') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_LICENSE'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_LICENSE') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_LICENSE'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_PVU') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_PVU'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_PVU') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_PVU'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_SOFTWARE') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_SOFTWARE'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_SOFTWARE') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_SOFTWARE'));


-- COMMIT ;


-- CONNECT TO TRAILSRP USER XXX USING XXX;


DELETE FROM ASN.IBMSNAP_SUBS_COLS WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_SW_LPAR') OR 
  (WHOS_ON_FIRST = 'F' 
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_SW_LPAR'));


DELETE FROM ASN.IBMSNAP_SUBS_MEMBR WHERE 
 APPLY_QUAL = 'PD_TO_RP_QUAL'
 AND SET_NAME = 'RPREP1'
 AND ((WHOS_ON_FIRST = 'S'
 AND TARGET_OWNER = 'EAADMIN'
 AND TARGET_TABLE = 'RECON_SW_LPAR') OR 
  (WHOS_ON_FIRST = 'F'
   AND TARGET_OWNER = 'EAADMIN'
   AND TARGET_TABLE = 'RECON_SW_LPAR'));


-- COMMIT ;




