//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 05:31:23 PM EST 
//

package com.ibm.asset.swkbt.domain;

public enum PlatformsEnum {

	AIX("AIX"), LINUX("LINUX"), SUN("SUN"), HPUX("HPUX"), UNIX("UNIX"), WINDOWS(
			"WINDOWS"), I_5_OS("I5OS"), ANY("ANY"), Z_OS("z/OS");

	private final String value;

	PlatformsEnum(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static PlatformsEnum fromValue(String v) {
		for (PlatformsEnum c : PlatformsEnum.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}