CREATE VIEW EAADMIN.V_RECON_LICENSING_QUEUE( PK , ID , FK , CUSTOMER_ID ,ACTION ,TABLE,REMOTE_USER ,RECORD_TIME ) 
AS SELECT 'RECON_INSTALLED_SW' || ACTION || CAST(ID AS CHAR(16)),ID ,INSTALLED_SOFTWARE_ID ,CUSTOMER_ID ,ACTION ,'RECON_INSTALLED_SW' ,REMOTE_USER,RECORD_TIME FROM EAADMIN.RECON_INSTALLED_SW WHERE ACTION = 'LICENSING'
UNION ALL 
SELECT 'RECON_LICENSE' || ACTION|| CAST(ID AS CHAR(16)) ,ID ,LICENSE_ID ,CUSTOMER_ID ,ACTION ,'RECON_LICENSE',REMOTE_USER ,RECORD_TIME FROM EAADMIN.RECON_LICENSE WHERE ACTION <> 'DELETE'