/*
 * Created on Jan 19, 2005
 *
 * TODO To change the template for this generated file go to
 * Window - Preferences - Java - Code Style - Code Templates
 */
package com.ibm.ea.bravo.framework.common;

import com.ibm.ea.bravo.framework.properties.DelegateProperties;

/**
 * @author Thomas
 * 
 * TODO To change the template for this generated type comment go to Window -
 * Preferences - Java - Code Style - Code Templates
 */
public class Constants {
	public static final String ACTIVE = "ACTIVE";
	public static final String TOOL_USER_GROUP = "com.ibm.ea.bravo.user";
	public static final String SCAN_TEAM_GROUP = "Scan Team";
	public static final String TOOL_ADMIN_GROUP = "com.ibm.ea.bravo.admin";
	public static final String SOFTWARE_LPAR_HEARTBEAT = "softwareLparHeartbeat";
	public static final String TAB = "\t";
	public static final String ASSET_ADMIN_GROUP = "com.ibm.ea.asset.admin";
	public static final String COMMA = ",";
	public static final String EA_ADMIN_GROUP = "com.ibm.ea.admin";
	public static final String SUCCESS = "success";
	public static final String ADMIN = "admin";
	public static final String DB_SCHEMA = "/var/bravo/bravo.schema.sql";
	public static final String NAME_SEARCH = "Name";
	public static final String USER = "user";
	public static final String TYPE_SEARCH = "Type";
	public static final String ACCOUNT_DISCREPANCIES = "accountSWComponentDiscrepancies";
	public static final String GLOBAL_DISCREPANCIES = "globalDiscrepancies";
	public static final String MAINFRAME_SCAN = "mainframeScan";
	public static final String GLOBAL_SUMMARY = "globalSummary";
	public static final String HARDWARE_LPAR_ONLY = "hardwareLparOnly";
	public static final String ALL = "all";
	public static final String SCRT_REPORT_FILE = "scrtReportFile";
	public static final String SOFTWARE_LPAR_ONLY = "softwareLparOnly";
	public static final String STATUS = "status";
	public static final String ACCOUNT_ASSETS = "accountAssets";
	public static final String SW_MULTI_REPORT = "softwareMulti";
	public static final String INTERNET = "internet";
	public static final String ACCOUNT_SOFTWARE = "accountSoftware";
	public static final String SOFTWARE_DISCREPANCY_BLANK_FILE = "/opt/IBMIHS/htdocs/en_US/downloads/BRAVO Mass Missing SW Discrepancy Template.xls";
	public static final String AUTHORIZED_ASSETS_BLANK_FILE = "/opt/IBMIHS/htdocs/en_US/downloads/BRAVO Authorized Assets Template.xls";
	public static final String HWCOUNT = "HWCOUNT";
	public static final String DEFINITION_SEARCH = "Definition";
	public static final String ONHOLD = "ON-HOLD";
	public static final String REMOVED = "REMOVED";
	public static final String HWCATEGORY = "hwcategory";
	public static final String ACCOUNT_ACCESS = "account.access";
	public static final String CONFIDENTIAL = "IBM Confidential";
	public static final String POSITIVE_NUMBER = "positive.number";

	public static final String CONF_DIR = "/opt/bravo/conf/";
	public static final String APP_PROPERTIES = CONF_DIR + "bravo.properties";
	public static final String HIBERNATE_PROPERTIES = CONF_DIR
			+ "hibernate.properties";
	public static final String[] PROPERTY_FILES = { APP_PROPERTIES,
			HIBERNATE_PROPERTIES };
	/* Constants for ftp'ing the file to another server */
	public static final int MAX_FTP_ATTEMPTS = 5;
	public static final int FTP_RETRY_WAIT_SECS = 30 * 1000;
	public static final String FTP_HOST = "tap.raleigh.ibm.com";
	public static final String FTP_DIR_TLCMZ = "mf_scan/";
	public static final String FTP_DIR_DORANA = "dorana/";
	public static final String FTP_DIR_MANUAL = "/var/ftp/manual";
	public static final String FTP_ID = "USERNAMEHERE";
	public static final String FTP_PW = "PASSWORDHERE";
	public static final String FTP_ID_ANONYMOUS = "anonymous";

	public static final String SOFTWARE_DISCREPANCY_BLANK = "softwareDiscrepancyBlank";
	public static final String AUTHORIZED_ASSETS_BLANK = "authorizedAssetsBlank";
	public static final String USER_CONTAINER = "user_container";
	public static final String MACHINETYPE_SEARCH = "name";
	public static final String HARDWARE_INVALID = "hardware.invalid";
	public static final String PROCESSOR_COUNT = "processorCount";
	public static final String LOCKED = "locked";
	public static final String TAP_ADMIN_GROUP = "com.ibm.tap.admin";
	public static final String SEARCHTYPE = "searchtype";
	public static final String COMMENT = "comment";
	public static final String LENGTH_MAX_255 = "length.max.255";
	public static final String BANK_ACCOUNT_LIST = "bankAccountList";
	public static final String ACCOUNT_STATISTICS = "accountStatistics";
	public static final String REPORT = "report";
	public static final String REPORT_DIR = "/opt/IBMIHS/htdocs/en_US/sam/report";
	public static final String MACHINE_TYPE_EXISTS = "machineType.exists";
	public static final int MAX_COMMENT_LENGTH = 255;
	public static final String TRUE = "true";
	public static final String HARDWARE_STATISTICS = "hardwareStatistics";
	public static final String SOFTWARE_LPAR_IP_ADDRESS = "softwareLparIPAddress";
	public static final String SOFTWARE_LPAR_HDISK = "softwareLparHDisk";	
	public static final String SOFTWARE_LPAR_MEM_MOD = "softwareLparMemMod";
	public static final String SOFTWARE_LPAR_ADC = "softwareLparADC";
	public static final String SOFTWARE_LPAR_PROCESSOR = "softwareLparProcessor";
	public static final String SOFTWARE_STATISTICS = "softwareStatistics";
	public static final String HARDWARE_STATUS = "hardwareStatus";
	public static final String TIVOLI = "tivoli";
	public static final String TIVOLI_CONFIRM = "tivoliConfirm";
	public static final String CONTACT_HW_LIST = "contactHwList";
	public static final String SOFTWARE_DISCREPANCY = "softwareDiscrepancy";
	public static final String SCRT_REPORT = "scrtReport";
	public static final String AUTHORIZED_ASSETS = "authorizedAssets";
	public static final String FALSE = "false";
	public static final String REQUIRED = "required";
	public static final String SOFTWARE_LPAR_EFF_EXISTS = "softwareLparEff.exists";
	public static final String ACTION = "action";
	public static final String CRUD_UPDATE = "Update";
	public static final String CRUD_EDIT = "Edit";
	public static final String CUSTOMER = "customer";
	public static final String SOFTWARE = "software";
	public static final String TAR_FILE_EXISTS = "tarfile.exists";
	public static final String ACCOUNT_INVALID = "account.invalid";
	public static final String ACTION_UPDATE = "Update";
	public static final String[] VIEW_BUTTONS = { "Edit", "Add New", "Cancel" };
	public static final String CRUD_CREATE = "Create";
	public static final String CRUD_ADD_NEW = "Add New";
	public static final String CONTACT = "contact";
	public static final String N = "N";
	public static final String FORMBUTTONS = "formbuttons";
	public static final String ACTION_ADD = "Add";
	public static final String CATEGORY = "category";
	public static final String VIEW = "view";
	public static final String CONTACT_LIST = "contactList";
	public static final String MACHINE_TYPE_LIST_TYPE = "machineTypeListType";
	public static final String NONE = "NONE";
	public static final String COMMENT_LIST = "commentList";
	public static final String SIGNATURE_LIST = "signatureList";
	public static final String SOFTWARE_LPAR = "softwareLpar";
	public static final String ACTION_VIEW = "View";
	public static final String FILTER_LIST = "filterList";
	public static final String MAINFRAME = "mainframe";
	public static final String CRUD_CANCEL = "Cancel";
	public static final String VM_LIST = "vmList";
	public static final String TADZ_LIST = "tadzList";
	public static final String SOFTWARE_LPAR_EFF = "softwareLparEff";
	public static final String[] EDIT_BUTTONS = { "Update", "Delete",
			"Cancel Edit" };
	public static final String SOFT_AUDIT_LIST = "softAuditList";
	public static final String DORANA_LIST = "doranaList";
	public static final String ACTION_DELETE = "Delete";
	public static final String EDIT = "edit";
	public static final String SEARCH = "search";
	public static final String UPDATE = "Update";
	public static final String CANCEL = "cancel";
	public static final String BATCH_INVALID = "batch.invalid";
	public static final String MACHINETYPE_LISTALL = "all";
	public static final String MACHINETYPE_LISTALLACTIVE = "allactive";
	public static final String EMAIL = "email";
	public static final String MACHINETYPE = "machineType";
	public static final String INVALID_SEARCH_REGEX = "^%*$";
	public static final String INIT = "init";
	public static final String INVALID = "invalid";
	public static final String ERROR = "error";
	public static final String LPAR = "lpar";
	public static final String CRUD_CANCEL_EDIT = "Cancel Edit";
	public static final String REFERER = "Referer";
	public static final String RECENTADD_SEARCH = "recentadd";
	public static final String UNKNOWN_ERROR = "unknown.error";
	public static final String UNKNOWN_DB_ERROR = "db.unknown.error";
	public static final String ACCOUNT = "account";
	public static final String ID = "id";
	public static final String STRING = "string";
	public static final String ACCOUNT_SEARCH = "Account";
	public static final String ACCOUNT_ID = "accountId";
	public static final String DEPARTMENT_SEARCH = "Department";
	public static final String TYPE = "type";
	public static final int MAX_SEARCH_RESULT_SIZE = 300;
	public static final int MAX_SWASSET_SEARCH_RESULT_SIZE = 25;
	public static final String HOSTNAME_SEARCH = "Hostname";
	public static final String HARDWARE = "hardware";
	public static final String SCRT_RECORDS = "scrtRecords";
	public static final String SOURCE = "source";
	public static final String SERIAL_SEARCH = "SerialNum";
	public static final String SOFTWARE_NAME = "softwareName";
	public static final String DEPARTMENT = "department";
	public static final String HOME = "home";
	public static final String[] CREATE_BUTTONS = { "Create", "Cancel" };
	public static final String RESULTS = "results";
	public static final String CUSTOMER_ID = "customerid";
	public static final String SEARCH_TOO_LARGE = "search.too.large";
	public static final String SEARCH_SWASSET_TOO_LARGE = "search.swasset.too.large";
	public static final String SWASSET_NOT_AUTHORIZED = "swasset.authorization.none";
	public static final String SUBMITTED_FOR_DELETION = "swasset.delete.submit";
	public static final String MANUAL_SUBMITTED_FOR_DELETION = "manual.delete.submit";
	public static final String ALREADY_SUBMITTED_FOR_DELETION = "manual.queue.exists";
	public static final String SELECT_FOR_MANUAL_DELETION = "manual.delete.select";
	public static final String SELECT_FOR_LPAR_DELETION = "lpar.delete.select";
	public static final String LIST = "list";
	public static final String CREATE = "create";
	public static final String MANUFACTURER = "manufacturer";
	public static final String LICENSE_LEVEL = "licenseLevel";
	public static final String ACCOUNT_HWCOUNT = "hwcount";
	public static final String ACCOUNT_NAME = "accountname";
	public static final int BATCH_PLUGIN_DELAY_SECS = 2 * 1000;
	public static final int BATCH_PLUGIN_PERIOD_SECS = 2 * 1000;
	public static final String FILE_NAME = "filename";
	public static final String FILE_NAME_REQUIRED = "filename.required";
	public static final String FILE_TOO_LARGE = "file.too.large";
	public static final String FILE_ZERO = "file.zero";
	public static final int FILE_MAX_SIZE = 500 * 1024;
	public static final String NO_PREVIEW_ALLOWD = "parser.no.preview";
	public static final String UPLOAD_DIR = "/var/bravo/upload/";
	public static final String UPLOAD_DIR_TAR = "/var/ftp/scan/";
	public static final String SCRT_REPORT_DIR = "/var/bravo/scrt_reports/";
	public static final String SEARCH_PARAM = "searchparam";
	public static final String HWLPAR = "hwlpar";
	public static final String BPLIST = "bplist";
	public static final String HARDWARE_DETAILS = "hardwaredetails";
	public static final String DISCREPANCY_TYPE_ID_MISSING = "2";
	public static final String CONTEXT = "context";
	public static final String HARDWARE_LPAR = "hardwareLpar";
	public static final String SEARCH_INVALID = "search.invalid";
	public static final String MISSING = "MISSING";
	public static final String DISCREPANCY_TYPE = "discrepancyType";
	public static final String INVALID_CATEGORY = "invalidCategory";
	public static final String SEARCH_ACCOUNT_NAME = "Account Name";
	public static final String SEARCH_ACCOUNT_NUMBER = "Account Number";
	public static final String TITLE_ACTION = "titleaction";
	public static final String CRUD_VIEW = "View";
	public static final String NAME = "name";
	public static final String CRUD_DELETE = "Delete";
	public static final String MACHINE_TYPE = "machineType";
	public static final String SOFTWARE_ID = "softwareId";
	public static final String SERIAL = "serial";
	public static final String COUNTRY = "country";
	public static final String REMOTE_USER = "remoteUser";
	public static final String LPAR_NAME = "lparName";
	public static final String LPAR_NAME_EXISTS = "lparName.exists";
	public static final String DB = "db";
	public static final String BLUEPAGES = "bluepages.ibm.com";
	public static final String BLUEGROUPS = "bluegroups.ibm.com";
	public static final int BLUEGROUP_SUBDEPTH = 4;
	public static final String ICON_SYSTEM_STATUS_OK = "http://w3.ibm.com/ui/v8/images/icon-system-status-ok.gif";
	public static final String ICON_SYSTEM_STATUS_NA = "http://w3.ibm.com/ui/v8/images/icon-system-status-na.gif";
	public static final String ICON_SYSTEM_STATUS_ALERT = "http://w3.ibm.com/ui/v8/images/icon-system-status-alert.gif";
	public static final String LPAR_ID = "lparId";
	public static final String DETAIL = "detail";
	public static final String DEFINITION = "definition";
	public static final String FALSE_HIT_DISCREPANCY = "FALSE HIT";
	public static final String INVALID_DISCREPANCY = "INVALID";
	public static final String VALID_DISCREPANCY = "VALID";
	public static final String MISSING_DISCREPANCY = "MISSING";
	public static final String NONE_DISCREPANCY = "NONE";
	public static final String TADZ_DISCREPANCY = "TADZ";
	public static final String INACTIVE = "INACTIVE";
	public static final String IMAGETAG_ADD = "imagetag_add";
	public static final String IMAGETAG_DELETE = "imagetag_delete";
	public static final String IMAGETAG = "imageTag";
	public static final String IMAGE_ADD = "<img src=\"http://w3.ibm.com/ui/v8/images/icon-link-add-dark.gif\" width=\"13\" height=\"13\" alt=\"add\"/>";
	public static final String IMAGE_DELETE = "<img src=\"http://w3.ibm.com/ui/v8/images/icon-link-delete-dark.gif\" width=\"13\" height=\"13\" alt=\"delete\" />";
	public static final String DOWNLOAD_MIME_TYPE = "application/download";
	public static final String HDW = "HDW";
	public static final String EMAIL_PROCESSOR_KEY = "batch.email.processor";
	public static final String CNC_REQUEST_FORM = "cncRequestForm";
	public static final String CNO_REQUEST_FORM = "cnoRequestForm";
	public static final String DPE_REQUEST_FORM = "dpeRequestForm";
	public static final String APP_SERVER_NAME = "tap.raleigh.ibm.com";
	public static final String EMAIL_ADDRESS_FROM = "tap@tap.raleigh.ibm.com";
	public static final int EMAIL_PLUGIN_DELAY_SECS = 15 * 1000;
	public static final int EMAIL_PLUGIN_PERIOD_SECS = 15 * 1000;
	public static final String IMAGE_LOCKED = "<img src=\"http://w3.ibm.com/ui/v8/images/icon-document-locked.gif\" width=\"11\" height=\"12\" alt=\"locked document icon\" />";
	public static final String RECON_INSTALLED_SW = "UPDATE_INST_SW";
	public static final String RECON_EFF_PROC = "UPDATE_EFF_PROC";
	public static final String DISPLAY_OS = "displayOS";
	public static final String DISPLAY_BIOS = "displayBios";
	public static final String DISPLAY_MISC = "displayMisc";
	public static final String DISPLAY_PROCESSORS = "displayProcessors";
	public static final String DISPLAY_MEMORY = "displayMemory";
	public static final String ALERT = "ALERT";
	public static final String BANK_ACCOUNT = "bankAccount";
	public static final String CONNECTED = "CONNECTED";
	public static final String DISCONNECTED = "DISCONNECTED";
	public static final String PROHIBIT_BANK_ACCOUNT_LIST ="TAD4Z";
	public static final String SYSTEM_SCHEDULE_STATUS_LIST =
			"systemScheduleStatusList";
	public static final String BANK_ACCOUNT_JOB_LIST = "bankAccountJobList";
	public static final String BANK_ACCOUNT_NAMES = "bankAccountNames";
	public static final String APMM_ACCOUNT_LIST ="DK002090,DK006074,DK006412,DK006421,DK120494,DK593039,DK593066,DKMDI,DK002090";
	public static final String Is_APMM_ACCOUNT ="isAPMMAccount";
}
