ALTER TABLE "EAADMIN"."HARDWARE" ADD COLUMN MULTI_TENANT VARCHAR(1)
;
ALTER TABLE "EAADMIN"."HARDWARE" ADD COLUMN HARDWARE_COMPLEX VARCHAR(20)
;
REORG TABLE EAADMIN.HARDWARE;

INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_ST_QUAL', 'STREP1', 'S', 'EAADMIN', 'HARDWARE', 'MULTI_TENANT', 'A', 'N', MAX(COLNO + 1), 'MULTI_TENANT' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_ST_QUAL' AND SET_NAME='STREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='HARDWARE';
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_ST_QUAL', 'STREP1', 'S', 'EAADMIN', 'HARDWARE', 'HARDWARE_COMPLEX', 'A', 'N', MAX(COLNO + 1), 'HARDWARE_COMPLEX' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_ST_QUAL' AND SET_NAME='STREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='HARDWARE';
 
