ALTER TABLE "EAADMIN"."HARDWARE" ADD COLUMN MULTI_TENANT VARCHAR(1)
;
ALTER TABLE TRAILSPD_CD.HARDWARE ADD COLUMN MULTI_TENANT VARCHAR(1); 
ALTER TABLE TRAILSPD_CC.HARDWARE ADD COLUMN MULTI_TENANT VARCHAR(1); 
ALTER TABLE "EAADMIN"."HARDWARE" ADD COLUMN HARDWARE_COMPLEX VARCHAR(20)
;
ALTER TABLE TRAILSPD_CD.HARDWARE ADD COLUMN HARDWARE_COMPLEX VARCHAR(20); 
ALTER TABLE TRAILSPD_CC.HARDWARE ADD COLUMN HARDWARE_COMPLEX VARCHAR(20); 
REORG TABLE EAADMIN.HARDWARE;
REORG TABLE TRAILSPD_CD.HARDWARE;
REORG TABLE TRAILSPD_CC.HARDWARE;
RUNSTATS ON TABLE EAADMIN.HARDWARE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CD.HARDWARE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;
RUNSTATS ON TABLE TRAILSPD_CC.HARDWARE ON ALL COLUMNS WITH DISTRIBUTION ON ALL COLUMNS AND DETAILED INDEXES ALL ALLOW WRITE ACCESS UTIL_IMPACT_PRIORITY 50
;