package IBM::Schema::CNDB::CndbDownloadView;

use strict;
use warnings;

use base 'DBIx::Class';

__PACKAGE__->load_components("Core");
__PACKAGE__->table("CNDB_DOWNLOAD_VIEW");
__PACKAGE__->add_columns(
  "customer_number",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "sector_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "industry_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "customer_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 64 },
  "pod_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "app_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "customer_type_name",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "dpe_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cost_pool_owner_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cno_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "fa_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "fa_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tower",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "area",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sub_group",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "division",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "state",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "country",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "postal_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address_title",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address1",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "address2",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "city",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "central_recv_supp",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "dock_contact_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "taxable_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "exemption_reason",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "charge_to_dept",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "clli",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "major",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "lpid",
  { data_type => "VARCHAR", is_nullable => 0, size => 255 },
  "function",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "igf_customer_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "branch_office_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "maint_only",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "sw_only_cn",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_number",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_type",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sign_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "contract_start_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "contract_end_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "contract_value",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_orders",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_hw_transfer",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_hw_transfer_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "contract_sw_transfer",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "contract_sw_transfer_count",
  { data_type => "INTEGER", is_nullable => 1, size => 10 },
  "field",
  { data_type => "VARCHAR", is_nullable => 0, size => 0 },
  "claim_work_item",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "claim_activity_code",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "status",
  { data_type => "VARCHAR", is_nullable => 0, size => 32 },
  "active_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "cnc_comments",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "validation_date",
  { data_type => "VARCHAR", is_nullable => 1, size => 10 },
  "validated_by",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "validation_status",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "abbr_customer_name",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "transition_team_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "focal_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "legacy_area",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "hostname_prefix",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "tme_object_id",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "tlm_deploy",
  { data_type => "VARCHAR", is_nullable => 1, size => 64 },
  "cno_exception_justification",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cn_sw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "cn_hw_asset_email",
  { data_type => "VARCHAR", is_nullable => 1, size => 255 },
  "account_number",
  { data_type => "BIGINT", is_nullable => 0, size => 19 },
);


# Created by DBIx::Class::Schema::Loader v0.04003 @ 2007-12-12 17:12:36
# DO NOT MODIFY THIS OR ANYTHING ABOVE! md5sum:I+0NGpXudh66Hh0Gj7kCYw


# You can replace this text with custom content, and it will be preserved on regeneration
1;
