DROP VIEW EAADMIN.v_mqt_alert_report;
create view EAADMIN.v_mqt_alert_report(ID, CUSTOMER_ID,DISPLAY_NAME,ASSET_TYPE,RECORD_TIME,ASSIGNED,RED,YELLOW,GREEN,RED91,RED121,RED151,RED181,RED366,ASSET_TOTAL ) as  
Select MSL.ID,MSL.CUSTOMER_ID,MSL.DISPLAY_NAME,MSL.ASSET_TYPE,MSL.RECORD_TIME,MSL.ASSIGNED,MSL.RED,MSL.YELLOW,MSL.GREEN,MSL.RED91,MSL.RED121,MSL.RED151,MSL.RED181,MSL.RED366,MSL.ASSET_TOTAL from EAADMIN.MQT_OP_METRICS_SWLM MSL
Union ALL 
Select MST.ID,MST.CUSTOMER_ID,MST.DISPLAY_NAME,MST.ASSET_TYPE,MST.RECORD_TIME,MST.ASSIGNED,MST.RED,MST.YELLOW,MST.GREEN,MST.RED91,MST.RED121,MST.RED151,MST.RED181,MST.RED366,MST.ASSET_TOTAL from eaadmin.MQT_OP_METRICS_SWTRACKING MST
;
GRANT CONTROL ON EAADMIN.v_mqt_alert_report TO USER EAADMIN		
;			
GRANT SELECT ON EAADMIN.v_mqt_alert_report TO GROUP TRAILUPD
;	
GRANT SELECT ON EAADMIN.v_mqt_alert_report TO GROUP TRAILSTG
;