package com.ibm.ea.bravo.framework.download;

import java.io.OutputStream;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.log4j.Logger;

import com.ibm.ea.bravo.framework.common.Constants;
import com.ibm.ea.bravo.framework.report.ReportBase;
import com.ibm.ea.bravo.report.DelegateReport;
import com.ibm.ea.utils.EaUtils;

/**
 * A basic servlet that returns a PNG image file generated by JFreeChart.
 * <P>
 * This class is described in the JFreeChart Developer Guide.
 * 
 * @author David Gilbert
 */
public class DownloadIt extends HttpServlet {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static final Logger logger = Logger.getLogger(DownloadIt.class);

	public void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException {

		// get the parameters
		String reportName = getParameter(request, Constants.NAME);
		String accountId = getParameter(request, Constants.ACCOUNT_ID);
		String softwareId = getParameter(request, Constants.SOFTWARE_ID);

		// report arguments
		String[] args = new String[] { accountId, softwareId };

		try {

			if (reportName.equalsIgnoreCase(Constants.SCRT_REPORT)) {
				response.setContentType("text/plain");
				String scrtReportFile = getParameter(request,
						Constants.SCRT_REPORT_FILE);
				logger.debug("[downloadit] scrtReportFile=" + scrtReportFile);
				args = new String[] { accountId, scrtReportFile };
			} else if (reportName.equalsIgnoreCase(Constants.SW_MULTI_REPORT)) {
				response.setContentType("application/zip");
			} else {
				response.setContentType("application/vnd.ms-excel");
			}
			// get the output stream for the report
			OutputStream outputStream = response.getOutputStream();
			// response.setContentType(Constants.DOWNLOAD_MIME_TYPE);

			// create the appropriate report
			ReportBase report = DelegateReport.getReport(reportName,
					outputStream);

			// if the report is legit, execute it
			if (report != null)
				report.execute(args, request);

		} catch (Exception e) {
			logger.error(e, e);
		}

	}

	private String getParameter(HttpServletRequest request, String name) {
		String parameter = new String();

		parameter = request.getParameter(name);
		if (EaUtils.isBlank(parameter)) {
			Object o = request.getAttribute(name);
			if (o != null) {
				parameter = (String) o;
			}
		}

		return parameter;
	}
}