drop table "EAADMIN"."MQT_ALERT_REPORT";

ALTER TABLE "EAADMIN"."ALERT_UNLICENSED_SW" ALTER COLUMN "TYPE" SET DATA TYPE varchar(16);

ALTER TABLE "TRAILSPD_CC"."ALERT_UNLICENSED_SW" ALTER COLUMN "TYPE" SET DATA TYPE varchar(16);
ALTER TABLE "TRAILSPD_CD"."ALERT_UNLICENSED_SW" ALTER COLUMN "TYPE" SET DATA TYPE varchar(16);



CREATE SUMMARY TABLE EAADMIN.MQT_ALERT_REPORT
(
   ID,
   CUSTOMER_ID,
   DISPLAY_NAME,
   ASSET_TYPE,
   RECORD_TIME,
   ASSIGNED,
   RED,
   YELLOW,
   GREEN,
   RED91,
   RED121,
   RED151,
   RED181,
   RED366,
   ASSET_TOTAL
)
AS
(
   SELECT
   ID ,
   CUSTOMER_ID ,
   DISPLAY_NAME ,
   ASSET_TYPE ,
   CURRENT TIMESTAMP ,
   ASSIGNED ,
   RED ,
   YELLOW ,
   GREEN ,
   RED91 ,
   RED121 ,
   RED151 ,
   RED181 ,
   RED366 ,
   ASSET_TOTAL
   FROM
   (
      SELECT
      'HARDWARE' || CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'HW W/O HW LPAR' AS DISPLAY_NAME ,
      CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AH.REMOTE_USER IS NULL THEN NULL WHEN AH.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM(CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) > 365 THEN 1 ELSE 0 END) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AH.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END) AS RED91 ,
      SUM
      (
         CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' THEN 1 ELSE 0 END
      )
      AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON H.CUSTOMER_ID = C.CUSTOMER_ID
      AND H.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_HARDWARE AH ON AH.HARDWARE_ID = H.ID
      AND AH.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'HARDWARE' || CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      'HW W/O HW LPAR' ,
      CASE WHEN H.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'HARDWARE' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'HW W/O HW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HARDWARE' || 'WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'HW W/O HW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HARDWARE_LPAR' || CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'HW LPAR W/O SW LPAR' AS DISPLAY_NAME ,
      CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AHL.REMOTE_USER IS NULL THEN NULL WHEN AHL.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHL.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      SUM
      (
         CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' THEN 1 ELSE 0 END
      )
      AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.CUSTOMER_ID = C.CUSTOMER_ID
      AND HL.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON H.ID = HL.HARDWARE_ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID LEFT OUTER
      JOIN EAADMIN.ALERT_HW_LPAR AHL ON AHL.HARDWARE_LPAR_ID = HL.ID
      AND AHL.OPEN = 1
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'HARDWARE_LPAR' || CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      'HW LPAR W/O SW LPAR' ,
      CASE WHEN HL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'HARDWARE_LPAR' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'HW LPAR W/O SW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'HARDWARE_LPAR' || 'WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'HW LPAR W/O SW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SOFTWARE_LPAR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SW LPAR W/O HW LPAR' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ASL.REMOTE_USER IS NULL THEN NULL WHEN ASL.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(ASL.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(SL.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID
      AND SL.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_SW_LPAR ASL ON SL.ID = ASL.SOFTWARE_LPAR_ID
      AND ASL.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'SOFTWARE_LPAR' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      'SW LPAR W/O HW LPAR' ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'SOFTWARE_LPAR' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SW LPAR W/O HW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'SOFTWARE_LPAR' || 'WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SW LPAR W/O HW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'EXPIRED_SCAN' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'OUTDATED SW LPAR' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN AES.REMOTE_USER IS NULL THEN NULL WHEN AES.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 0 AND 45 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY > 365 THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 151 AND 180 THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN AES.ID IS NOT NULL AND DAYS(CURRENT TIMESTAMP) - DAYS(SL.SCANTIME) - C.SCAN_VALIDITY BETWEEN 91 AND 120 THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(SL.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.SOFTWARE_LPAR SL ON C.CUSTOMER_ID = SL.CUSTOMER_ID
      AND SL.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_EXPIRED_SCAN AES ON AES.SOFTWARE_LPAR_ID = SL.ID
      AND AES.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'EXPIRED_SCAN' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      'OUTDATED SW LPAR' ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'EXPIRED_SCAN' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'OUTDATED SW LPAR' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'EXPIRED_SCAN' || 'WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'OUTDATED SW LPAR' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'UNLICENSED_IBM_SW' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'UNLICENSED IBM SW' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ( ( AUS.REMOTE_USER IS NULL ) AND ( AUS.OPEN = 1 ) ) THEN NULL
				WHEN ( ( AUS.REMOTE_USER != 'STAGING' ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS ASSIGNED ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 90 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 46 AND 90) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) < 46) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 365) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 181 AND 365 ) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 151 AND 180 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 121 AND 150 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 91 AND 120 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(AUS.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID LEFT OUTER
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID LEFT OUTER
      JOIN EAADMIN.INSTALLED_SOFTWARE IS ON SL.ID = IS.SOFTWARE_LPAR_ID
      AND IS.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_UNLICENSED_SW AUS ON AUS.INSTALLED_SOFTWARE_ID = IS.ID
      and aus.type = 'IBM'
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'UNLICENSED_IBM_SW' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      'UNLICENSED IBM SW' ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'UNLICENSED_IBM_SW' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'UNLICENSED IBM SW' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'UNLICENSED_IBM_SW' || 'WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'UNLICENSED IBM SW' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'UNLICENSED_ISV_SW' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'UNLICENSED ISV SW' AS DISPLAY_NAME ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END AS ASSET_TYPE ,
      SUM( CASE WHEN ( ( AUS.REMOTE_USER IS NULL ) AND ( AUS.OPEN = 1 ) ) THEN NULL
				WHEN ( ( AUS.REMOTE_USER != 'STAGING' ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS ASSIGNED ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 90 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 46 AND 90) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) < 46) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) > 365) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS RED366 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 181 AND 365 ) AND ( AUS.OPEN = 1 ) )  THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 151 AND 180 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED151 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 121 AND 150 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN ( ( DAYS(CURRENT TIMESTAMP) - DAYS(AUS.CREATION_TIME) BETWEEN 91 AND 120 ) AND ( AUS.OPEN = 1 ) ) THEN 1 ELSE 0 END ) AS RED91 ,
      COUNT(AUS.ID) AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.SOFTWARE_LPAR SL ON SL.CUSTOMER_ID = C.CUSTOMER_ID LEFT OUTER
      JOIN EAADMIN.HW_SW_COMPOSITE HSC ON SL.ID = HSC.SOFTWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE_LPAR HL ON HL.ID = HSC.HARDWARE_LPAR_ID LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON HL.HARDWARE_ID = H.ID LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID LEFT OUTER
      JOIN EAADMIN.INSTALLED_SOFTWARE IS ON SL.ID = IS.SOFTWARE_LPAR_ID
      AND IS.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_UNLICENSED_SW AUS ON AUS.INSTALLED_SOFTWARE_ID = IS.ID
      AND AUS.TYPE = 'ISV'
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'UNLICENSED_ISV_SW' || CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID ,
      'UNLICENSED ISV SW' ,
      CASE WHEN SL.CUSTOMER_ID IS NULL THEN 'NON-WORKSTATION' WHEN MT.TYPE != 'WORKSTATION' OR MT.TYPE IS NULL THEN 'NON-WORKSTATION' ELSE MT.TYPE END
      UNION
      ALL
      SELECT
      'UNLICENSED_ISV_SW' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'UNLICENSED ISV SW' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      UNION
      ALL
      SELECT
      'UNLICENSED_ISV_SW' || 'WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'UNLICENSED ISV SW' AS DISPLAY_NAME ,
      'WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
	  UNION
      ALL
	  SELECT
      'HWCFGDTA' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1b: HW Box Critical Configuration Data Populated' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      SUM( CASE WHEN AHC.REMOTE_USER IS NULL THEN NULL WHEN AHC.REMOTE_USER = 'STAGING' THEN 0 ELSE 1 END ) AS ASSIGNED ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) > 90 THEN 1 ELSE 0 END ) AS RED ,
      SUM(CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 46 AND 90 THEN 1 ELSE 0 END ) AS YELLOW ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) < 46 THEN 1 ELSE 0 END ) AS GREEN ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) > 365 THEN 1 ELSE 0 END) AS RED366 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 181 AND 365 THEN 1 ELSE 0 END ) AS RED181 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 151 AND 180 THEN 1 ELSE 0 END) AS RED151 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 121 AND 150 THEN 1 ELSE 0 END ) AS RED121 ,
      SUM( CASE WHEN DAYS(CURRENT TIMESTAMP) - DAYS(AHC.CREATION_TIME) BETWEEN 91 AND 120 THEN 1 ELSE 0 END) AS RED91 ,
      SUM
      (
         CASE WHEN H.HARDWARE_STATUS = 'ACTIVE' THEN 1 ELSE 0 END
      )
      AS ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C LEFT OUTER
      JOIN EAADMIN.HARDWARE H ON H.CUSTOMER_ID = C.CUSTOMER_ID
      AND H.STATUS = 'ACTIVE' LEFT OUTER
      JOIN EAADMIN.ALERT_HARDWARE_CFGDATA AHC ON AHC.HARDWARE_ID = H.ID
      AND AHC.OPEN = 1 LEFT OUTER
      JOIN EAADMIN.MACHINE_TYPE MT ON H.MACHINE_TYPE_ID = MT.ID
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
      GROUP BY 'HWCFGDTA' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) ,
      C.CUSTOMER_ID
      UNION
      ALL
      SELECT
      'HWCFGDTA' || 'NON-WORKSTATION' || CAST(C.CUSTOMER_ID AS CHAR(16)) AS ID ,
      C.CUSTOMER_ID AS CUSTOMER_ID ,
      'SOM1b: HW Box Critical Configuration Data Populated' AS DISPLAY_NAME ,
      'NON-WORKSTATION' AS ASSET_TYPE ,
      0 as ASSIGNED ,
      0 as RED ,
      0 as YELLOW ,
      0 as GREEN ,
      0 as RED366 ,
      0 as RED181 ,
      0 as RED151 ,
      0 as RED121 ,
      0 as RED91 ,
      0 as ASSET_TOTAL
      FROM EAADMIN.CUSTOMER C
      WHERE C.SW_LICENSE_MGMT = 'YES'
      AND C.STATUS = 'ACTIVE'
   )
   AS T
)
DATA INITIALLY DEFERRED REFRESH DEFERRED ENABLE QUERY OPTIMIZATION MAINTAINED BY SYSTEM IN "MISC" INDEX IN "MISCINDEX";


GRANT CONTROL ON "EAADMIN "."MQT_ALERT_REPORT" TO USER EAADMIN
;
GRANT DELETE ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILPRD
;
GRANT INSERT ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILPRD
;
GRANT SELECT ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILPRD
;
GRANT UPDATE ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILPRD
;
GRANT DELETE ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILUPD
;
GRANT INSERT ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILUPD
;
GRANT SELECT ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILUPD
;
GRANT UPDATE ON "EAADMIN "."MQT_ALERT_REPORT" TO GROUP TRAILUPD
;

SET INTEGRITY FOR "EAADMIN"."MQT_ALERT_REPORT" immediate checked
;



