//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 05:31:23 PM EST 
//

package com.ibm.asset.trails.domain;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

@Entity(name = "Alias")
@org.hibernate.annotations.Entity(mutable = false)
@Table(name = "ALIAS", uniqueConstraints = @UniqueConstraint(columnNames = { "name" }))
public class Alias implements Serializable {

	private static final long serialVersionUID = -1675162072680736936L;

	@Id
	@Column(name = "ID")
	private Long id;

	@Basic
	@Column(name = "NAME")
	private String name;

	@Basic
	@Column(name = "PREFERRED")
	private Boolean preferred;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Boolean getPreferred() {
		return preferred;
	}

	public void setPreferred(Boolean preferred) {
		this.preferred = preferred;
	}

}
