package com.ibm.asset.trails.domain;

// Generated Oct 23, 2009 4:03:54 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mips generated by hbm2java
 */
@Entity
@Table(name = "MIPS", schema = "EAADMIN")
@NamedQuery(name = "listModel", query = "SELECT DISTINCT m.id.model FROM Mips m ORDER BY model")
public class Mips implements java.io.Serializable {

	private MipsId id;
	private BigDecimal mips;
	private String upduser;
	private Date updstamp;
	private String updIntranetId;
	private String status;

	public Mips() {
	}

	public Mips(MipsId id, BigDecimal mips, String upduser, Date updstamp,
			String updIntranetId, String status) {
		this.id = id;
		this.mips = mips;
		this.upduser = upduser;
		this.updstamp = updstamp;
		this.updIntranetId = updIntranetId;
		this.status = status;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "machineTypeId", column = @Column(name = "MACHINE_TYPE_ID", nullable = false)),
			@AttributeOverride(name = "model", column = @Column(name = "MODEL", nullable = false, length = 20)),
			@AttributeOverride(name = "mipsGroup", column = @Column(name = "MIPS_GROUP", nullable = false, length = 3)),
			@AttributeOverride(name = "vendor", column = @Column(name = "VENDOR", nullable = false, length = 10)),
			@AttributeOverride(name = "mipsvendor", column = @Column(name = "MIPSVENDOR", nullable = false, length = 10)) })
	public MipsId getId() {
		return this.id;
	}

	public void setId(MipsId id) {
		this.id = id;
	}

	@Column(name = "MIPS", nullable = false, precision = 7)
	public BigDecimal getMips() {
		return this.mips;
	}

	public void setMips(BigDecimal mips) {
		this.mips = mips;
	}

	@Column(name = "UPDUSER", nullable = false, length = 8)
	public String getUpduser() {
		return this.upduser;
	}

	public void setUpduser(String upduser) {
		this.upduser = upduser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDSTAMP", nullable = false, length = 26)
	public Date getUpdstamp() {
		return this.updstamp;
	}

	public void setUpdstamp(Date updstamp) {
		this.updstamp = updstamp;
	}

	@Column(name = "UPD_INTRANET_ID", nullable = false, length = 60)
	public String getUpdIntranetId() {
		return this.updIntranetId;
	}

	public void setUpdIntranetId(String updIntranetId) {
		this.updIntranetId = updIntranetId;
	}

	@Column(name = "STATUS", nullable = false, length = 32)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
