package com.ibm.asset.trails.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity
@Table(name = "MQT_OP_METRICS_SWLM")
@org.hibernate.annotations.Entity
@NamedQueries({
		@NamedQuery(name = "accountAlertOperationalReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)  GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountAlertOperationalReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)  GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountAlertOperationalReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)  GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365) AND OPLM.account.department = :department   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :country AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :countryCode AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365) AND OPLM.account.sector = :sector   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :countryCode AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByGeographyByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNameAlertOperationalReportByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,   OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,   OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365) AND OPLM.account.department = :department   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :country AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :countryCode AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.department = :department AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365) AND OPLM.account.sector = :sector   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :countryCode AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByGeographyByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "accountByNumberAlertOperationalReportByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.sector = :sector AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "alertOperationalReportByAccount", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name,  OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account = :account AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name,  OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "alertOperationalReportByAccountName", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.name = :accountName AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.name, OPLM.account.account, OPLM.account.id, OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.name, OPLM.account.countryCode.name, OPLM.account.sector.name, OPLM.account.accountType.name, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "countryCodeAlertOperationalReport", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "countryCodeAlertOperationalReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "countryCodeAlertOperationalReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "countryCodeAlertOperationalReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.name, OPLM.account.countryCode.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReport", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "departmentAlertOperationalReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.department.name, OPLM.account.department.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "geographyAlertOperationalReport", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.geography.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.region.geography.name, OPLM.account.countryCode.region.geography.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "regionAlertOperationalReport", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.region.name, OPLM.account.countryCode.region.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.region.name, OPLM.account.countryCode.region.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "regionAlertOperationalReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.countryCode.region.name, OPLM.account.countryCode.region.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.countryCode.region.name, OPLM.account.countryCode.region.id, OPLM.displayName ORDER BY OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReport", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region.geography = :geography AND OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY  OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY  OPLM.account.sector.name, OPLM.displayName"),
		@NamedQuery(name = "sectorAlertOperationalReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOperationalReport(OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName, SUM(OPLM.red), SUM(OPLM.yellow), SUM(OPLM.green), SUM(OPLM.assetTotal)) FROM MqtOpMetricsSwlm OPLM WHERE  OPLM.account.countryCode.region = :region AND OPLM.account.countryCode = :countryCode AND (OPLM.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(OPLM.account.contractSignDate) >= 365)   GROUP BY OPLM.account.sector.name, OPLM.account.sector.id, OPLM.displayName ORDER BY OPLM.account.sector.name, OPLM.displayName")
 })
public class MqtOpMetricsSwlm{

	@Id
	@Column(name = "ID", nullable = false)
	private String id;

	@ManyToOne
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	private Account account;

	@Column(name = "DISPLAY_NAME", nullable = false)
	private String displayName;

	@Column(name = "ASSET_TYPE", nullable = true)
	private String assetType;

	@Column(name = "RECORD_TIME", nullable = false)
	private Date recordTime;

	@Column(name = "ASSIGNED", nullable = true)
	private Integer assigned;

	@Column(name = "RED", nullable = true)
	private Integer red;

	@Column(name = "YELLOW", nullable = true)
	private Integer yellow;

	@Column(name = "GREEN", nullable = true)
	private Integer green;

	@Column(name = "RED91", nullable = true)
	private Integer red91;

	@Column(name = "RED121", nullable = true)
	private Integer red121;

	@Column(name = "RED151", nullable = true)
	private Integer red151;

	@Column(name = "RED181", nullable = true)
	private Integer red181;

	@Column(name = "RED366", nullable = true)
	private Integer red366;

	@Column(name = "ASSET_TOTAL", nullable = false)
	private Integer assetTotal;

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getAssetType() {
		return assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	public Integer getAssigned() {
		return assigned;
	}

	public void setAssigned(Integer assigned) {
		this.assigned = assigned;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Integer getGreen() {
		return green;
	}

	public void setGreen(Integer green) {
		this.green = green;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getRecordTime() {
		return recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public Integer getRed() {
		return red;
	}

	public void setRed(Integer red) {
		this.red = red;
	}

	public Integer getYellow() {
		return yellow;
	}

	public void setYellow(Integer yellow) {
		this.yellow = yellow;
	}

	public Integer getAssetTotal() {
		return assetTotal;
	}

	public void setAssetTotal(Integer assetTotal) {
		this.assetTotal = assetTotal;
	}

	public Integer getRed121() {
		return red121;
	}

	public void setRed121(Integer red121) {
		this.red121 = red121;
	}

	public Integer getRed151() {
		return red151;
	}

	public void setRed151(Integer red151) {
		this.red151 = red151;
	}

	public Integer getRed181() {
		return red181;
	}

	public void setRed181(Integer red181) {
		this.red181 = red181;
	}

	public Integer getRed366() {
		return red366;
	}

	public void setRed366(Integer red366) {
		this.red366 = red366;
	}

	public Integer getRed91() {
		return red91;
	}

	public void setRed91(Integer red91) {
		this.red91 = red91;
	}

}
