//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.15 at 05:31:23 PM EST 
//

package com.ibm.asset.trails.domain;

import java.io.Serializable;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity(name = "Platform")
@org.hibernate.annotations.Entity(mutable = false)
@Table(name = "PLATFORM")
public class Platform implements Serializable {

	private static final long serialVersionUID = 8997050255317421671L;

	@Id
	@Column(name = "ID")
	private Long id;

	@Basic
	@Column(name = "SWKBT_ID")
	private int swkbtId;

	@Basic
	@Column(name = "NAME")
	@Enumerated(EnumType.STRING)
	private PlatformsEnum name;

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public int getSwkbtId() {
		return swkbtId;
	}

	public void setSwkbtId(int swkbtId) {
		this.swkbtId = swkbtId;
	}

	public PlatformsEnum getName() {
		return name;
	}

	public void setName(PlatformsEnum name) {
		this.name = name;
	}

}
