package com.ibm.asset.trails.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity
@Table(name = "MQT_OP_METRICS_SWTRACKING")
@org.hibernate.annotations.Entity
@NamedQueries({
		@NamedQuery(name = "accountSwTrackingAlertReportByGeography", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)  GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountSwTrackingAlertReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)  GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountSwTrackingAlertReportByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)  GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365) AND STR.account.department = :department   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :country AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :countryCode AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365) AND STR.account.sector = :sector   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :countryCode AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByGeographyByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNameSwTrackingAlertReportByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,   STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,   STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365) AND STR.account.department = :department   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :country AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :countryCode AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.department = :department AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365) AND STR.account.sector = :sector   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :countryCode AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByGeographyByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "accountByNumberSwTrackingAlertReportByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.sector = :sector AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "SwTrackingAlertReportByAccount", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name,  STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account = :account AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name,  STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "SwTrackingAlertReportByAccountName", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.name = :accountName AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.name, STR.account.account, STR.account.id, STR.account.countryCode.region.geography.name, STR.account.countryCode.region.name, STR.account.countryCode.name, STR.account.sector.name, STR.account.accountType.name, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "countryCodeSwTrackingAlertReport", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "countryCodeSwTrackingAlertReportByGeography", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "countryCodeSwTrackingAlertReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "countryCodeSwTrackingAlertReportByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.name, STR.account.countryCode.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReport", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByGeography", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "departmentSwTrackingAlertReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.department.name, STR.account.department.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.department.name, STR.account.department.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "geographySwTrackingAlertReport", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.region.geography.name, STR.account.countryCode.region.geography.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.region.geography.name, STR.account.countryCode.region.geography.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "regionSwTrackingAlertReport", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.region.name, STR.account.countryCode.region.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.region.name, STR.account.countryCode.region.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "regionSwTrackingAlertReportByGeography", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.countryCode.region.name, STR.account.countryCode.region.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.countryCode.region.name, STR.account.countryCode.region.id, STR.displayName ORDER BY STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReport", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByGeography", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region.geography = :geography AND STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY  STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByRegion", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY  STR.account.sector.name, STR.displayName"),
		@NamedQuery(name = "sectorSwTrackingAlertReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.SwTrackingAlertReport(STR.account.sector.name, STR.account.sector.id, STR.displayName, SUM(STR.red), SUM(STR.yellow), SUM(STR.green), SUM(STR.assetTotal)) FROM SwTrackingAlertReport STR WHERE  STR.account.countryCode.region = :region AND STR.account.countryCode = :countryCode AND (STR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(STR.account.contractSignDate) >= 365)   GROUP BY STR.account.sector.name, STR.account.sector.id, STR.displayName ORDER BY STR.account.sector.name, STR.displayName"),

})
public class SwTrackingAlertReport {

	@Id
	@Column(name = "PK", nullable = false)
	private String id;

	@ManyToOne
	@JoinColumn(name = "CUSTOMER_ID", nullable = false)
	private Account account;

	@Column(name = "DISPLAY_NAME", nullable = false)
	private String displayName;

	@Column(name = "ASSET_TYPE", nullable = true)
	private String assetType;

	@Column(name = "RECORD_TIME", nullable = false)
	private Date recordTime;

	@Column(name = "ASSIGNED", nullable = true)
	private Integer assigned;

	@Column(name = "RED", nullable = true)
	private Integer red;

	@Column(name = "YELLOW", nullable = true)
	private Integer yellow;

	@Column(name = "GREEN", nullable = true)
	private Integer green;

	@Column(name = "RED91", nullable = true)
	private Integer red91;

	@Column(name = "RED121", nullable = true)
	private Integer red121;

	@Column(name = "RED151", nullable = true)
	private Integer red151;

	@Column(name = "RED181", nullable = true)
	private Integer red181;

	@Column(name = "RED366", nullable = true)
	private Integer red366;

	@Column(name = "ASSET_TOTAL", nullable = false)
	private Integer assetTotal;

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getAssetType() {
		return assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	public Integer getAssigned() {
		return assigned;
	}

	public void setAssigned(Integer assigned) {
		this.assigned = assigned;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Integer getGreen() {
		return green;
	}

	public void setGreen(Integer green) {
		this.green = green;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getRecordTime() {
		return recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public Integer getRed() {
		return red;
	}

	public void setRed(Integer red) {
		this.red = red;
	}

	public Integer getYellow() {
		return yellow;
	}

	public void setYellow(Integer yellow) {
		this.yellow = yellow;
	}

	public Integer getAssetTotal() {
		return assetTotal;
	}

	public void setAssetTotal(Integer assetTotal) {
		this.assetTotal = assetTotal;
	}

	public Integer getRed121() {
		return red121;
	}

	public void setRed121(Integer red121) {
		this.red121 = red121;
	}

	public Integer getRed151() {
		return red151;
	}

	public void setRed151(Integer red151) {
		this.red151 = red151;
	}

	public Integer getRed181() {
		return red181;
	}

	public void setRed181(Integer red181) {
		this.red181 = red181;
	}

	public Integer getRed366() {
		return red366;
	}

	public void setRed366(Integer red366) {
		this.red366 = red366;
	}

	public Integer getRed91() {
		return red91;
	}

	public void setRed91(Integer red91) {
		this.red91 = red91;
	}

}
