package com.ibm.asset.trails.domain;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;


@Entity
@Table(name = "V_MQT_ALERT_REPORT")
@org.hibernate.annotations.Entity
@NamedQueries({
		@NamedQuery(name = "accountAlertOverviewReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.department = :department  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "alertOverviewReportByAccount", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account = :account  GROUP BY VMAR.account.name, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByGeographyByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertOverviewReportByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.sector = :sector  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertOverviewReport", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR  GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertOverviewReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography  GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertOverviewReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region  GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertOverviewReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region  GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReport", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertOverviewReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "geographyAlertOverviewReport", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.geography.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR  GROUP BY VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.geography.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "regionAlertOverviewReport", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR  GROUP BY VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "regionAlertOverviewReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography  GROUP BY VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReport", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertOverviewReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertOverviewReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.assigned), SUM(VMAR.red), SUM(VMAR.yellow), SUM(VMAR.green)) FROM VmqtAlertReport VMAR WHERE VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode  GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),

		@NamedQuery(name = "accountAlertRedAgingReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.name, VMAR.account.countryCode.name, VMAR.account.sector.name, VMAR.account.accountType.name, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.name, VMAR.account.countryCode.name, VMAR.account.sector.name, VMAR.account.accountType.name, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :country AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.name, VMAR.account.countryCode.name, VMAR.account.sector.name, VMAR.account.accountType.name, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.name, VMAR.account.countryCode.name, VMAR.account.sector.name, VMAR.account.accountType.name, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.name, VMAR.account.countryCode.name, VMAR.account.sector.name, VMAR.account.accountType.name, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.name, VMAR.account.countryCode.name, VMAR.account.sector.name, VMAR.account.accountType.name, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByRegionByCountryCodeByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByRegionByDepartment", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.department = :department AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByGeographyByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByRegionByCountryCodeBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "accountAlertRedAgingReportByRegionBySector", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.sector = :sector AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.account, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "alertRedAgingReportByAccount", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.name, VMAR.account.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account = :account AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)  GROUP BY VMAR.account.name, VMAR.account.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertRedAgingReport", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertRedAgingReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertRedAgingReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "countryCodeAlertRedAgingReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.name, VMAR.account.countryCode.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReport", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "departmentAlertRedAgingReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.department.name, VMAR.account.department.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "geographyAlertRedAgingReport", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.geography.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.region.geography.name, VMAR.account.countryCode.region.geography.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "regionAlertRedAgingReport", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "regionAlertRedAgingReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.countryCode.region.name, VMAR.account.countryCode.region.id, VMAR.displayName ORDER BY VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReport", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByGeography", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByGeographyByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByGeographyByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByGeographyByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region.geography = :geography AND VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByRegion", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName"),
		@NamedQuery(name = "sectorAlertRedAgingReportByRegionByCountryCode", query = "SELECT new com.ibm.asset.trails.form.AlertRedAgingReport(VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName, SUM(VMAR.red91), SUM(VMAR.red121), SUM(VMAR.red151), SUM(red181), SUM(red366)) FROM VmqtAlertReport VMAR WHERE  VMAR.account.countryCode.region = :region AND VMAR.account.countryCode = :countryCode AND (VMAR.account.softwareFinancialManagement = 'YES' OR DAYS(CURRENT_TIMESTAMP) - DAYS(VMAR.account.contractSignDate) >= 365)   GROUP BY VMAR.account.sector.name, VMAR.account.sector.id, VMAR.displayName ORDER BY VMAR.account.sector.name, VMAR.displayName") })
public class VmqtAlertReport {

	@Id
	@Column(name = "ID")
	private String id;

	@ManyToOne
	@JoinColumn(name = "CUSTOMER_ID")
	private Account account;

	@Column(name = "DISPLAY_NAME")
	private String displayName;

	@Column(name = "ASSET_TYPE")
	private String assetType;

	@Column(name = "RECORD_TIME")
	private Date recordTime;

	@Column(name = "ASSIGNED")
	private Integer assigned;

	@Column(name = "RED")
	private Integer red;

	@Column(name = "YELLOW")
	private Integer yellow;

	@Column(name = "GREEN")
	private Integer green;

	@Column(name = "RED91")
	private Integer red91;

	@Column(name = "RED121")
	private Integer red121;

	@Column(name = "RED151")
	private Integer red151;

	@Column(name = "RED181")
	private Integer red181;

	@Column(name = "RED366")
	private Integer red366;

	@Column(name = "ASSET_TOTAL")
	private Integer assetTotal;

	public Account getAccount() {
		return account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	public String getAssetType() {
		return assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	public Integer getAssigned() {
		return assigned;
	}

	public void setAssigned(Integer assigned) {
		this.assigned = assigned;
	}

	public String getDisplayName() {
		return displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	public Integer getGreen() {
		return green;
	}

	public void setGreen(Integer green) {
		this.green = green;
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Date getRecordTime() {
		return recordTime;
	}

	public void setRecordTime(Date recordTime) {
		this.recordTime = recordTime;
	}

	public Integer getRed() {
		return red;
	}

	public void setRed(Integer red) {
		this.red = red;
	}

	public Integer getYellow() {
		return yellow;
	}

	public void setYellow(Integer yellow) {
		this.yellow = yellow;
	}

	public Integer getAssetTotal() {
		return assetTotal;
	}

	public void setAssetTotal(Integer assetTotal) {
		this.assetTotal = assetTotal;
	}

	public Integer getRed121() {
		return red121;
	}

	public void setRed121(Integer red121) {
		this.red121 = red121;
	}

	public Integer getRed151() {
		return red151;
	}

	public void setRed151(Integer red151) {
		this.red151 = red151;
	}

	public Integer getRed181() {
		return red181;
	}

	public void setRed181(Integer red181) {
		this.red181 = red181;
	}

	public Integer getRed366() {
		return red366;
	}

	public void setRed366(Integer red366) {
		this.red366 = red366;
	}

	public Integer getRed91() {
		return red91;
	}

	public void setRed91(Integer red91) {
		this.red91 = red91;
	}

}
