ALTER TABLE EAADMIN.CUSTOMER ADD COLUMN CUSTOMER_PREFIX VARCHAR(16);
ALTER TABLE EAADMIN.CUSTOMER ADD COLUMN CUSTOMER_SUFFIX VARCHAR(16);
ALTER TABLE EAADMIN.CUSTOMER ADD COLUMN HOSTNAME_PREFIX VARCHAR(64);
REORG TABLE EAADMIN.CUSTOMER;
INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_RP_QUAL', 'RPREP1', 'S', 'EAADMIN', 'CUSTOMER', 'CUSTOMER_PREFIX', 'A', 'N', MAX(COLNO + 1), 'CUSTOMER_PREFIX' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='CUSTOMER';
 
 INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_RP_QUAL', 'RPREP1', 'S', 'EAADMIN', 'CUSTOMER', 'CUSTOMER_SUFFIX', 'A', 'N', MAX(COLNO + 1), 'CUSTOMER_SUFFIX' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='CUSTOMER';
 
  INSERT INTO ASN.IBMSNAP_SUBS_COLS ( 
 APPLY_QUAL, SET_NAME, WHOS_ON_FIRST, 
 TARGET_OWNER, TARGET_TABLE, TARGET_NAME, 
 COL_TYPE, IS_KEY, COLNO, EXPRESSION 
 )SELECT 'PD_TO_RP_QUAL', 'RPREP1', 'S', 'EAADMIN', 'CUSTOMER', 'HOSTNAME_PREFIX', 'A', 'N', MAX(COLNO + 1), 'HOSTNAME_PREFIX' 
 FROM ASN.IBMSNAP_SUBS_COLS  WHERE APPLY_QUAL='PD_TO_RP_QUAL' AND SET_NAME='RPREP1' AND WHOS_ON_FIRST='S' AND 
 TARGET_OWNER='EAADMIN' AND TARGET_TABLE='CUSTOMER';